### PR TITLE
Do not require hostname for non-persistent MySQL connection and require for persistent

### LINKED ISSUE #3942: MySQLi connection fails or triggers a notice if the hostname is not specified
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.0-dev

#### Summary

When attempting to establish a non-persistent connection without a hostname:
```php
echo (new MysqliConnection([], 'root', ''))
    ->query('SELECT VERSION()')
    ->fetch()[0], PHP_EOL;

// Notice: Undefined index: host in src/Driver/Mysqli/MysqliConnection.php on line 52
// 5.7.27
```
When attempting to establish a persistent connection without a hostname:
```php
new MysqliConnection(['persistent' => true], 'root', '');

// Notice: Undefined index: host in src/Driver/Mysqli/MysqliConnection.php on line 52
// MysqliException: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in src/Driver/Mysqli/MysqliConnection.php on line 72
```

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #3942.

According to the [documentation](https://www.php.net/mysqli_real_connect), the hostname may be omitted and will default to "localhost". However, given the fact that the persistent connection flag is passed as part of the hostname, the hostname cannot be omitted for persistent connection.

The issue is not reproducible on 2.x because the "Undefined index" notice is suppressed by the error handler:
https://github.com/doctrine/dbal/blob/35beaca3bed81ad4983e58706ae38688de34a853/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L67-L70

### CODE REVIEW

File: src/Driver/Mysqli/HostnameRequired.php [hunk 1]
```diff
@@ -0,0 +1,13 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Doctrine\DBAL\Driver\Mysqli;
+
+final class HostnameRequired extends MysqliException
+{
+    public static function fromPersistentConnection() : self
```
Comment (greg0ire) [inline src/Driver/Mysqli/HostnameRequired.php:9]: With that naming, I would expect a connection argument. How about this?
```suggestion
    public static function forPersistentConnection() : self
```

File: src/Driver/Mysqli/HostnameRequired.php [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+    {
+        return new self('Hostname is required for persistent connection');
```
Comment (greg0ire) [inline src/Driver/Mysqli/HostnameRequired.php:11]: I'd go with either
```suggestion
        return new self('The host parameter is required for persistent connections');
```

or

```suggestion
        return new self('host parameter required for persistent connection');
```

File: src/Driver/Mysqli/HostnameRequired.php (hunk 1 above)
Comment (morozov) [reply src/Driver/Mysqli/HostnameRequired.php:9]: Agree. Let's do that.

File: src/Driver/Mysqli/HostnameRequired.php (hunk 2 above)
Comment (morozov) [reply src/Driver/Mysqli/HostnameRequired.php]: Not sure about the articles but I'd keep the "connection" singular since the exception is about a single connection.

File: src/Driver/Mysqli/HostRequired.php [hunk 3]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Doctrine\DBAL\Driver\Mysqli;
+
+/**
+ * @internal
```
Comment (morozov) [inline src/Driver/Mysqli/HostRequired.php:8]: Also, note that I marked it as `@internal` (there's a plan to do the same for the rest of the named exceptions in newer versions). This way, we can rework them at any time w/o breaking other's code who should rely only on higher-level classes and interfaces.

**Review by greg0ire — APPROVED** [review]
