### PR TITLE
Enforce consistent constructor in dynamically instantiated classes

### LINKED ISSUE #4511: Signature of wrapper Connection constructor is not enforced
Psalm on level 2:

```
ERROR: UnsafeInstantiation - lib/Doctrine/DBAL/DriverManager.php:236:16 - Cannot safely instantiate class Doctrine\DBAL\Connection with "new $class_name" as its constructor might change in child classes (see https://psalm.dev/229)
        return new $wrapperClass($params, $driver, $config, $eventManager);
```

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

Closes #4511.

### CODE REVIEW

File: lib/Doctrine/DBAL/Platforms/Keywords/KeywordList.php [hunk 1]
```diff
@@ -8,6 +8,8 @@
 
 /**
  * Abstract interface for a SQL reserved keyword dictionary.
+ *
+ * @psalm-consistent-constructor
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/Keywords/KeywordList.php:12]: This can be removed in `4.0.x` thanks to https://github.com/doctrine/dbal/pull/4583.

**Review by derrabus — APPROVED** [review]
