### PR TITLE
Handle binding invalid named parameter errors

### LINKED ISSUE #5130: PDO\Exception doesn't handle driver-specific error code being NULL
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.0

When a PDO error occurs, the ::errorInfo() method returns the internal error code of the internal PDO driver.
This error then goes into the Doctrine\Dbal\Driver\Pdo\Exception class, which converts the information from PDO::errorInfo() into a Doctrine exception.
What Doctrine means is that PDO::errorInfo() always returns an integer error code, but sometimes it may return null.
Because of this, I get the following exception: [](https://postimg.cc/TKGZJypw)

This is because PDO does not return an error code for error HY093 in Postgresql:
[](https://postimg.cc/zL47pM0j)

I won't say any more about it. I'm just bringing this point to your attention.)

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #5130.

From the [documentation](https://www.php.net/manual/en/pdo.errorinfo.php):
> If the SQLSTATE error code is not set or there is no driver-specific error, the elements following element 0 will be set to null.

### CODE REVIEW

File: tests/Functional/StatementTest.php [hunk 1]
```diff
@@ -236,6 +241,28 @@ public function testBindParamWithNullLength(): void
...
+            self::markTestSkipped('pdo_oci on PHP 7 does not report this error');
+        }
+
+        $platform  = $this->connection->getDatabasePlatform();
+        $statement = $this->connection->prepare($platform->getDummySelectSQL(':foo'));
+        $this->expectException(DriverException::class);
+
+        // prevent the PHPUnit error handler from handling the warning that oci_bind_by_name() may trigger
+        if (TestUtil::isDriverOneOf('oci8')) {
+            $this->iniSet('error_reporting', (string) (E_ALL & ~E_WARNING));
```
Comment (morozov) [inline tests/Functional/StatementTest.php:260]: This will have to be replaced with a `@` before `oci_bind_by_name()` in `4.0.x` since the error there is reported as a driver exception.

File: tests/Functional/StatementTest.php [hunk 2]
```diff
@@ -236,6 +241,28 @@ public function testBindParamWithNullLength(): void
         self::assertEquals(1, $stmt->executeQuery()->fetchOne());
     }
 
+    public function testBindInvalidNamedParameter(): void
+    {
+        if (TestUtil::isDriverOneOf('ibm_db2', 'mysqli', 'sqlsrv')) {
+            self::markTestSkipped('The driver does not support named statement parameters');
+        }
+
+        if (PHP_VERSION_ID < 80000 && TestUtil::isDriverOneOf('pdo_oci')) {
```
Comment (morozov) [inline tests/Functional/StatementTest.php:250]: This will have to be removed in `4.0.x`.

**Review by greg0ire — APPROVED** [review]

**Review by derrabus — APPROVED** [review]
