### PR TITLE
Fix handling existing SQL Server column comment when other properties change

### LINKED ISSUE #3400: Wrong column comment setting command in migrations of SQL Server
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.8.0

#### Summary

The condition to use different SQL command to set column comment in SQL Server is not proper.

#### Current behaviour

When I attempted to alter columns (already had comments) in SQL Server with a migration function of Laravel (it uses doctrine/dbal in alteration of columns), the migration sequence was aborted with an SQL execution error if a same column comment was specified as previous. The error message was as follows:

```
Illuminate\Database\QueryException  : SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Property cannot be added. Property 'MS_Description' already exists for 'dbo.table_name.column_name'. (SQL: EXEC sp_addextendedproperty N'MS_Description', N'column_comment', N'SCHEMA', 'dbo', N'TABLE', 'table_name', N'COLUMN', column_name)

  at /project_dir/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Property cannot be added. Property 'MS_Description' already exists for 'dbo.table_name.column_name'.")
      /project_dir/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144

  2   PDOException::("SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Property cannot be added. Property 'MS_Description' already exists for 'dbo.table_name.column_name'.")
      /project_dir/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142
```

To change (not add) column comment, `sp_updateextendedproperty` should be used, but instead doctrine/dbal tries to use `sp_addextendedproperty` when a new comment is same as previous, which results in SQL execution error.

#### Solution
The causal code is here:
https://github.com/doctrine/dbal/blob/2b8513dc2ceedf81b7f9b014375d2f6d3f905e8f/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L509-L523

The line 517 should be corrected as follows:
```
-   } elseif ($hasComment) {
+   } elseif (! $hasFromComment && $hasComment) {
```

In my local environment, this correction solved the problem.

### LINKED ISSUE #4313: MSSQL incorrectly detected changes to a column comment
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1
| Database Server| docker: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
| Doctrine Driver| pdo_sqlsrv

#### Summary

When an entity has a column with a comment, I change the type of that column without changing the comment, Doctrine is not correctly finding the comment changes on the column.
I am getting an error 
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Property cannot be added. Property 'MS_Description' already exists for 'dbo.user.surname'.
```
After changing the column type and updating comments at the same time, it works fine.

#### Current behaviour

Schema updater tries to add a property that already exists and has not changed.

#### How to reproduce

1. Declare an entity with column with comment or add column with comment.
``` php
class User
{
    /**
     * @ORM\Column(type="integer", nullable=false, options={"comment":"Funky comment"})
     */
    private $surname;
}
```
`orm:schema-tool:update --dump-sql` output:
```
CREATE TABLE [user] (id INT IDENTITY NOT NULL, surname INT NOT NULL, PRIMARY KEY (id));
EXEC sp_addextendedproperty N'MS_Description', N'Funky comment', N'SCHEMA', 'dbo', N'TABLE', '[user]', N'COLUMN', surname;
```

2. Change this column type or requirement without changing the comment.
``` php
class User
{
    /**
     * @ORM\Column((type="string", length=100, nullable=true, options={"comment":"Funky comment"})
     */
    private $surname;
}
```
`orm:schema-tool:update --dump-sql` output:
```
ALTER TABLE [user] ALTER COLUMN surname NVARCHAR(100);
EXEC sp_addextendedproperty N'MS_Description', N'Funky comment', N'SCHEMA', 'dbo', N'TABLE', 'user', N'COLUMN', surname;
```

#### Expected behaviour

The schema updater should only update the column type without updating the comment unless it has changed.

### PR DESCRIPTION
**Pull request by trusek**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4313

#### Summary
Fix case when schema updater tries to add a property that already exists and has not changed.

I use fix mentioned by @msyfurukawa in #3416
Closes #3416

### CODE REVIEW

File: lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php [hunk 1]
```diff
@@ -532,7 +532,7 @@ public function getAlterTableSQL(TableDiff $diff)
                     );
                 } elseif ($hasFromComment && ! $hasComment) {
                     $commentsSql[] = $this->getDropColumnCommentSQL($diff->name, $column->getQuotedName($this));
-                } elseif ($hasComment) {
+                } elseif ($hasComment && ! $hasFromComment) {
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php:535]: Please change to `! $hasFromComment && $hasComment` for the order consistency with the previous conditions.

File: tests/Doctrine/Tests/DBAL/Functional/Schema/SQLServerSchemaManagerTest.php [hunk 2]
```diff
@@ -326,13 +328,29 @@ public function testColumnComments(): void
...
+            new Column(
+                'commented_req_change_column',
+                Type::getType('integer'),
+                ['comment' => 'Some comment', 'notnull' => true]
+            ),
+            ['comment', 'notnull'],
+            new Column(
+                'commented_req_change_column',
+                Type::getType('integer'),
+                ['comment' => 'Some comment', 'notnull' => false]
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/SQLServerSchemaManagerTest.php:343]: Since 'comment' is in the list of changed properties, should this one have some different value? Or if it's not changed, should it be removed from the list?

File: tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php [hunk 3]
```diff
@@ -1718,4 +1718,19 @@ private function expectCteWithMinAndMaxRowNums(
...
         self::assertEquals(sprintf($pattern, $expectedSql, $expectedMin, $expectedMax), $sql);
     }
+
+    public function testAlterTableWithSchemaSameColumnComments(): void
+    {
+        $tableDiff                          = new TableDiff('testschema.mytable');
+        $tableDiff->changedColumns['quota'] = new ColumnDiff(
+            'quota',
+            new Column('quota', Type::getType('integer'), ['comment' => 'A comment', 'notnull' => true]),
+            ['comment', 'notnull'],
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Platforms/AbstractSQLServerPlatformTestCase.php:1728]: If it's the same column comment, why is it the list of changed properties?

File: tests/Doctrine/Tests/DBAL/Functional/Schema/SQLServerSchemaManagerTest.php (hunk 2 above)
Comment (trusek) [reply tests/Doctrine/Tests/DBAL/Functional/Schema/SQLServerSchemaManagerTest.php:343]: "comment" should be removed from changed properties.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @trusek!
