### PR TITLE
Fix SQLite FK handling in altered tables

### LINKED ISSUE #7123: Table incorrectly indexes anonymous foreign key constraints
|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.10.1

#### Summary

Foreign key constraints within a `Table` model are indexed by name. For unnamed foreign key constraints, the name is auto-generated based on the referencing table name and the referenced column names. If there are two unnamed foreign key constraints on the same table that reference different tables but the same set of columns, one of them will silently override the other.

Consider the following valid MySQL schema definition:
```sql
CREATE TABLE t1 (
    id INT PRIMARY KEY
);

CREATE TABLE t2 (
    id INT PRIMARY KEY
);

CREATE TABLE t3 (
    id INT PRIMARY KEY,
    t_id INT,
    FOREIGN KEY (t_id) REFERENCES t1(id),
    FOREIGN KEY (t_id) REFERENCES t2(id)
);
```

The `t3` definition expressed in DBAL terms will look like the following (the PK is omitted for brevity):
```php
$table = new Table('t3');
$table->addColumn('id', 'integer');
$table->addColumn('t_id', 'integer');
$table->addForeignKeyConstraint('t1', ['id'], ['id']);
$table->addForeignKeyConstraint('t2', ['id'], ['id']);
```

It is expected that the resulting table definition has two foreign constraints, while in fact it contains only the most recently added one:
```php
$foreignKeyConstraints = $table->getForeignKeys();
echo count($foreignKeyConstraints), PHP_EOL;
// 1

$foreignKeyConstraint = current($foreignKeyConstraints);
echo $foreignKeyConstraint->getForeignTableName(), PHP_EOL;
// t2
```

### PR DESCRIPTION
**Pull request by santysisi**
Fixes #7123

#### Summary

Fixes incorrect handling of foreign keys in `SQLitePlatform` when altering tables.

Previously, `getForeignKeys` relied on constraint names as array keys, but this behavior has changed and now returns a list.

Solution:
- Added a `$keysByName` to link constraint names to their positions
- Used this `$keysByName` to correctly unset matching foreign keys by name

This ensures that only the appropriate constraints are removed during table alterations.

### CODE REVIEW

**Comment by santysisi** [comment]
Hi @morozov, I didn’t add a dedicated test in this PR because the following PR (which changes the deprecation into an error) effectively covers this new behavior. Without the fix introduced here, that next PR would fail, so it indirectly serves as a test for this change.

**Comment by morozov** [comment]
> Without the fix introduced here, that next PR would fail, so it indirectly serves as a test for this change.

Let's make one PR for both changes. Just push the second commit to the same branch. Otherwise, there's no way to validate the fix.

**Comment by santysisi** [comment]
I chose to pass a `string` instead of an `UnqualifiedName` as the second parameter of `ForeignKeyAlreadyExists` because the `key` can either come from a `UnqualifiedName` or be generated dynamically via `generateNameFromObjectColumnNames`.

That said, I’m open to changing it to `UnqualifiedName` like in `ForeignKeyDoesNotExist` if you think is a better option

File: src/Platforms/SQLitePlatform.php [hunk 1]
```diff
@@ -861,7 +861,23 @@ private function getForeignKeysInAlteredTable(TableDiff $diff): array
     {
         $oldTable    = $diff->getOldTable();
         $foreignKeys = $oldTable->getForeignKeys();
-        $nameMap     = $this->getDiffColumnNameMap($diff);
+        $keysByName  = [];
+        foreach ($foreignKeys as $key => $foreignKey) {
```
Comment (morozov) [inline src/Platforms/SQLitePlatform.php]: Instead of introducing a new loop, `$keysByName` could be populated in the existing one.

File: src/Platforms/SQLitePlatform.php [hunk 2]
```diff
@@ -905,7 +921,7 @@ private function getForeignKeysInAlteredTable(TableDiff $diff): array
                     ->getValue(),
             );
 
-            unset($foreignKeys[$constraintKey]);
+            unset($foreignKeys[$keysByName[$constraintKey]]);
```
Comment (morozov) [inline src/Platforms/SQLitePlatform.php]: `$keysByName[$constraintKey]` isn't guaranteed to be set (dropping a FK that doesn't exist). This should  be an exception. Let's make an it assertion for now and revisit later.

File: src/Platforms/SQLitePlatform.php [hunk 3]
```diff
@@ -917,7 +933,11 @@ private function getForeignKeysInAlteredTable(TableDiff $diff): array
                         ->getValue(),
                 );
 
-                $foreignKeys[$constraintKey] = $constraint;
+                if (isset($keysByName[$constraintKey])) {
+                    $foreignKeys[$keysByName[$constraintKey]] = $constraint;
```
Comment (morozov) [inline src/Platforms/SQLitePlatform.php]: This looks like an error state to me. If a constraint with the same name already exists, it shouldn't be silently overwritten.

Let's make an it assertion for now that `$keysByName[$constraintKey]` is not set and revisit later.

Also, the new name and key need to be added to `$keysByName` to prevent the overwrite by the subsequent ones.

File: src/Platforms/SQLitePlatform.php [hunk 4]
```diff
@@ -917,7 +933,11 @@ private function getForeignKeysInAlteredTable(TableDiff $diff): array
...
+                } else {
+                    $foreignKeys[] = $constraint;
```
Comment (morozov) [inline src/Platforms/SQLitePlatform.php]: This code doesn't need to be duplicated. The logic, at a high level, should look like the following:
```
if the constraint is named
    make sure that there's no existing constraint with the same name
    update the name-key map
end

add the new constraint
```

File: UPGRADE.md [hunk 5]
```diff
@@ -8,6 +8,11 @@ awareness about deprecated code.
 
 # Upgrade to 5.0
 
+## BC BREAK: changes in `Table` class
+
+The `Table` class no longer accepts `foreignKeyConstraints`
+with duplicate keys.
```
Comment (morozov) [inline UPGRADE.md]: This probably should be "duplicate names".

File: src/Schema/Exception/ForeignKeyAlreadyExists.php [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+
+use Doctrine\DBAL\Schema\Name\OptionallyQualifiedName;
+use Doctrine\DBAL\Schema\SchemaException;
+use LogicException;
+
+use function sprintf;
+
+final class ForeignKeyAlreadyExists extends LogicException implements SchemaException
+{
+    public static function new(OptionallyQualifiedName $tableName, string $foreignKeyName): self
```
Comment (morozov) [inline src/Schema/Exception/ForeignKeyAlreadyExists.php]: `$foreignKeyName` could still be an `UnqualifiedName`. If it's auto-generated, you can convert it using `Unqualified::unquoted()`.

I have a pending PR that will not require generating array keys for unnamed constraints, so this won't be necessary. See `OptionallyUnqualifiedNamedObjectSet`.

**Comment by santysisi** [comment]
Hi, thanks for your suggestions!
I've made the changes based on your feedback. I think they're really good.
Please let me know if there's anything else I should adjust.

File: src/Platforms/SQLitePlatform.php [hunk 7]
```diff
@@ -905,7 +917,11 @@ private function getForeignKeysInAlteredTable(TableDiff $diff): array
                     ->getValue(),
             );
 
-            unset($foreignKeys[$constraintKey]);
+            if (! isset($keysByName[$constraintKey])) {
+                continue;
+            }
```
Comment (morozov) [inline src/Platforms/SQLitePlatform.php]: By assertion I mean `assert(isset($keysByName[$constraintKey]))`. This way, we are saying that we always expect it to be set, otherwise it should be an error.

Making it a `continue` sends the wrong message and adds code not covered by tests.

File: src/Platforms/SQLitePlatform.php [hunk 8]
```diff
@@ -917,7 +933,11 @@ private function getForeignKeysInAlteredTable(TableDiff $diff): array
                         ->getValue(),
                 );
 
-                $foreignKeys[$constraintKey] = $constraint;
+                if (! isset($keysByName[$constraintKey])) {
```
Comment (morozov) [inline src/Platforms/SQLitePlatform.php]: Similarly. this should be `assert(! isset($keysByName[$constraintKey]))`. This will allow to move `$foreignKeys[] = $constraint;` out of the `if` as suggested in https://github.com/doctrine/dbal/pull/7158#discussion_r2366262152.

File: src/Platforms/SQLitePlatform.php (hunk 7 above)
Comment (santysisi) [reply src/Platforms/SQLitePlatform.php]: Understand! Sorry about that, that was my fault.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @santysisi!
