### PR TITLE
Fix getServerVersion for OCI8 when assertions are disabled

### LINKED ISSUE #4994: OCI8 drivers notice on getServerVersion, "matches" is always undefined
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.1.3 (I upgraded from 2.13.5)

#### Summary

The driver fail on "Connection" class for Oracle database. I have a notice everywhere like this.

image

For sure, the matches array is always undefined when the instruction is in assert. I don't know why.
If you move the preg_match instruction outside, its work like a charm.

#### Current behaviour

All is in the previous capture.

#### How to reproduce

Juste using this kind of connection, and listen notice error. In symfony is the default.

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4994

### CODE REVIEW

**Review by morozov — APPROVED** [review]

File: src/Driver/OCI8/Connection.php [hunk 1]
```diff
@@ -78,7 +78,8 @@ public function getServerVersion()
             throw Error::new($this->dbh);
         }
 
-        assert(preg_match('/\s+(\d+\.\d+\.\d+\.\d+\.\d+)\s+/', $version, $matches) === 1);
+        $result = preg_match('/\s+(\d+\.\d+\.\d+\.\d+\.\d+)\s+/', $version, $matches);
+        assert($result === 1);
```
Comment (morozov) [inline src/Driver/OCI8/Connection.php:82]: For reference: https://github.com/vimeo/psalm/issues/4392.
