### PR TITLE
Catch MySQLi exceptions on PHP 8.1

### LINKED ISSUE #4870: PHP 8.1: MySQLi: Default error mode set to exceptions
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1

#### Summary

In PHP 8.1, MySQLi default error mode is set to exceptions. Prior to PHP 8.1, the default error reporting mode in MySQLi was to silent the errors.

If I understand correctly, now `mysqli_sql_exception` is not captured and standardized into DBAL exceptions, and rather bubble up in consuming code.

https://php.watch/versions/8.1/mysqli-error-mode

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4870

#### Summary

This is the MySQLi part of #4875, redone on the 3.1.x branch. The branches diverged in this area of the code so that I preferred to redo the changes to ease the merge-up.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

File: src/Driver/Mysqli/Connection.php [hunk 1]
```diff
@@ -52,7 +53,13 @@ public function __construct(
             $initializer->initialize($connection);
         }
```
Comment (greg0ire) [inline src/Driver/Mysqli/Connection.php:54]: Yesterday, I had to move this block inside the `try` block for this to work… weird that you do not have to.

Comment (derrabus) [reply src/Driver/Mysqli/Connection.php:54]: I've adjusted the `Charset` initializer to catch the exception.
