### PR TITLE
Fix JSON Dbal type to properly encode whole number float values, preserving zero fractions.

### LINKED ISSUE #5172: JSON float values encoded inproperly, trailing zeros removed
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.x and probably others

#### Summary

During saving float values to the database's JSON field the trailing zeros are removed which hurts data integrity and causes problems with strongly typed systems.

#### Current behaviour

Trailing zeros are removed from float values during encoding them to JSON

#### How to reproduce

Add a JSON type field to your chosen table. Save whole number float values to the table and then select the field from the table and observe the trailing zeros removed.

Example:
Save value float(10.0) to database via JSON type.
After retrieving the value from the database it becomes int(10).

The problem is in the encoding part of the code, because it misses the `JSON_PRESERVE_ZERO_FRACTION` flag.

#### Expected behaviour
Trailing zeros are kept.

### PR DESCRIPTION
**Pull request by Kova101**
|      Q       |   A
|------------- | -----------
| Type         | bugfix
| BC Break     | no
| Fixed issues | #5172

#### Summary

Fixes the zero fraction removal during JSON encoding. It is important for keeping the data integrity and really useful for strongly typed systems (value won't turn to integer during decode).

### CODE REVIEW

File: tests/Types/JsonTest.php [hunk 1]
```diff
@@ -62,7 +62,7 @@ public function testJsonEmptyStringConvertsToPHPValue(): void
     public function testJsonStringConvertsToPHPValue(): void
     {
         $value         = ['foo' => 'bar', 'bar' => 'foo'];
-        $databaseValue = json_encode($value, 0, JSON_THROW_ON_ERROR);
```
Comment (Ocramius) [inline tests/Types/JsonTest.php:65]: This should probably stay as it was, since `JSON_THROW_ON_ERROR` has an effect on how `vimeo/psalm` analyzes this code

File: tests/Types/JsonTest.php [hunk 2]
```diff
@@ -100,6 +100,27 @@ public function testRequiresSQLCommentHint(): void
...
+
+        self::assertEquals('{"foo":"bar","bar":"foo"}', $databaseValue);
+    }
+
+    public function testPHPFloatValueConvertsToJsonString(): void
+    {
+        $source        = ['foo' => 11.4, 'bar' => 10.0];
+        $databaseValue = $this->type->convertToDatabaseValue($source, $this->platform);
+
+        self::assertEquals('{"foo":11.4,"bar":10.0}', $databaseValue);
```
Comment (Ocramius) [inline tests/Types/JsonTest.php]: IMO `assertSame()`

File: tests/Types/JsonTest.php [hunk 3]
```diff
@@ -100,6 +100,27 @@ public function testRequiresSQLCommentHint(): void
...
+    {
+        self::assertNull($this->type->convertToDatabaseValue(null, $this->platform));
+    }
+
+    public function testPHPValueConvertsToJsonString(): void
+    {
+        $source = ['foo' => 'bar', 'bar' => 'foo'];
+        $databaseValue = $this->type->convertToDatabaseValue($source, $this->platform);
+
+        self::assertEquals('{"foo":"bar","bar":"foo"}', $databaseValue);
```
Comment (Ocramius) [inline tests/Types/JsonTest.php]: IMO `assertSame()`

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: tests/Types/JsonTest.php (hunk 1 above)
Comment (Kova101) [reply tests/Types/JsonTest.php:65]: Reverted back

File: tests/Types/JsonTest.php (hunk 2 above)
Comment (Kova101) [reply tests/Types/JsonTest.php]: Done

File: tests/Types/JsonTest.php (hunk 3 above)
Comment (Kova101) [reply tests/Types/JsonTest.php]: Done

**Review by Ocramius — DISMISSED** [review]

**Review by derrabus — APPROVED** [review]

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @Kova101.

**Comment by Ocramius** [comment]
@morozov is it worth cutting `3.2.2`?

**Comment by morozov** [comment]
So far, it looks like the only issue solved in the milestone. I don't mind it being released if you need it that bad. But can't you temporarily override the class with a fixed one?

**Comment by Ocramius** [comment]
Should be fine - it's just that I drop multiple releases a day, these days, so I'm used to closing a milestone as soon as it is complete.
