### PR TITLE
Fix auto_increment implementation for Oracle

### LINKED ISSUE #4725: OraclePlatform::getCreateAutoincrementSql forces sequence value in autoincrement column
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.0

#### Summary

The trigger that OraclePlatform::getCreateAutoincrementSql() adds to the database when an autoincrement column is defined does not take into account values passed in directly in the INSERT statements and always overwrites them with the next value of the sequence. 

#### Current behaviour

Look at the trigger code:

https://github.com/doctrine/dbal/blob/a602f2baf74df3d9b17ea8b29fca5fc33786d68d/src/Platforms/OraclePlatform.php#L532-L536

In the very first statement, `sequence.nextval` always forces the next value sequence to the autoincrement column, no matter if there's a value defined already. Other databases allow forcing a value to the autoincrement column, with this code Oracle behaves differently. Weirdly, the rest of the trigger code seems to deal with the case of a value higher that the sequence value to get it up to match an higher value inserted directly; but that can not run, actually, because the first statement has already forced the sequence.nextval to the column to be inserted.

I think just removing that first statement will do.

#### How to reproduce

Create a table with an autoincrement column, try to INSERT a record with a value = 1000 in that column, select back => the value inserted has a value == 1.

#### Expected behaviour

Create a table with an autoincrement column, try to INSERT a record with a value = 1000 in that column, select back => the value inserted has a value == 1000; next insert operation with no value defined will determine a record with value == 1001.

### PR DESCRIPTION
**Pull request by mondrake**
Fixes #4725.

Obviously, different behavior per platform is not something very attractive, but at least with this MR we make Oracle behave like MySql and SQLite, and add tests for all the platforms (except MS Sql that does not allow arbitrary values in INSERT for identity columns).

### CODE REVIEW

File: tests/Functional/AutoincrementColumnTest.php [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+        parent::setUp();
+
+        if (! self::$tableCreated) {
+            $table = new Table('auto_increment_table');
+            $table->addColumn('id', 'integer', ['autoincrement' => true]);
+            $table->addColumn('test_int', 'integer');
+            $table->setPrimaryKey(['id']);
+
+            $sm = $this->connection->getSchemaManager();
+            $sm->createTable($table);
```
Comment (morozov) [inline tests/Functional/AutoincrementColumnTest.php]: Please use `dropAndCreateTable()` and create the table unconditionally. This is effectively what truncation does.

File: tests/Functional/AutoincrementColumnTest.php [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+    private static $tableCreated = false;
+
+    protected function setUp(): void
+    {
+        parent::setUp();
+
+        if (! self::$tableCreated) {
+            $table = new Table('auto_increment_table');
+            $table->addColumn('id', 'integer', ['autoincrement' => true]);
+            $table->addColumn('test_int', 'integer');
```
Comment (morozov) [inline tests/Functional/AutoincrementColumnTest.php]: Why is this column needed? The `id` column should be sufficient to test how autoincrement works.

File: tests/Functional/AutoincrementColumnTest.php [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+    {
+        if ($this->connection->getDatabasePlatform()->getName() === 'mssql') {
+            self::markTestSkipped('Test does not work on MSSql.');
+        }
+
+        $this->connection->insert('auto_increment_table', ['test_int' => 1]);
+
+        $this->assertEquals([
+            ['id' => 1, 'test_int' => 1],
+        ], $this->lowerCaseResultColumnNames($this->connection->fetchAllAssociative(
```
Comment (morozov) [inline tests/Functional/AutoincrementColumnTest.php]: `lowerCaseResultColumnNames()` isn't necessary. If a single column is selected, you can use `fetchOne()`, and we don't need to select all columns.

File: tests/Functional/AutoincrementColumnTest.php [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+            'SELECT * FROM auto_increment_table ORDER BY id ASC'
+        )));
+
+        $this->connection->insert('auto_increment_table', ['id' => 1000, 'test_int' => 2]);
```
Comment (morozov) [inline tests/Functional/AutoincrementColumnTest.php]: Why is the rest of the test needed? The above assertion verifies that the resulting value is the same as specified manually (could use a different value than `1` though).

File: tests/Functional/AutoincrementColumnTest.php [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+        $this->assertEquals([
+            ['id' => 1, 'test_int' => 1],
+            ['id' => 1000, 'test_int' => 2],
+        ], $this->lowerCaseResultColumnNames($this->connection->fetchAllAssociative(
+            'SELECT * FROM auto_increment_table ORDER BY id ASC'
+        )));
+
+        $this->connection->insert('auto_increment_table', ['test_int' => 3]);
+
+        // DBMS autogenerated value after an arbitrary insert differs per platform.
```
Comment (morozov) [inline tests/Functional/AutoincrementColumnTest.php]: If that's the case, why do we want to get it tested? Let's keep the test scoped to the original issue.

File: tests/Functional/AutoincrementColumnTest.php (hunk 1 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: OK, thanks.

File: tests/Functional/AutoincrementColumnTest.php (hunk 2 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: SQLite fails on `insert('autoincrement_table', [])` which would be the way to go here if we were just having a single autoincrement column in the table. Will change anyway so we do not get confused.

File: tests/Functional/AutoincrementColumnTest.php (hunk 3 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: Changed to use `fetchFirstColumn()`.

File: tests/Functional/AutoincrementColumnTest.php (hunk 4 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: IMHO we also need to test what happens next time a record is inserted _after_ an arbitrary value is inserted. This tests in Oracle, for instance, that the rest of the trigger code that aligns the sequence value with the max value inserted runs OK.

File: tests/Functional/AutoincrementColumnTest.php (hunk 5 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: See above.

File: tests/Functional/AutoincrementColumnTest.php (hunk 2 above)
Comment (morozov) [reply tests/Functional/AutoincrementColumnTest.php]: Please try using `$platform->etEmptyIdentityInsertSQL()` instead:
https://github.com/doctrine/dbal/blob/891ec185b0a0740a0dfeede0a3eddd2f399bb009/src/Platforms/AbstractPlatform.php#L3421-L3424

File: tests/Functional/AutoincrementColumnTest.php (hunk 4 above)
Comment (morozov) [reply tests/Functional/AutoincrementColumnTest.php]: Why does it matter what happens if it's inconsistent across the platforms? The user cannot rely in this behavior anyways.

What does matter though is what happens if we create a new table, and then:
1. Insert an empty row (`1`)
2. Insert `2` manually. At this point, MySQL will bump `AUTO_INCREMENT` to `3` but Oracle will just skip the call to `seq.NEXTVAL`
3. Insert an empty row.

It doesn't matter what the resulting value is since it's inconsistent across platforms. It does matter whether it succeeds or fails.

File: tests/Functional/AutoincrementColumnTest.php (hunk 2 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: Done, thanks

File: tests/Functional/AutoincrementColumnTest.php (hunk 4 above)
Comment (mondrake) [reply tests/Functional/AutoincrementColumnTest.php]: That scenario rules off the test for DB2 and PostgreSql, because the manual insertion in 2 does not update their sequence so 3 fails because it will try to insert a value '2' in the ID again.

**Comment by morozov** [comment]
@mondrake do you mind if I update the test myself and push it to your branch? Otherwise, the review is taking too much time on my end.

**Comment by mondrake** [comment]
Not at all, you’re welcome

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @mondrake.
