### PR TITLE
Cast `BIGINT` values to int if possible

### LINKED ISSUE #6126: DBAL36 - BIGINT documentation misunderstanding
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.5

#### Summary

Please rephrase the explanation in the docs about the **BIGINT** datatype.

#### Current behaviour

The current statements lead to misinterpretation:

```markdown
<!-- dbal/docs/en/reference/types.rst:90 -->
Values retrieved from the database are always converted to PHP's ``string`` type
or ``null`` if no data is present.
```

```markdown
<!-- dbal/docs/en/reference/types.rst:95 -->
For compatibility reasons this type is not converted to an integer
```

Which is not true.

We have many entities mapped with **BIGINT** and **BIGSERIAL** in a PostgreSQL database
and doctrine always casts their value to a regular PHP integer. We use the 64 bit architecture
and the primary keys are mapped this way.

```php
<?php
class User {
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'SEQUENCE')]
    #[ORM\SequenceGenerator(
        sequenceName: 'user.user_id_user_seq',
        allocationSize: 1,
        initialValue: 1
    )]
    #[ORM\Column(name: 'id_user', type: Types::BIGINT)]
    private ?int $id = null;
}
```
According to the [PostgreSQL's documentation](https://www.postgresql.org/docs/11/datatype-numeric.html) the maximum number for a BIGINT field is **9223372036854775807** which is the same as the [PHP_INT_MAX](https://www.php.net/manual/en/reserved.constants.php).

#### How to reproduce

- Make an entity whose primary key represents a **BIGINT** type in the database.
- Run the respective migration
- Add a row to the table via a SQL script
- Fetch that entity using that entity's repository via Symfony Commands or Regular Controllers
- Debug the datatype via `dd()` or let it serialize it through a JsonResponse.

You'll notice that the value comes as a PHP integer.

You can also add another row to the table with the maximum possible value, see the value of PHP_INT_MAX and make an insertion to the database.
Fetch all the entities and you can see that the value still comes as a regular integer type.

Due to the limitations of JSON, things start to get really weird for numbers like this, so you can only trust the `dd()` output in this case.

#### Expected behaviour

The docs should say that the values retrieved from the database are always converted to PHP's ``int`` type or ``null`` if no data is present and display a notice about it being cast to string only in legacy 32-bit platforms.

Btw why have you guys changed your minds? #2976

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | Replaces #6143, closes #6126

#### Summary

`BigIntType` casts values retrieved from the database to int if they're inside the integer range of PHP. Previously, those values were always cast to string.

This PR continues the work done by @cizordj in #6143.

### CODE REVIEW

File: tests/Functional/Types/BigIntTypeTest.php [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+        yield 'positive number' => ['42', 42];
+        yield 'negative number' => ['-42', -42];
+
+        if (PHP_INT_SIZE < 8) {
+            // The following tests only work on 64bit systems.
+            return;
+        }
+
+        // PHP_INT_MAX - 1
+        yield 'large positive number' => ['9223372036854775806', 9223372036854775806];
```
Comment (morozov) [inline tests/Functional/Types/BigIntTypeTest.php]: Maybe instead of putting it as a comment, we could replace the integer values with the `PHP_INT_* ± 1` expressions? This way, the code will be self-explaining.

File: tests/Functional/Types/BigIntTypeTest.php [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+        $table = new Table('bigint_type_test');
+        $table->addColumn('id', Types::SMALLINT, ['notnull' => true]);
+        $table->addColumn('my_integer', Types::BIGINT, ['notnull' => false, 'unsigned' => true]);
+        $table->setPrimaryKey(['id']);
+        $this->dropAndCreateTable($table);
+
+        // Insert (2 ** 64) - 1
+        $this->connection->executeStatement(<<<'SQL'
+            INSERT INTO bigint_type_test (id, my_integer)
+            VALUES (42, 18446744073709551614)
```
Comment (morozov) [inline tests/Functional/Types/BigIntTypeTest.php]: This cannot be 2<sup>64</sup> - 1 since it's an even number. Similar to the above, let's code it as an expression instead of a magic literal.

File: tests/Functional/Types/BigIntTypeTest.php [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+            INSERT INTO bigint_type_test (id, my_integer)
+            VALUES (42, $value)
+            SQL);
+
+        self::assertThat(
+            $this->connection->convertToPHPValue(
+                $this->connection->fetchOne('SELECT my_integer from bigint_type_test WHERE id = 42'),
+                Types::BIGINT,
+            ),
+            LogicalXor::fromConstraints(new IsIdentical($value), new IsIdentical((string) $value)),
```
Comment (morozov) [inline tests/Functional/Types/BigIntTypeTest.php]: Do we really need an XOR here? Just an OR should suffice. The converted value cannot be identical to two different values by definition, so we don't really need to assert that.

File: src/Types/BigIntType.php [hunk 4]
```diff
@@ -7,8 +7,13 @@
...
 use Doctrine\DBAL\Platforms\AbstractPlatform;
 
+use function is_int;
+
+use const PHP_INT_MAX;
+use const PHP_INT_MIN;
+
 /**
- * Type that maps a database BIGINT to a PHP string.
+ * Type that maps a database BIGINT to a PHP int.
```
Comment (morozov) [inline src/Types/BigIntType.php]: It can be either `int` or `string`.

**Review by morozov — APPROVED** [review]

**Comment by cizordj** [comment]
Nice to see this feature implemented 😄.
Thanks you all

**Comment by ondrejmirtes** [comment]
I'm not a big fan of this change. This now means that bigint properties now need to be declared as `int|string` and it brings additional complexity to the code.

**Comment by derrabus** [comment]
> This now means that bigint properties now need to be declared as `int|string`

No, you can declare them as `int` in most cases. The `string` edge-case is rare enough that you can decide to ignore it in your project.

**Comment by ondrejmirtes** [comment]
Errr, what? Once we put a large enough integer value to the database, we need to declare `string` too. Of course from the point of static analysis, only code that declares `int|string` is safe.

**Comment by derrabus** [comment]
> Errr, what? Once we put a large enough integer value to the database, we need to declare `string` too.

Which is only possible if:

* Your PHP is on 32bit
* You use `BIGINT UNSIGNED` on MySQL

In both cases, you deliberately decided to deal with integers that are larger than what your PHP setup can handle, so the "added complexity" you're talking about is justified.

And if that `int|string` union is too much complexity for your taste, you can still declare your property as `string` and the ORM will cast the integer back to string. You basically opt-out of the new behavior that you don't like. Everybody wins. 🙂

**Comment by ondrejmirtes** [comment]
Alright, thank you, hopefully this can be accommodated for in phpstan-doctrine correctly :)

**Comment by cizordj** [comment]
@ondrejmirtes by default, **BigInts** are **signed 8-byte numbers** that work well with PHP's integer type. However, if you're hosting your project on a 32-bit system, the PHP integer range is smaller, and larger numbers need to be converted to strings to function properly. The same goes for unsigned integers, as their range exceeds what PHP can handle, leading to the need to cast them as strings due to memory limitations. If your database uses signed integers, sticking to the integer type in PHP is just fine.

**Comment by derrabus** [comment]
> Alright, thank you, hopefully this can be accommodated for in phpstan-doctrine correctly :)

:100: I have full confidence in the abilities of the authors of said package. 🚀

**Comment by ondrejmirtes** [comment]
Just one more question about this - if the mapped property contains a `string` it's still okay and Doctrine will write it correctly o the BIGINT column in the database, right?

**Comment by derrabus** [comment]
Sure. It should be the string representation of an integer, obviously.

**Comment by ondrejmirtes** [comment]
Thanks :) So `int|string` is a valid type declaration for property mapped as `bigint` :)

File: src/Types/BigIntType.php [hunk 5]
```diff
@@ -28,12 +37,25 @@ public function getBindingType(): ParameterType
...
      */
-    public function convertToPHPValue(mixed $value, AbstractPlatform $platform): ?string
+    public function convertToPHPValue(mixed $value, AbstractPlatform $platform): int|string|null
     {
-        return $value === null ? null : (string) $value;
+        if ($value === null || is_int($value)) {
+            return $value;
+        }
+
+        if ($value > PHP_INT_MIN && $value < PHP_INT_MAX) {
```
Comment (mvorisek) [inline src/Types/BigIntType.php:50]: Shouldn't this be `>= && <=`?

Comment (derrabus) [reply src/Types/BigIntType.php:50]: no

Comment (mvorisek) [reply src/Types/BigIntType.php:50]: see https://3v4l.org/I9jI9 repro - may I know why the valid int extremes should not be casted?

Comment (derrabus) [reply src/Types/BigIntType.php:50]: Because I cannot detect them safely.

Comment (mvorisek) [reply src/Types/BigIntType.php:50]: will `$v === (string) (int) $v` work?

Comment (mvorisek) [reply src/Types/BigIntType.php:50]: @derrabus I really feel this is not matching the expected behaviour and documentation.

Comment (derrabus) [reply src/Types/BigIntType.php:50]: Find a better implementation that works well on a hot path and send a PR. Theorizing in the comments of a merged PR is wasting everybody's time and energy.

Comment (mvorisek) [reply src/Types/BigIntType.php:50]: It is your PR and I am just reporting an issue to you privately. The docs is clear the whole representible range is supported.
