### PR TITLE
Use exception in OCI8 driver, instead of relying on assert

### LINKED ISSUE #6595: OCI8 driver does not check result from oci_parse, relies on disabled assert in production
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 4.2.1

#### Summary

The Oracle (OCI8) driver uses assert to verify the result from oci_parse. 

By default (since PHP7), assert is disabled in production environments, which means the validation is never executed in prod. Unlike other drivers that handle this check by throwing exceptions, the OCI8 driver relies on assert, resulting in warnings in the log, and no way of catching the lost connection

```php
        $statement = oci_parse($this->connection, $visitor->getSQL());
        assert(is_resource($statement));

        return new Statement($this->connection, $statement, $visitor->getParameterMap(), $this->executionMode);
```
#### Current behavior

In production, if oci_parse fails (e.g., due to a connection issue), the assert statement is bypassed, leading to PHP warnings rather than controlled exceptions. This results in the following warning:
```
PHP Warning: oci_parse(): ORA-03114: not connected to ORACLE in /srv/app/vendor/doctrine/dbal/src/Driver/OCI8/Connection.php on line 57
```

#### Expected behavior

The Oracle driver should handle oci_parse failures consistently with other drivers by checking the result and throwing an appropriate exception if oci_parse fails. This would ensure reliable error handling across all environments

#### How to reproduce

1. Disable assertions in your production-like environment
2. Use the OCI8 driver to connect to an Oracle database
3. Trigger a connection issue (e.g., disconnect or shutdown the Oracle server)
4. Observe that instead of an exception, a PHP warning is issued, and the error is not handled as expected

### PR DESCRIPTION
**Pull request by segrax**
Fixes a bug where disabled asserts in production left oci_parse() errors unchecked. Now uses explicit checks and exceptions

Fixes #6595

|      Q       |   A
|------------- | -----------
| Type         | bug
| Fixed issues | #6595 

#### Summary

Fixes a bug where disabled asserts in production left oci_parse()
errors unchecked. Now uses explicit checks and exceptions

### CODE REVIEW

File: src/Driver/OCI8/Connection.php [hunk 1]
```diff
@@ -47,22 +47,30 @@ public function getServerVersion(): string
...
+     */
     public function prepare(string $sql): Statement
     {
         $visitor = new ConvertPositionalToNamedPlaceholders();
 
         $this->parser->parse($sql, $visitor);
 
-        $statement = oci_parse($this->connection, $visitor->getSQL());
+        $statement = @oci_parse($this->connection, $visitor->getSQL());
         assert(is_resource($statement));
```
Comment (derrabus) [inline src/Driver/OCI8/Connection.php]: Shouldn't we remove this line now?

**Review by derrabus — DISMISSED** [review]
Thank you. Can we cover this change with a test?

File: src/Driver/OCI8/Connection.php (hunk 1 above)
Comment (segrax) [reply src/Driver/OCI8/Connection.php]: wasn't sure if the assert should be removed, so I kept it consistent with the PostgreSQL driver by adding the error check alongside it. But can remove it if there is no reason for it to be here anymore?

Comment (derrabus) [reply src/Driver/OCI8/Connection.php]: > if there is no reason for it to be here anymore

I don't see any. 🤷‍♂️ Let's remove it.

Comment (segrax) [reply src/Driver/OCI8/Connection.php]: Turned out it had to go anyway, assert is enabled when tests run 😄

**Comment by segrax** [comment]
> Thank you. Can we cover this change with a test?

yeah, test has just been added

**Comment by segrax** [comment]
@derrabus should be all good, the last failing test seems to be unrelated (and has happened a couple of times now)

```
Failures
 - sqlite (exited 1) - sqlite not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable: Back-end server is at capacity
Sorry, we tried running command for 3 times and all attempts were unsuccessful!

Get-ChildItem : Cannot find path 'C:\tools\php' because it does not exist.
At line:6 char:3
+   Get-ChildItem -Path c:\tools\php
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\tools\php:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
cd : Cannot find path 'C:\tools\php' because it does not exist
```

**Comment by morozov** [comment]
The AppVeyor build failure is tracked in https://github.com/doctrine/dbal/pull/6601.

File: tests/Driver/OCI8/ConnectionTest.php [hunk 2]
```diff
@@ -0,0 +1,98 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Doctrine\DBAL\Tests\Driver\OCI8;
```
Comment (morozov) [inline tests/Driver/OCI8/ConnectionTest.php]: Please move under `Tests\Functional`.

File: tests/Driver/OCI8/ConnectionTest.php [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+                return;
+            }
+
+            $params   = TestUtil::getConnectionParams();
+            $username = $params['user'] ?? '';
+            $password = $params['password'] ?? '';
+            $host     = $params['host'] ?? '';
+
+            $secondConnection = oci_connect($username, $password, $host);
+            if ($secondConnection === false) {
```
Comment (morozov) [inline tests/Driver/OCI8/ConnectionTest.php]: Please use DBAL, if possible. I feel like the amount of boilerplate code will reduce.

File: tests/Driver/OCI8/ConnectionTest.php [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+                throw new RuntimeException('Unable to establish secondary connection for session termination.');
+            }
+
+            $killStmt = oci_parse(
+                $secondConnection,
+                'ALTER SYSTEM DISCONNECT SESSION \'' . $session['SID'] . ',' . $session['SERIAL#'] . '\' IMMEDIATE',
```
Comment (morozov) [inline tests/Driver/OCI8/ConnectionTest.php]: Please bind parameters to the statement instead of concatenation. Even though it may be safe in this case, it sets a bad example.

File: tests/Driver/OCI8/ConnectionTest.php (hunk 3 above)
Comment (segrax) [reply tests/Driver/OCI8/ConnectionTest.php]: Done

File: tests/Driver/OCI8/ConnectionTest.php (hunk 2 above)
Comment (segrax) [reply tests/Driver/OCI8/ConnectionTest.php]: Done

File: tests/Driver/OCI8/ConnectionTest.php (hunk 4 above)
Comment (segrax) [reply tests/Driver/OCI8/ConnectionTest.php]: Done, 

had to use a PL/SQL block, as Oracle doesn't allow binding in ALTER commands

**Comment by segrax** [comment]
hey @derrabus and @morozov, 
Is there anything else needed here?

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+namespace Doctrine\DBAL\Tests\Functional\Driver\OCI8;
+
+use Doctrine\DBAL\DriverManager;
+use Doctrine\DBAL\Exception\DriverException;
+use Doctrine\DBAL\Tests\FunctionalTestCase;
+use Doctrine\DBAL\Tests\TestUtil;
+use PHPUnit\Framework\Attributes\RequiresPhpExtension;
+use Throwable;
+
+#[RequiresPhpExtension('oci8')]
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: We probably want to test it with `pdo_oci` as well. Instead of requiring a PHP extension, please use `TestUtils::isDriverOneOf()`. Otherwise, if the extension is available at runtime, this test will run with any other drivers and fail.

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+        $params['charset'] = 'utf8mb4';
+        $secondConnection  = DriverManager::getConnection($params);
+
+        try {
+            $stmt = $secondConnection->prepare(self::DISCONNECT_SESSION_SQL);
+            $stmt->bindValue(':sid', $session['SID']);
+            $stmt->bindValue(':serial', $session['SERIAL#']);
+            $stmt->executeQuery();
+        } catch (Throwable $e) {
+            self::fail($e->getMessage());
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: This try-catch block can be removed. If the query fails, it will automatically fail the test.

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+#[RequiresPhpExtension('oci8')]
+class ConnectionTest extends FunctionalTestCase
+{
+    private const DISCONNECT_SESSION_SQL = <<<'SQL'
+        DECLARE
+            v_sid    VARCHAR2(10) := :sid;
+            v_serial VARCHAR2(10) := :serial;
+            v_sql    VARCHAR2(200);
+        BEGIN
+            v_sql := 'ALTER SYSTEM DISCONNECT SESSION ''' || v_sid || ',' || v_serial || ''' IMMEDIATE';
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: This isn't really better than the original version in terms of security. If binding parameters is impossible, please quote the strings using `Connection::quote()` before using them in the statement.

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 5 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Done

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 7 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Done, 

This is actually a single string parameter, so it has to be quoted in the form 'SID, SERIAL#'

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    /**
+     * Kill the current session, by using another connection
+     * Oracle doesn't allow you to terminate the current session, so we use a second connection
+     */
+    private function killCurrentSession(): void
+    {
+        $session = $this->getCurrentSession();
+        if ($session === false || ! isset($session['SID'], $session['SERIAL#'])) {
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: Is it possible that this query doesn't return a row? What will happen in this case?

I would just inline `getCurrentSession()` like this:
```php
$row = $this->connection->fetchNumeric(<<<'SQL'
SELECT SID, SERIAL#
FROM V\$SESSION
WHERE AUDSID = USERENV('SESSIONID')
SQL
);

self::assertNotFalse($row);
[$sid, $serialNumber] = $row;
```

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+            return;
+        }
+
+        $params            = TestUtil::getConnectionParams();
+        $params['charset'] = 'utf8';
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: Why is charset needed for the second connection?

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+        $secondConnection  = DriverManager::getConnection($params);
+
+        $sessionParam = $this->connection->quote($session['SID'] . ', ' . $session['SERIAL#']);
+        $stmt         = $secondConnection->prepare('ALTER SYSTEM DISCONNECT SESSION ' . $sessionParam . ' IMMEDIATE');
+        $stmt->executeQuery();
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: You can directly call `$secondConnection->executeStatement()`, there's no need to prepare it explicitly if it's not going to be reused.

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+
+    public function testPrepareThrowsErrorOnConnectionLost(): void
+    {
+        $this->markConnectionNotReusable();
+        $this->killCurrentSession();
+
+        $this->expectException(DriverException::class);
+
+        $stmt = $this->connection->prepare('SELECT * FROM 1');
+        $stmt->executeQuery();
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: You can use `$this->connection->executeQuery()` instead.

File: src/Driver/OCI8/Connection.php [hunk 12]
```diff
@@ -47,22 +47,29 @@ public function getServerVersion(): string
...
+            throw Error::new($this->connection);
+        }
 
         return new Statement($this->connection, $statement, $visitor->getParameterMap(), $this->executionMode);
     }
 
     /**
      * @throws Exception
      * @throws Parser\Exception
+     * @throws Error
```
Comment (morozov) [inline src/Driver/OCI8/Connection.php]: `Error` is a subtype of `Exception`, so it's already declared.

**Review by morozov — COMMENTED** [review]
Logic wise, looks good. Just nits.

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 9 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Without it, DriverManager::getConnection is returning the same connection

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 11 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Done

File: src/Driver/OCI8/Connection.php (hunk 12 above)
Comment (segrax) [reply src/Driver/OCI8/Connection.php]: Done

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 8 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: No, at least not under normal operation... the checks where just to keep phpstan happy,

Changed

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 9 above)
Comment (morozov) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: This is the default behavior of Oracle instant client. Please try setting 'exclusive' driver option instead.

https://github.com/doctrine/dbal/blob/83469cbfd4a59a993f54e4bafc3c28c4e453a695/tests/Functional/LockMode/NoneTest.php#L45

Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Done

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 13]
```diff
@@ -0,0 +1,65 @@
...
+    private function killCurrentSession(): void
+    {
+        $row = $this->connection->fetchNumeric(<<<'SQL'
+        SELECT SID, SERIAL#
+        FROM V$SESSION
+        WHERE AUDSID = USERENV('SESSIONID')
+SQL);
+
+        self::assertNotFalse($row);
+        [$sid, $serialNumber] = [$row[0] ?? null, $row[1] ?? null];
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: Why isn't `[$sid, $serialNumber] = $row` sufficient here? If the row is not `false`, then it will be an array of exactly two elements.

In general, we don't want any flow control operations in the tests (like `if`, `??`, etc.). We want to test a very specific scenario, so we make assertions to prove (to ourselves and the static analysis tools) that we're testing what we want to.

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 14]
```diff
@@ -0,0 +1,65 @@
...
+     * Kill the current session, by using another connection
+     * Oracle doesn't allow you to terminate the current session, so we use a second connection
+     */
+    private function killCurrentSession(): void
+    {
+        $row = $this->connection->fetchNumeric(<<<'SQL'
+        SELECT SID, SERIAL#
+        FROM V$SESSION
+        WHERE AUDSID = USERENV('SESSIONID')
+SQL);
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php]: This should be indented as well. Otherwise, all lines above will have be indented, which is likely not what we want.

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 13 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Psalm flags that as an issue, and as there is only 8 suppress comments across the codebase, I went with that.

`
ERROR: PossiblyUndefinedArrayOffset - tests/Functional/Driver/OCI8/ConnectionTest.php:47:10 - Possibly undefined array key (see https://psalm.dev/167)
        [$sid, $serialNumber] = $row;
`

suppress added

File: tests/Functional/Driver/OCI8/ConnectionTest.php (hunk 14 above)
Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php]: Wasn't entirely sure what you meant here, so I've just changed it to match the style in getCreateTableSQL (src/Schema/SQLiteSchemaManager.php)

**Comment by segrax** [comment]
@morozov its not clear why the last test failed, seems something in the setup of php extensions failed, but theres no log of it

```
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.3.13

==> Setup Extensions
Error: The process '/usr/bin/bash' failed with exit code 1
```

**Comment by morozov** [comment]
@greg0ire here's another anomaly where the the modified code is reported as not covered. If you have a minute, could you analyze the coverage reports? I will run the test locally before merging.

**Comment by morozov** [comment]
@segrax it's an intermittent setup failure which sometimes happen in our CI environment. I've restarted the build. Once we figure out what's wrong with test coverage, we will merge the PR. Thank you.

**Comment by greg0ire** [comment]
I'm on my phone but from what I can see, only the appveyor files were processed. I'll reopen the codecov issue

File: tests/Functional/Driver/OCI8/ConnectionTest.php [hunk 15]
```diff
@@ -0,0 +1,68 @@
...
+        $params                               = TestUtil::getConnectionParams();
+        $params['driverOptions']['exclusive'] = true;
+        $secondConnection                     = DriverManager::getConnection($params);
+
+        $sessionParam = $this->connection->quote($sid . ', ' . $serialNumber);
+        $secondConnection->executeStatement('ALTER SYSTEM DISCONNECT SESSION ' . $sessionParam . ' IMMEDIATE');
+
+        // Ensure OCI driver is aware of connection state change by executing any statement
+        try {
+            $this->connection->executeStatement('INVALID SQL');
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/ConnectionTest.php:64]: It doesn't look like this statement is necessary. If I remove it, the test still passes. Could you try removing it or explain why it's necessary?

Comment (segrax) [reply tests/Functional/Driver/OCI8/ConnectionTest.php:64]: Without it, this error isn't throwing. The same error is being thrown elsewhere and caught by the test.

```php
        if (! is_resource($statement)) {
            throw Error::new($this->connection);
        }
```

This is happening because a few days ago, we changed
```php
$stmt = $this->connection->prepare('SELECT * FROM 1');
```

to
```php
$this->connection->executeQuery('SELECT * FROM 1');
```

Which shouldn't of been changed

This has however exposed that we cant test against PDO_OCI, as PDO_OCI doesnt use `Doctrine\DBAL\Driver\OCI8\Connection`.

I've reverted the line to just using prepare, and made it skip PDO_OCI

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @segrax.
