### PR TITLE
Fixed parsing MySQL create table flags (options without a value)

### LINKED ISSUE #3384: MySqlSchemaManager.php:319 Undefined index 1 when using MySQL Cluster (NDBCLUSTER engine)
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

After upgrading to DBAL 2.9.0 I got the following error when running doctrine:schema:update

In MySqlSchemaManager.php line 319:

  [ErrorException]
  Notice: Undefined offset: 1

Because $createOptionString DOES NOT NECESSARILY contains an = sign when using MySQL Cluster.
The culprit is with the option that contains just the string "partitioned" (no equal sign)

#### Previous behaviour

Doctrine schema update feature was working properly in 2.8

#### Current behavior

In MySqlSchemaManager.php line 319:

  [ErrorException]
  Notice: Undefined offset: 1

Exception trace:
 () at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:319
 Doctrine\DBAL\Schema\MySqlSchemaManager->listTableDetails() at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:251
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1053
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:896
 Doctrine\ORM\Tools\SchemaTool->getUpdateSchemaSql() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:98
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand() at /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:70
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at /var/www/vendor/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:35
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at /var/www/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:919
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/bin/console:45

#### How to reproduce

Try to do a doctrine:schema:update with a MySQL Cluster backend using partitioned tables.

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #3384.

### CODE REVIEW

File: tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php [hunk 1]
```diff
@@ -511,7 +512,10 @@ public function testEnsureTableOptionsAreReflectedInMetadata() : void
         self::assertEquals('utf8_general_ci', $onlineTable->getOption('collation'));
         self::assertEquals(42, $onlineTable->getOption('autoincrement'));
         self::assertEquals('This is a test', $onlineTable->getOption('comment'));
-        self::assertEquals(['row_format' => 'COMPRESSED'], $onlineTable->getOption('create_options'));
+        self::assertEquals([
+            'row_format' => 'COMPRESSED',
+            'partitioned' => true,
```
Comment (Ocramius) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php]: Would it make sense to split this into a further test?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php (hunk 1 above)
Comment (morozov) [reply tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php]: So that two different tests, if failed, would show which kind of options we're failing to parse? I don't know. Parsing a mix of different options at a time is also a valid case. I'd leave it as is.

**Review by Ocramius — APPROVED** [review]
