### PR TITLE
Ignore columnDefinition in schema comparison

### LINKED ISSUE #5223: Schema diff changes since version 3.3.1
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes?
| Version     | 3.3.1

#### Summary

SInce 3.3.1 I have schema changes that I did not have before.

#### Current behaviour

```
app/console doctrine:schema:validate

Database
--------

                                                                                                                        
 [ERROR] The database schema is not in sync with the current mapping file.                                              
``` 

Running `app/console doctrine:schema:update --dump-sql` mostly shows changes related to `ENUM` column definitions like

```
ALTER TABLE my_entity CHANGE foo foo ENUM('foo', 'bar') NOT NULL;
``` 

However: the generated SQL is identical with the actual column definition in MySQL. So I cannot get rid of the diff.

Might be related to https://github.com/doctrine/dbal/pull/5220 ?

#### How to reproduce

Add an ORM entity with a `ENUM` columnDefinition like

```php
class MyEntity
{
     /**
     * @ORM\Column(
     *     name="foo",
     *     type="string",
     *     length=0,
     *     columnDefinition="ENUM('foo', 'bar') NOT NULL"
     * )
     */
    private $foo;
}
``` 

And map `enum` to string like

```
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                charset:  UTF8
                mapping_types:
                    enum: string
``` 

See https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/cookbook/mysql-enums.html#solution-1-mapping-to-varchars

#### Expected behaviour

There should not be any schema diff.

### PR DESCRIPTION
**Pull request by bcremer**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     |  no
| Fixes          |  #5223
#### Summary

Support schema validation when using `columnDefinition`.

Closes #5234

### CODE REVIEW

File: src/Schema/MySQLSchemaManager.php [hunk 1]
```diff
@@ -385,4 +387,35 @@ private function parseCreateOptions(?string $string): array
 
         return $options;
     }
+
+    private function buildColumnDefinition(array $tableColumn): string
```
Comment (bcremer) [inline src/Schema/MySQLSchemaManager.php]: Not happy about that.

There is no native mysql syntax to show the create statement for a single column.

File: src/Platforms/AbstractPlatform.php [hunk 2]
```diff
@@ -4017,6 +4017,10 @@ protected function getLikeWildcardCharacters(): string
      */
     public function columnsEqual(Column $column1, Column $column2): bool
     {
+        if ($column1->getColumnDefinition() !== null && $column2->getColumnDefinition() !== null) {
+            return $column1->getColumnDefinition() === $column2->getColumnDefinition();
```
Comment (bcremer) [inline src/Platforms/AbstractPlatform.php]: In case of the schema validation `$column1` would be populated by `\Doctrine\DBAL\Schema\AbstractSchemaManager::listTableColumns` and `$column`2 from the entity metadata.

File: src/Schema/MySQLSchemaManager.php [hunk 3]
```diff
@@ -385,4 +387,35 @@ private function parseCreateOptions(?string $string): array
...
+        if (isset($tableColumn['collation'])) {
+            $parts[] = 'COLLATE ' . $tableColumn['collation'];
+        }
+
+        if ($tableColumn['null'] !== 'YES') {
+            $parts[] = 'NOT NULL';
+        }
+
+        if (isset($tableColumn['default'])) {
+            $parts[] = sprintf("DEFAULT '%s'", $tableColumn['default']);
```
Comment (bcremer) [inline src/Schema/MySQLSchemaManager.php]: Might need a `$this->_platform->quoteIdentifier()` here.

File: src/Schema/MySQLSchemaManager.php [hunk 4]
```diff
@@ -385,4 +387,35 @@ private function parseCreateOptions(?string $string): array
...
+        }
+
+        if (isset($tableColumn['comment']) && $tableColumn['comment'] !== '') {
+            $parts[] = sprintf("COMMENT '%s'", $tableColumn['comment']);
```
Comment (bcremer) [inline src/Schema/MySQLSchemaManager.php]: Might need a `$this->_platform->quoteIdentifier()` here.

**Comment by Ocramius** [comment]
@bcremer could you cherry-pick my test from #5234 into this? Would like to see if this is a possible solution :)

**Comment by Ocramius** [comment]
Locally, I verified that the test @ e760ef885e9dae1e3bdb471e84d2b4f17cb4dd23 (from #5234) works with this patch on SQLite

**Comment by greg0ire** [comment]
Is this still WIP?

**Comment by morozov** [comment]
Without digging too much into the details, the approach here looks more straightforward and correct than the one in https://github.com/doctrine/dbal/pull/5234. So I assume if the test from there passes with this fix, this is what we need.

**Review by greg0ire — APPROVED** [review]

**Review by dmaicher — APPROVED** [review]
This works for me and schema diff because of custom `columnDefinition` are gone :+1:

**Comment by greg0ire** [comment]
Blocked by https://github.com/doctrine/dbal/pull/5239

**Review by morozov — APPROVED** [review]
