### PR TITLE
Platform-aware schema comparison 

### LINKED ISSUE #2331: Can't convert JSON to LONGTEXT (or MEDIUMTEXT)
Using Laravel migrations and the change() method, one can convert a JSON datatype to a string, and in a subsequent migration to a LONGTEXT or MEDIUMTEXT, but one cannot change JSON to a LONGTEXT or MEDIUMTEXT directly.

### LINKED ISSUE #2411: Comparator miss-detects custom columns as changed
While working a little with custom types in Doctrine lately, I recently noticed a bug in the `Comparator`, although its roots are deeper down. Consider having a custom type like this:

```php
class CustomType extends Type
{
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return $platform->getBinaryTypeDeclarationSQL([
            'length' => '16',
            'fixed' => true,
        ]);
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        // …
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        // …
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true;
    }

    public function getName()
    {
        return 'CustomType';
    }
}
```

Now, when using that type in an entity, at first when generating the database SQL and inserting it, everything is fine. The column has the correct type (binary, fixed 16) and a comment denoting the "CustomType" type.

The problem now is when asking the schema-tool for a diff. Even though the column using that type wasn't changed, the schema-tool suggests an ALTER TABLE statement, changing the column to exactly what it already is.

I looked a bit into this, and it seems that the problem is that the `Schema` generated from the mapping files does not include the columns comment, length, fixed status and also that the type in the `Schema` coming from the DB has `Binary` as type, instead of `CustomType`. This lets the `Comparator` think it needs to update the column.

This problem looks rather complex to me, and I have no real idea on how to solve this, maybe someone else who has a better insight can analyse this further.

### LINKED ISSUE #2566: Column altering in migration from TEXT to LONGTEXT may not apply.
Based on this
https://github.com/laravel/framework/issues/12363
and my experience here
https://laracasts.com/discuss/channels/laravel/alter-table-change-field-to-longtext

I think there is a problem when migrating a table column from TEXT to LONG TEXT

### LINKED ISSUE #2663: Comparator fails for BLOBS
In the TYPO3 project we use the diffColumn method in the class Doctrine\DBAL\Schema. Unfortunately this method fails to detect changes in BLOB columns. So changing a column from BLOB to another BLOB type fails.

### PR DESCRIPTION
**Pull request by morozov**
## State
The existing property-based column definition comparison has quite some flaws (see all the associated issues):
1. Certain properties, even if different, may yield the same column definition (e.g. the length of a blob column within the type limits).
2. The above is platform-specific, so if a certain type's property is ignored on one platform, it can cause a false-positive match on another platform.

## Proposal
The idea is to replace property-based comparison with the comparison of the SQL that the given column definition generates on the target platform. This way, the diff will be only generated if the column SQL representations on a given platform are different.

### API changes

This is quite an invasive change but it's meant to be safe for a minor release. The changes in the test logic identify the existing bugs rather than breaking changes. 

1. The `Comparator` class now takes an optional `AbstractPlatform` argument. If it's passed, column comparison will be performed in the context of the platform. Not passing a platform is now deprecated.
2. `AbstractPlatform::columnsEqual()` and `Comparator::columnsEqual()` have been added to compare column definitions in the context of the given platform. Depending on the platform, the comparison logic may be more complex than comparing the immediate column SQL. E.g. the default value on SQL Server is represented as a separate constraint.
3. `AbstractSchemaManager::createComparator()` has been added to create the comparator. Besides the schemas being compared and the target platform, the comparison logic may depend on the data available only at runtime (current database collation on SQL Server).
4. Constructors of the `Comparator` class and the subclasses are marked as internal to their schema managers. This will allow potentially improving the comparison logic without introducing breaking changes. The same is already implemented in driver-level connections and statements.

Platform-specific comparators clone the tables, if necessary, and normalize them before passing them to the base implementation. This implementation is far from perfect but it allows to avoid the introduction of a which may be not extensible enough and require a breaking change in the future.

### Testing

Most of the changes in the tests are temporary and are needed to guarantee the parity between the old and the new implementation. The data providers will be removed in the next major release when the dependency of `Comparator` on `AbstractPlatform` becomes mandatory.

1. All functional tests have been reworked to cover the default comparator and the one returned by `$schemaManager->createSchemaManager()`.
2. The unit tests that cover schema comparison in the context of a platform have been reworked to cover the default comparator and the one for the given platform (if it's different from the default).
3. The unit tests covering the `Comparator` outside of the context of a platform have been extended to cover all sub-classes.

## Future scope
1. Array representation of column definitions. Burn with fire. Some of the existing APIs expect `Column $column`, others expect `array<string,mixed> $column`. The latter is an archaism, relies on some magic defaults (see `AbstractPlatfrom::columnToArray()`) and requires unnecessary type conversion back and forth.
2. Deprecate and get rid of `Comparator::diffColumn()` and `ColumnDiff::$changedProperties`. In light of the above changes, the meaning and the purpose of the changed properties become ambiguous. If a property has changed but it doesn't result in a diff in the context of the current platform, should it be included in the changed properties?
3. Mark `SQLServer2012Platform::getDefaultConstraintDeclarationSQL()` and other similar methods internal and then protected. See #4503 for reference.
4. Use parametrized classes instead of the temporarily added assertions.

### CODE REVIEW

File: tests/Platforms/AbstractMySQLPlatformTestCase.php [hunk 1]
```diff
@@ -769,10 +795,8 @@ public function testDoesNotPropagateDefaultValuesForUnsupportedColumnTypes(): vo
         $diffTable->changeColumn('def_blob', ['default' => null]);
         $diffTable->changeColumn('def_blob_null', ['default' => null]);
 
-        $diff = (new Comparator())->diffTable($table, $diffTable);
-        self::assertNotFalse($diff);
-
-        self::assertEmpty($this->platform->getAlterTableSQL($diff));
```
Comment (morozov) [inline tests/Platforms/AbstractMySQLPlatformTestCase.php:775]: These two assertions cover the bug in the current implementation rather than the expected behavior. The original test and assertions read as follows:
1. Make some schema changes that don't change the resulting SQL.
2. Assert that the diff is not empty. This is the bug being fixed.
3. Assert that even though the diff is not empty, the resulting diff SQL is. This is a workaround of the bug.

File: tests/Platforms/OraclePlatformTest.php [hunk 2]
```diff
@@ -575,13 +575,7 @@ public function testDoesNotPropagateUnnecessaryTableAlterationOnBinaryType(): vo
...
         $table2->addColumn('column_binary', 'binary');
 
-        $comparator = new Comparator();
-
-        // VARBINARY -> BINARY
-        // BINARY    -> VARBINARY
-        $diff = (new Comparator())->diffTable($table1, $table2);
-        self::assertNotFalse($diff);
-        self::assertEmpty($this->platform->getAlterTableSQL($diff));
+        self::assertFalse((new Comparator($this->platform))->diffTable($table1, $table2));
```
Comment (morozov) [inline tests/Platforms/OraclePlatformTest.php:578]: Same as above, the existing logic covers a bug, not the expected behavior.

File: src/Driver/AbstractMySQLDriver.php [hunk 3]
```diff
@@ -126,6 +127,8 @@ public function getDatabasePlatform()
      */
     public function getSchemaManager(Connection $conn, AbstractPlatform $platform)
     {
+        assert($platform instanceof MySQLPlatform);
```
Comment (derrabus) [inline src/Driver/AbstractMySQLDriver.php:130]: Would it make sense to add the platform class as a `@template` to the `Driver` interface instead, like you did for `AbstractSchemaManager`?

File: src/Schema/Comparator.php [hunk 4]
```diff
@@ -30,9 +53,12 @@ class Comparator
...
      */
-    public static function compareSchemas(Schema $fromSchema, Schema $toSchema)
-    {
-        $comparator       = new self();
+    public static function compareSchemas(
+        Schema $fromSchema,
+        Schema $toSchema,
+        ?AbstractPlatform $platform = null
+    ) {
+        $comparator       = new self($platform);
```
Comment (derrabus) [inline src/Schema/Comparator.php]: Does this still work, now that we have `Comparator` implementations for the individual drivers? This constructor call will yield a generic `Comparator` and not the implementation specific to the passed platform.

File: tests/Functional/Schema/MySQL/ComparatorTest.php [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+use Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils;
+use Doctrine\DBAL\Tests\FunctionalTestCase;
+use Doctrine\DBAL\Types\Types;
+
+final class ComparatorTest extends FunctionalTestCase
+{
+    /** @var AbstractPlatform */
+    private $platform;
+
+    /** @var AbstractSchemaManager */
```
Comment (derrabus) [inline tests/Functional/Schema/MySQL/ComparatorTest.php:21]:
```suggestion
    /** @var AbstractSchemaManager<MySQLPlatform> */
```

File: tests/Schema/ComparatorTest.php [hunk 6]
```diff
@@ -14,13 +14,22 @@
...
 use function get_class;
 
 class ComparatorTest extends TestCase
 {
+    /** @var Comparator */
+    protected $comparator;
+
+    protected function setUp(): void
+    {
+        $this->comparator = new Comparator();
```
Comment (derrabus) [inline tests/Schema/ComparatorTest.php:30]: You have deprecated not passing a platform to the constructor.

File: tests/Schema/ComparatorTest.php [hunk 7]
```diff
@@ -42,7 +51,7 @@ public function testCompareSame1(): void
 
         $expected             = new SchemaDiff();
         $expected->fromSchema = $schema1;
-        self::assertEquals($expected, Comparator::compareSchemas($schema1, $schema2));
+        self::assertEquals($expected, $this->comparator->compareSchemas($schema1, $schema2));
```
Comment (derrabus) [inline tests/Schema/ComparatorTest.php:54]: Why this change? The method is still static, isn't it?

File: src/Driver/AbstractMySQLDriver.php (hunk 3 above)
Comment (morozov) [reply src/Driver/AbstractMySQLDriver.php:130]: It would. I tried that before wrapping up the patch but it looks like it's a rabbit hole (this is the current state: https://github.com/morozov/dbal/commit/8990107aae96b91d8a5b5362aa936c5347db245c).

A certain complexity arises when we parameterize the types like `Connection`, `Driver`, etc. that are used in connection parameters.

We can tackle this issue separately.

File: src/Schema/Comparator.php (hunk 4 above)
Comment (morozov) [reply src/Schema/Comparator.php]: Good point. The generic comparator supplied with a platform can cause false-positive diffs. It shouldn't be used this way. I'll also adjust the deprecation message in the comparator constructor accordingly.

File: tests/Schema/ComparatorTest.php (hunk 7 above)
Comment (morozov) [reply tests/Schema/ComparatorTest.php:54]: It is but now the comparator class is extended by platform-specific classes and I want to reuse the same test case to test all implementations. See the classes extending this one.

File: tests/Schema/ComparatorTest.php (hunk 6 above)
Comment (morozov) [reply tests/Schema/ComparatorTest.php:30]: Yes, but it still has to be covered with a test until the deprecated code is removed.

File: src/Driver/AbstractMySQLDriver.php (hunk 3 above)
Comment (derrabus) [reply src/Driver/AbstractMySQLDriver.php:130]: Fair enough. 👍🏻

File: tests/Functional/Schema/MySQL/ComparatorTest.php (hunk 5 above)
Comment (morozov) [reply tests/Functional/Schema/MySQL/ComparatorTest.php:21]: This will require `Connection::createSchemaManager()` and `Driver::createSchemaManager()` to be parametrized which will lead to the same issues as in https://github.com/doctrine/dbal/pull/4746#discussion_r695024202.

File: src/Schema/Comparator.php (hunk 4 above)
Comment (morozov) [reply src/Schema/Comparator.php]: I rolled this back and deprecated `Schema::getMigrateFromSql()` and `::getMigrateToSql()` that instantiate a comparator internally. Introducing a dependency of `Schema` on `SchemaManager` would be incorrect, and they are just convenience methods that can be replaced with their implementation.

**Review by greg0ire — DISMISSED** [review]
Wow, looks like this is going to be a huge improvement given the number of linked issues :tada:

**Comment by morozov** [comment]
It should be. I haven't check them individually yet but I want to before the merge.

**Comment by morozov** [comment]
The remaining four linked issues are indeed fixed by this PR (the details are in the comments to each issue). I unlinked two since they appear to be unrelated and need to be addressed separately. One more is not reproducible even on `3.1.x` (closed).

**Review by greg0ire — APPROVED** [review]

File: src/Driver/AbstractMySQLDriver.php (hunk 3 above)
Comment (morozov) [reply src/Driver/AbstractMySQLDriver.php:130]: For posterity: the issue of having to perform these assertions was addressed by https://github.com/doctrine/dbal/pull/5465. Now, even though it is possible to parameterize the `Driver` interface with the `AbtractPlatform` type, it doesn't solve any problem (there's no code that expects that a certain driver will return a certain platform).
