### PR TITLE
#4295 Keep master, slaves, keepReplica params in MasterSlaveConnection

### LINKED ISSUE #4295: MasterSlaveConnection was BC Broken in 2.11.0 affecting doctrine/doctrine-bundle
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.11.0

#### Summary

`Doctrine\DBAL\Connections\MasterSlaveConnection` has changed how it handles `$params` (`__construct` arg 1). Specifically, it now unsets the legacy parameters `master` / `slaves`. This is a BC break because `Doctrine\DBAL\Connection::getParams` is `public`. Anything relying on these parameters will now break however the major version of `doctrine/dbal` was not bumped.

#### Current behaviour

For example `doctrine/doctrine-bundle`'s `Command`s use the following code to extract connection params:

```php
$params = $connection->getParams();
if (isset($params['master'])) {
    $params = $params['master'];
}
```

These commands now fail:

```
03:26:50 ERROR     [console] Error thrown while running command "{command}". Message: "{message}" ["exception" => InvalidArgumentException { …},"extra" => ["command" => "-v doctrine:database:create","message" => "Connection does not contain a 'path' or 'dbname' parameter and cannot be created."]]

In CreateDatabaseDoctrineCommand.php line 82:

  [InvalidArgumentException]                                                         
  Connection does not contain a 'path' or 'dbname' parameter and cannot be created.  

```

#### How to reproduce

```php
$masterParam = [/***/];
$slavesParam = [/***/];
$conn = new \Doctrine\DBAL\Connections\MasterSlaveConnection([
    'master' => $masterParam,
    'slaves' => $slavesParam,
]);
\assert($conn->getParams()['master'] === $masterParam); // fails, used to pass in doctrine/dbal 2.10.4
\assert($conn->getParams()['slaves'] === $slavesParam); // fails, used to pass in doctrine/dbal 2.10.4
```

#### Expected behaviour

`Doctrine\DBAL\Connections\MasterSlaveConnection` should not `unset($params['master']);` / `unset($params['slaves']);`

### PR DESCRIPTION
**Pull request by kralos**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4295

#### Summary

Ensure `Doctrine\DBAL\Connections\MasterSlaveConnection` `$params` are not stripped as `Doctrine\DBAL\Connection::getParams` is public and used by other libraries (e.g. `doctrine/doctrine-bundle`).

### CODE REVIEW

**Comment by kralos** [comment]
@greg0ire Build failure is unrelated to this MR, can you for it to retry or override?

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+use Doctrine\DBAL\Connections\MasterSlaveConnection;
+use Doctrine\DBAL\Driver;
+use Doctrine\Tests\DbalTestCase;
+
+class MasterSlaveConnectionTest extends DbalTestCase
+{
+    /**
+     * \Doctrine\DBAL\Connection::getParams has been marked @internal as of 2.11.0
+     * This test will be removed in 3.0
```
Comment (stof) [inline tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:13]: this comment can be removed. MasterSlaveConnection itself has been deprecated and will be removed in 3.0 entirely anyway.

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+     */
+    public function testConnectionDoesParamsRemainAvailable(): void
```
Comment (greg0ire) [inline tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:11]:
```suggestion
    public function testConnectionParamsRemainAvailable(): void
```

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+                [
+                    'host' => 'slave1.host',
+                    'user' => 'root',
+                    'password' => 'password',
+                    'port' => '1234',
+                ],
+            ],
+        ];
+
+        $connection = new MasterSlaveConnection($constructionParams, $this->createMock(Driver::class));
```
Comment (greg0ire) [inline tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:32]:
```suggestion
        $connection = new MasterSlaveConnection($constructionParams, $this->createStub(Driver::class));
```

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+
+        $connectionParams = $connection->getParams();
+        foreach ($constructionParams as $key => $value) {
+            self::assertSame($constructionParams[$key], $value);
```
Comment (greg0ire) [inline tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: Did you check that the test fails if you revert your changes?

**Review by greg0ire — COMMENTED** [review]
> @greg0ire CI failure is unrelated to this MR, can you force it to retry or override?

Addressing the review will be sufficient for that purpose since it will trigger a new build.

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 4 above)
Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: Yes

Comment (greg0ire) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: Really?

```
git restore --source=origin/2.11.x lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php
vendor/bin/phpunit tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php                       
PHPUnit 9.3.2 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.030, Memory: 6.00 MB

OK (1 test, 4 assertions)
```

Any idea why I'm commenting on this specific line? :smile:

Comment (stof) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: The test should use `$connectionParams[$key]` on that line. Otherwise, it is comparing an array to itself.

Comment (greg0ire) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: Should have been in a spoiler tag :stuck_out_tongue:

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 2 above)
Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:11]: removed

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 3 above)
Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:32]: changed

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 4 above)
Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: oops, i refactored before my last push and broke, fixed now

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 1 above)
Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php]: removed

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 3 above)
Comment (greg0ire) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:32]: It does not look changed to me…

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php (hunk 4 above)
Comment (greg0ire) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:36]: It still looks wrong. Did you forget to push or something?

Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php]: was just waiting for composer / phpunit / phpcs locally etc before pushing

File: tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+                ],
+            ],
+        ];
+
+        $connection = new MasterSlaveConnection($constructionParams, $this->createStub(Driver::class));
+
+        $connectionParams = $connection->getParams();
+        foreach ($constructionParams as $key => $value) {
+            self::assertSame($value, $connectionParams[$key]);
+        }
```
Comment (greg0ire) [inline tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:37]:
```suggestion
        self::assertEqualsCanonicalizing($constructionParams, $connection->getParams());
```

Comment (kralos) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:37]: the issue isn't the order, it's pollution of params by the constructor (`primary`, `replica`, `keepReplica`). Hence the loop. if you really want this, i'd have to `array_intersect` but i thought a loop was simpler.

Comment (greg0ire) [reply tests/Doctrine/Tests/DBAL/Connections/MasterSlaveConnectionTest.php:37]: Oh right, nevermind then keep it that way 👍

**Review by greg0ire — APPROVED** [review]

**Review by morozov — APPROVED** [review]
