### PR TITLE
fixed annotations of parameter $columns in Table

### LINKED ISSUE #3380: 2.9 BC Break on Doctrine\DBAL\Schema\Table method signatures
|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

Sorry if this is intended, but I couldn't find anywhere mentioning these changes on these `Doctrine\DBAL\Schema\Table` method signatures :
- setPrimaryKey(int, string) -> setPrimaryKey(array)
- addUniqueIndex(int, string) -> addUniqueIndex(array)
- addIndex(int, string) -> addIndex(array)

I can drop a PR either reverting the method signature's back or update the docs if needed.

### PR DESCRIPTION
**Pull request by LukasVitek**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #3380.

#### Summary

Fixed annotations of parameter `$columns` in Table. Parameter `$columns` is array of mixed, nowhere in the code does not treated with him as with an array of array. 

Before the fix the code, phpStan reported an error with this code:
```php
$table = new Table('tableName');
$table->addUniqueIndex(['col1', 'col2']);
```
`Parameter #1 $columnNames of method Doctrine\DBAL\Schema\Table::addUniqueIndex() expects array<array>, array<int, string> given. `

### CODE REVIEW

**Comment by morozov** [comment]
@LukasVitek is this related to https://github.com/doctrine/dbal/issues/3380? Could you double check if those `mixed[][] $columns/$columnNames` are actually `string[] $columnNames`, not `mixed[]`? See the details in the related ticket.

**Comment by LukasVitek** [comment]
Actually, yes, issue https://github.com/doctrine/dbal/issues/3380 is very related. 
And yes, it is always assumed that `$columns/$columnNames` are type of `string[]`, 
except for one case here: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Table.php#L274 where it is verified if the variable in the array is type of `string`.
Should I therefore type of annotations to remake to `string[]`?

File: lib/Doctrine/DBAL/Schema/Table.php [hunk 1]
```diff
@@ -253,12 +253,12 @@ public function columnsAreIndexed(array $columnsNames)
     }
 
     /**
-     * @param mixed[][] $columnNames
-     * @param string    $indexName
-     * @param bool      $isUnique
-     * @param bool      $isPrimary
-     * @param string[]  $flags
-     * @param mixed[]   $options
+     * @param string[] $columnNames
```
Comment (morozov) [inline lib/Doctrine/DBAL/Schema/Table.php]: > […] except for one case here: https://github.com/doctrine/dbal/blob/4b4d44f90ae6efde2a494b12167348bbc0551e09/lib/Doctrine/DBAL/Schema/Table.php#L274
where it is verified if the variable in the array is type of `string`.

Here, it should be something like `string[]|mixed[][]`. Judging by the code, it allows the following syntax:
```php
_createIndex([
    'column_1',
    'column_2' => [
        'option' => 'value'
    ],
]);
```

**Review by koftikes — DISMISSED** [review]

File: lib/Doctrine/DBAL/Schema/Table.php [hunk 2]
```diff
@@ -253,12 +253,12 @@ public function columnsAreIndexed(array $columnsNames)
     }
 
     /**
-     * @param mixed[][] $columnNames
-     * @param string    $indexName
-     * @param bool      $isUnique
-     * @param bool      $isPrimary
-     * @param string[]  $flags
-     * @param mixed[]   $options
+     * @param string[]|mixed[][] $columnNames
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Schema/Table.php]: This is probably not `mixed[][]`. To inspect that, I'd suggest digging into the `Index` constructor.

**Review by Ocramius — DISMISSED** [review]

File: lib/Doctrine/DBAL/Schema/Table.php (hunk 2 above)
Comment (morozov) [reply lib/Doctrine/DBAL/Schema/Table.php]: If it's not `mixed[][]`, then the code handling `$indexColOptions` should be removed. Given that this is a private API, I wanted to make the annotations consistent with the code and then clean up the code in a minor release.

Comment (morozov) [reply lib/Doctrine/DBAL/Schema/Table.php]: Indeed, it's only `string[]` Judging by the four calls from the same class. Please revert back to `string[] $columnNames` and rework the `foreach` loop to:
```php
foreach ($columnNames as $columnName) {
}
```

**Comment by morozov** [comment]
@LukasVitek please squash and I’ll merge it.

**Comment by thewilkybarkid** [comment]
`columnsAreIndexed()` needs updating too.

**Comment by morozov** [comment]
@LukasVitek please update `columnsAreIndexed()` as well.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thank you @LukasVitek and @thewilkybarkid.

**Comment by leofeyer** [comment]
I'm afraid this change breaks indexes with a fixed length. We have an index named `path(768)`, which now throws a `There is no column with name 'path(768)'` exception, because the following code has been removed:

```php
    foreach ($columnNames as $columnName => $indexColOptions) {
        if (is_numeric($columnName) && is_string($indexColOptions)) {
            $columnName = $indexColOptions;
        }
```

**Comment by Ocramius** [comment]
@leofeyer can you please report a new issue? Got a test case for it?

**Comment by leofeyer** [comment]
@Ocramius Sure, here you go: #3409
