### PR TITLE
Move fix for user provided pdo connection

### LINKED ISSUE #4619: ensureForwardCompatibilityStatement broke existing code
### Bug Report

This is likely a low priority. 

|    Q        |   A
|------------ | ------
| BC Break    | yes?
| Version     | 2.13.1, but it looks like 2.12.x branch has the issue too. 2.12.1 worked fine

#### Summary

Commit 4297f5027011027529fdccfa3b1fbbb3090a7d25 broke `Connection` when passing in `$params['pdo']`

https://github.com/doctrine/dbal/pull/4590 says it should have fixed the issue, but I'm using 2.13.1 and it still seems to be broken.

#### Current behaviour

If you build a `Connection` object using an already established `$params['pdo']` connection, commit 4297f5027011027529fdccfa3b1fbbb3090a7d25 caused breaking changes that no longer allow that behavior. Now you get the following error:

```
An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'':  Argument 1 passed to Doctrine\DBAL\Connection::ensureForwardCompatibilityStatement() must be an instance of Doctrine\DBAL\Driver\ResultStatement, instance of PDOStatement given, called in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1314
```

#### How to reproduce

```php

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Driver\PDO\MySQL\Driver;

$params = [
    'pdo' => new \PDO('mysql:<whatever>'),
];
$driver = new Driver();

$connection = new Connection($params, $driver);
// This is a query that Doctrine Migrations tool does:
$connection->executeQuery("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
```

- Within the `executeQuery()` method, it calls `$connection = $this->getWrappedConnection();` which is returning the raw PDO connection. 
- Later in the method it calls `$stmt = $connection->prepare($sql);` which is a raw PDOStatement object.
- At the end of the method the referenced commit changed the code to `return $this->ensureForwardCompatibilityStatement($stmt);` and it expects `$stmt` to be an instance of `ResultStatement`, but of course it's the raw PDOStatement instead.

#### Expected behaviour

No error to be thrown

### PR DESCRIPTION
**Pull request by bizurkur**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | yes
| Fixed issues | #4619

#### Summary

Commit 4297f5027011027529fdccfa3b1fbbb3090a7d25 broke `Connection` when passing in `$params['pdo']`

https://github.com/doctrine/dbal/pull/4590 says it should have fixed the issue, but I'm using 2.13.1 and it still seems to be broken.

I took the fix that was already applied in #4590 and moved it to the `Connection` class. This way it gets applied to all connections, not just connections built using the DriverManager.

If it's a good idea to keep the fix applied inside DriverManager, too, please let me know and I can add that back.

#### How to reproduce

```php

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Driver\PDO\MySQL\Driver;

$params = [
    'pdo' => new \PDO('mysql:<whatever>'),
];
$driver = new Driver();

$connection = new Connection($params, $driver);
// This is a query that Doctrine Migrations tool does:
$connection->executeQuery("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
```

-----

Also, I love Doctrine. You all are doing awesome work!

### CODE REVIEW

**Comment by bizurkur** [comment]
Oh, and I opened this PR against 2.12.x because it looked like the code had the same issue in that branch. Please let me know if I need to open a separate PR against 2.13.x or if 2.12.x will get merged into 2.13.x.

File: lib/Doctrine/DBAL/Connection.php [hunk 1]
```diff
@@ -195,6 +197,7 @@ public function __construct(
 
         if (isset($params['pdo'])) {
             $this->_conn = $params['pdo'];
+            $this->_conn->setAttribute(PDO::ATTR_STATEMENT_CLASS, [PDODriverStatement::class, []]);
```
Comment (mdumoulin) [inline lib/Doctrine/DBAL/Connection.php:209]: Maybe we should add some logic of the DriverManager here :
- Check that pdo is a PDO instance
- Trigger a deprecation

If we do so, I'm not sure that deprecation in DriverManager will still be useful. Someone using factory would get 2 deprecation.

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php [hunk 2]
```diff
@@ -701,7 +704,7 @@ public static function dataCallConnectOnce(): iterable
     public function testCallConnectOnce(string $method, array $params): void
     {
         $driverMock   = $this->createMock(Driver::class);
-        $pdoMock      = $this->createMock(Connection::class);
+        $pdoMock      = $this->createMock(PDO::class);
         $platformMock = $this->createMock(AbstractPlatform::class);
         $stmtMock     = $this->createMock(Statement::class);
```
Comment (mdumoulin) [inline tests/Doctrine/Tests/DBAL/ConnectionTest.php:714]: Not sure that your tests modification actually test your modification. 

I would rather add a functional test where the connection is not built by DriverManager : https://github.com/doctrine/dbal/blob/1372a42083dedc56016051d61526507fb5521f9c/tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php#L354-L363

**Comment by greg0ire** [comment]
2.12.x is no longer maintained, please target 2.13 instead.

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php (hunk 2 above)
Comment (bizurkur) [reply tests/Doctrine/Tests/DBAL/ConnectionTest.php:714]: Added

File: lib/Doctrine/DBAL/Connection.php (hunk 1 above)
Comment (bizurkur) [reply lib/Doctrine/DBAL/Connection.php:209]: - Moved the deprecation warning to trigger from Connection and removed it from DriverManager
- Added the PDO check

File: lib/Doctrine/DBAL/Connection.php [hunk 3]
```diff
@@ -193,8 +195,20 @@ public function __construct(
         $this->_driver = $driver;
         $this->params  = $params;
 
+        // check for existing pdo object
+        if (isset($params['pdo']) && ! $params['pdo'] instanceof PDO) {
```
Comment (morozov) [inline lib/Doctrine/DBAL/Connection.php]: This condition partially duplicates the following one. Would it make sense to deduplicate them?
```php
if (isset(...)) {
    Deprecation::trigger()

    if (! instanceof PDO) {
        throw
    }
}
```

Comment (bizurkur) [reply lib/Doctrine/DBAL/Connection.php]: I'm all for changing it however it is wanted. The above code was a literal copy/paste from DriverManager. I wasn't sure if it was written like that to avoid nesting an `if` inside another `if` or what, so I kept it the same.

I swapped it to be like the above example, though.

File: lib/Doctrine/DBAL/Connection.php [hunk 4]
```diff
@@ -193,8 +195,20 @@ public function __construct(
         $this->_driver = $driver;
         $this->params  = $params;
 
+        // check for existing pdo object
```
Comment (morozov) [inline lib/Doctrine/DBAL/Connection.php]: This comment is redundant. The code is self-explanatory.

File: lib/Doctrine/DBAL/DriverManager.php [hunk 5]
```diff
@@ -220,14 +218,7 @@ public static function getConnection(
         }
 
         if (isset($params['pdo'])) {
-            Deprecation::trigger(
-                'doctrine/dbal',
-                'https://github.com/doctrine/dbal/pull/3554',
-                'Passing a user provided PDO instance directly to Doctrine is deprecated.'
-            );
-
             $params['pdo']->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
```
Comment (morozov) [inline lib/Doctrine/DBAL/DriverManager.php:245]: Should this also be moved to `Connection`?

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php [hunk 6]
```diff
@@ -646,28 +647,40 @@ public function testFetchAll(): void
         self::assertSame($result, $conn->fetchAll($statement, $params, $types));
     }
 
+    public function testConnectionThrowsExceptionWhenInvalidPDOProvided(): void
+    {
+        $driverMock = $this->createMock(Driver::class);
+        $pdo        = $this->createMock(Connection::class);
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/ConnectionTest.php]: Could it be an `stdClass` mock for more clarity?

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php [hunk 7]
```diff
@@ -646,28 +647,40 @@ public function testFetchAll(): void
...
+        $conn = new Connection(['pdo' => $pdo], $driverMock);
 
         self::assertTrue($conn->isConnected(), 'Connection is not connected after passing external PDO');
     }
 
     public function testCallingDeleteWithNoDeletionCriteriaResultsInInvalidArgumentException(): void
     {
         $driver  = $this->createMock(Driver::class);
-        $pdoMock = $this->createMock(\Doctrine\DBAL\Driver\Connection::class);
+        $pdoMock = $this->createMock(PDO::class);
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/ConnectionTest.php]: The case is not PDO-specific but it's implemented via PDO as a way to inject a driver connection.

Please use the implementation from #3548: https://github.com/doctrine/dbal/blob/dcc3f2d4dcea0e7e82cfd3bfd4c1adbc925c746a/tests/Doctrine/Tests/DBAL/ConnectionTest.php#L688-L696

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php [hunk 8]
```diff
@@ -701,7 +714,7 @@ public static function dataCallConnectOnce(): iterable
     public function testCallConnectOnce(string $method, array $params): void
     {
         $driverMock   = $this->createMock(Driver::class);
-        $pdoMock      = $this->createMock(Connection::class);
+        $pdoMock      = $this->createMock(PDO::class);
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/ConnectionTest.php]: Same as above, it likely doesn't have to be a PDO connection.

**Comment by morozov** [comment]
> Property `Doctrine\DBAL\Connection::$_conn` (`Doctrine\DBAL\Driver\Connection|null`) does not accept `PDO`.

This error probably will have to be suppressed since the library violates its own API by allowing a PDO instance to be used instead of a driver connection.

**Comment by morozov** [comment]
Please rebase on top of `2.13.x` to fix the MySQL build failures (see https://github.com/doctrine/dbal/pull/4625).

File: lib/Doctrine/DBAL/DriverManager.php (hunk 5 above)
Comment (mdumoulin) [reply lib/Doctrine/DBAL/DriverManager.php:245]: Seems a bit risky to me. This will change the current behavior by overriding the error mode for someone providing a 'pdo' params without using DriverManager.

```php
$pdo = new PDO('sqlite::memory:');
$pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_SILENT);

$conn = new \Doctrine\DBAL\Connection(['pdo' => $pdo], $driver);
```

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php (hunk 8 above)
Comment (bizurkur) [reply tests/Doctrine/Tests/DBAL/ConnectionTest.php]: I don't know how to change this, if it needs to be changed. The test is mocking `connect` and `connect` is the only method that sets `$_conn`, other than passing in a PDO object to the constructor. Which, now that it has the instanceof check, must be a PDO object.

I was able to change the other tests, just not this one.

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php (hunk 7 above)
Comment (bizurkur) [reply tests/Doctrine/Tests/DBAL/ConnectionTest.php]: Updated

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php (hunk 6 above)
Comment (bizurkur) [reply tests/Doctrine/Tests/DBAL/ConnectionTest.php]: Yes. Changed.

File: lib/Doctrine/DBAL/Connection.php (hunk 4 above)
Comment (bizurkur) [reply lib/Doctrine/DBAL/Connection.php]: Removed

**Comment by bizurkur** [comment]
> Please rebase on top of `2.13.x` to fix the MySQL build failures (see #4625).

Rebase pushed

**Comment by andrewkhan1** [comment]
Any luck getting this one pushed? It is preventing us from updating some of our dependencies. Thanks for all of your hard work everyone! :100:

**Comment by morozov** [comment]
Somehow I missed all the updates after my last review. Will take a look. Thanks for the reminder, @andrewkhan1.

File: tests/Doctrine/Tests/DBAL/ConnectionTest.php (hunk 8 above)
Comment (morozov) [reply tests/Doctrine/Tests/DBAL/ConnectionTest.php]: See the implementation from `3.x`: https://github.com/doctrine/dbal/blob/bd5fc0d72861caeed7aaef91756d3e35527aab67/tests/ConnectionTest.php#L587-L601

File: tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php [hunk 9]
```diff
@@ -366,6 +367,21 @@ public function testUserProvidedPDOConnection(): void
...
+    public function testUserProvidedPDOConnectionWithoutDriverManager(): void
+    {
+        $connection = new Connection(
+            ['pdo' => new PDO('sqlite::memory:')],
+            new PDODriver()
+        );
+
+        $result = $connection->executeQuery('SELECT 1');
+
+        self::assertInstanceOf(ForwardCompatibility\Result::class, $result);
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ConnectionTest.php]: I believe the expected type should be one of these two: https://github.com/doctrine/dbal/blob/63d19ff4f3ac3eafe357e11b4fa11f13020b75a6/lib/Doctrine/DBAL/Connection.php#L1279

Otherwise, if the code starts returning just the `Result`, the method signature will be violated but the test will pass.

**Review by morozov — COMMENTED** [review]
Looks good overall. Please see the comments and squash commits.

**Comment by bizurkur** [comment]
Sorry, but I'm just gonna close this. The PR was meant to be an extremely simple fix to move the code from https://github.com/doctrine/dbal/pull/4590 into another class, nothing more. Yet it seems like each time I make the changes you guys ask for, you review it again and ask for different changes. I was only trying to move one line of code to a better location.

Feel free to re-open, copy/paste to a new PR, do whatever you want. I personally don't need this fix anymore so I've lost interest.

**Comment by greg0ire** [comment]
Come on! I hate it when a contributor gets discouraged at 99% of the task! Let me do the remaining 1%, it would be a shame to waste your efforts so close to the finish line.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @bizurkur.
