### PR TITLE
Infer omitted column charset from collation

### LINKED ISSUE #5338: Schema validation error (and diff error) when collation is set
### Bug Report

Not sure if this belongs here or to ORM / Migrations, but this looks directly related to #5322.

|    Q        |   A
|------------ | ------
| Version     | 3.3.4

#### Summary

When an entity has a `collation` set for a `string` column:

```php
class User
{
    #[ORM\Column(type: 'string', length: 100, options: ['collation' => 'ascii_bin'])]
    public string $email;
}
```

`doctrine:schema:validate` always reports:

> [ERROR] The database schema is not in sync with the current mapping file.   

and `doctrine:migrations:diff` generates the same migration again and again, even after executing it.

#### How to reproduce

Small reproduce project: https://github.com/BenMorel/doctrine-bug-2022-03-29

- Set `DATABASE_URL` in `.env` or `.env.local`
- Run `bin/console doctrine:database:create`
- Run `bin/console doctrine:migrations:diff`
    ```
    Generated new migration class to "/home/benjamin/src/roketto/packages/backend/bug/migrations/Version20220329140701.php"
    
    To run just this migration for testing purposes, you can use migrations:execute --up 'DoctrineMigrations\\Version20220329140701'
    
    To revert the migration you can use migrations:execute --down 'DoctrineMigrations\\Version20220329140701'
- Execute the migration: `bin/console doctrine:migrations:migrate -n`
    ```
    [notice] Migrating up to DoctrineMigrations\Version20220329140701
    [notice] finished in 18.6ms, used 14M memory, 1 migrations executed, 1 sql queries
    ```
- Check the schema: `bin/console doctrine:schema:validate`
    ```
    Mapping
    -------
    
    [OK] The mapping files are correct.
    
    Database
    --------
    
    [ERROR] The database schema is not in sync with the current mapping file.                                              
    ```

**At this point, running `doctrine:migrations:diff` again generates the same migration again and again:**

```sql
ALTER TABLE user CHANGE email email VARCHAR(100) NOT NULL COLLATE `ascii_bin`
```

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug

Fixes #5338.

### CODE REVIEW

File: src/Platforms/MySQL/CollationMetadataProvider.php [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+declare(strict_types=1);
+
+namespace Doctrine\DBAL\Platforms\MySQL;
+
+/**
+ * @internal
+ */
+interface CollationMetadataProvider
+{
+    public function getCollationCharset(string $collation): ?string;
```
Comment (greg0ire) [inline src/Platforms/MySQL/CollationMetadataProvider.php:12]: What does `null` mean here? "This collation has no charset"? "We don't know about this collation"? Both? If both, should the second case result in an exception?

Comment (morozov) [reply src/Platforms/MySQL/CollationMetadataProvider.php:12]: > What does `null` mean here?

"This collation has no charset" is impossible, so it's "We don't know about this collation".

> […] should the second case result in an exception?

It doesn't have to. Should `strpos()` throw an exception if the substring is not found? The calling code handles `null` by not updating options, so if the collation is invalid, the DDL will eventually fail once it hits the database.

If we decide to throw an exception here, how do we unit-test the comparator without the database connection? Right now, we supply it with a provider that always returns `null`, which is fine because no unit tests rely on this feature.

**Review by greg0ire — APPROVED** [review]

File: src/Platforms/MySQL/CollationMetadataProvider.php (hunk 1 above)
Comment (greg0ire) [reply src/Platforms/MySQL/CollationMetadataProvider.php:12]: It's clearer, thanks for the explanation.

**Comment by Ocramius** [comment]
Note to self: this will do something alike:

```php
$column->setPlatformOptions([
    'collation' => 'utf8_bin',
    'charset' => 'utf8',
]);
```

~What I found while testing locally (couldn't investigate further, so this is mostly a note to self, in order to figure out how to debug + open an issue about it), is that the order of the platform options may be scrambled.~

~Sometimes, `'collation'` comes first, other times, `'charset'` comes first.~

This seems to trip the whole schema comparison somewhere, although I couldn't pinpoint it yet. 

EDIT: errata: it's just the table charset being diffed with my own column definition. Very confused about it, need to check deeper. 

EDIT2: possibly found the culprit, and it's possibly a weird edge case that doesn't really need fixing. Given a table like this:

```sql
CREATE TABLE a_table
(
   a_column VARCHAR(255) COLLATE utf8_bin NULL,
)
    charset = utf8;
```

The following table definition seems to always produce a diff:

```php
new Table(
    'a_table',
    new Column(
        'a_column',
        Type::getType(Types::STRING),
        ['platformOptions' => ['collation' => 'utf8_bin, 'charset' => 'utf8']]
)
```

This makes sense, because we don't want to "remove" the charset from columns that have an `utf8` charset, and are already part of a table with `utf8` charset: we mostly want to ignore that.

This will produce `ALTER` statements like:

```sql
ALTER TABLE a_table CHANGE a_column a_column VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_bin`;
```

Next up for me is dusting off the DBAL test suite and making it reproducible (plus new issue)
