### PR TITLE
Merge 2.13.x into 3.1.x

### LINKED ISSUE #4869: mysqli::real_connect may be called with null $flags
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1

#### Summary

In PHP 8.1 you get a deprecation when `mysqli::real_connect` is called with null $flags:
`
mysqli::real_connect(): Passing null to parameter #7 ($flags) of type int is deprecated
`

### PR DESCRIPTION
**Pull request by greg0ire**
Closes https://github.com/doctrine/dbal/issues/4869

### CODE REVIEW

**Comment by greg0ire** [comment]
Note to self: port 429f746 to 2.13.x Cc @derrabus in case you want to beat me to it.

**Comment by derrabus** [comment]
I intend to do that tomorrow, if that's not too late for you.

**Comment by greg0ire** [comment]
@derrabus that's great, there is absolutely no hurry!

File: src/Schema/AbstractSchemaManager.php [hunk 1]
```diff
@@ -156,6 +156,7 @@ public function listSequences($database = null)
     {
         if ($database === null) {
             $database = $this->_conn->getDatabase();
+            assert($database !== null);
```
Comment (greg0ire) [inline src/Schema/AbstractSchemaManager.php]: I don't know how likely it is these assertions will actually fail. If there is a more appropriate exception I should throw, let me know.

File: phpstan.neon.dist [hunk 2]
```diff
@@ -133,6 +133,30 @@ parameters:
...
+        # https://github.com/phpstan/phpstan/issues/4679
+        -
+            message: '~^Cannot call method writeTemporary\(\) on OCILob\|null\.$~'
+            paths:
+                - src/Driver/OCI8/Statement.php
+
+        # https://github.com/phpstan/phpstan/issues/5786
+        -
+            message: '~Parameter \#7 \$flags of method mysqli\:\:real_connect\(\) expects int, int\|null given\.~'
+            path: src/Driver/Mysqli/Connection.php
```
Comment (greg0ire) [inline phpstan.neon.dist]: I added that last one, so please take a look at the linked PHPStan issue.

**Comment by greg0ire** [comment]
Settings will have to be tweaked before pushing this.

File: phpstan.neon.dist (hunk 2 above)
Comment (greg0ire) [reply phpstan.neon.dist]: Ah I have to rework this actually, because of https://github.com/doctrine/dbal/issues/4869

File: src/Driver/Mysqli/Connection.php [hunk 3]
```diff
@@ -42,10 +42,14 @@ public function __construct(
         ?string $database = null,
         ?int $port = null,
         ?string $socket = null,
-        ?int $flags = null,
+        ?int $flags = 0,
```
Comment (morozov) [inline src/Driver/Mysqli/Connection.php]: The constructor is internal. It won’t be a BC-break, if the parameter is made non-nullable.

File: src/Schema/AbstractSchemaManager.php (hunk 1 above)
Comment (morozov) [reply src/Schema/AbstractSchemaManager.php]: Probably, it should be an exception. Let’s suppress all errors with non-obvious fixes instead of fixing here.

**Review by derrabus — APPROVED** [review]

**Review by morozov — APPROVED** [review]
