### PR TITLE
[DBAL-1779] Fix string column type declarations with whitespace on SQLite

### LINKED ISSUE #1339: DBAL-1779: [GH-921] Update AbstractPlatform.php
Jira issue originally created by user @doctrinebot:

This issue is created automatically through a Github pull request on behalf of szekeresa:

Url: https://github.com/doctrine/dbal/pull/921

Message:

trim $dbType

### PR DESCRIPTION
**Pull request by deeky666**
When introspecting column types from a table in SQLite that has not been created by Doctrine and contains whitespaces in the DDL, DBAL fails to introspect the column types correctly.

**Works**

``` sql
CREATE TABLE dbal_1779 (
    foo VARCHAR(64),
    bar TEXT(100)
)
```

**Does not work**

``` sql
CREATE TABLE dbal_1779 (
    foo VARCHAR (64) ,
    bar TEXT (100)
)
```

fixes #1339
closes/supersedes #921

### CODE REVIEW

File: tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php [hunk 1]
```diff
@@ -157,6 +158,34 @@ public function testNonDefaultPKOrder()
     }
 
     /**
+     * @group DBAL-1779
+     */
+    public function testListTableColumnsWithWhitespacesInTypeDeclarations()
```
Comment (zeroedin-bill) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php]: Probably needs also a testListTableColumnsWithoutWhitespacesInTypeDeclarations, too.

File: lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php [hunk 2]
```diff
@@ -269,7 +269,7 @@ protected function _getPortableTableColumnList($table, $database, $tableColumns)
     protected function _getPortableTableColumnDefinition($tableColumn)
     {
         $parts = explode('(', $tableColumn['type']);
-        $tableColumn['type'] = $parts[0];
+        $tableColumn['type'] = trim($parts[0]);
```
Comment (zeroedin-bill) [inline lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php]: :+1:

File: tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php (hunk 1 above)
Comment (deeky666) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php]: @zeroedin-bill this is already covered by all the other DBAL tests

Comment (zeroedin-bill) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/SqliteSchemaManagerTest.php]: k
