### PR TITLE
Stop considering generated column definition as being its default value

### LINKED ISSUE #6198: PostgresSQLSchemaManager incorrectly detect GENERATED column definition as being the column default value
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | all

#### Summary

As reported https://github.com/doctrine/dbal/issues/5661 

When creating  [generated column ](https://www.postgresql.org/docs/current/ddl-generated-columns.html) using `columnDefinition`  , the schema tool will try to generate a  `ALTER TABLE mytable  ALTER mycolumn DROP DEFAULT

the reason is that currently `PostgreSQLSchemaManager`  considers `SELECT pg_get_expr(adbin, adrelid) FROM pg_attrdef`  as containing ONLY the  attribute *DEFault* value , while it contains the attribute *DEFinition* , which is 99% of the time the default value .... except for generated column

for a column defined as `foobar INT GENERATED ALWAYS AS  ( otherColumn / 100 ) STORED`   ,  `SELECT pg_get_expr(adbin, adrelid) FROM pg_attrdef` will return the  part inside `()`   i.e `otherColumn / 100`  , i.e the definition of the generated value.

#### Current behaviour

Currently `ColumnDiff`  will always see a change because the schema definition says there's no default which is correct as 'default' as no meaning for a  ,  while `PostgreSQLSchemaManager` will report the column as having 

#### How to reproduce
```sql
CREATE SEQUENCE fulltext_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE fulltext (
id INT NOT NULL, column1 TEXT DEFAULT NULL, 
column2 TEXT DEFAULT NULL,
concatenated  TEXT GENERATED ALWAYS AS  ( column1 || column 2 )  STORED,
PRIMARY KEY(id)
);
```

    * Add the below entity in your (Symfony) codebase. Outside Symfony, change the command to orm:schema-tool:update. The point is to get the SchemaTool to try to detect changes.
    * Run bin/console do:sch:up --force to create the table and sequence
    * Run bin/console do:sch:up --dump-sql to see the broken update queries.

```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class Fulltext
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
    
    #[ORM\Column(type: 'text', nullable: true)]
    private $column1;

    #[ORM\Column(type: 'text', nullable: true)]
    private $column2;

    #[ORM\Column(
        type: 'text',
        nullable: true,
        insertable: false,
        updatable: false,
        columnDefinition: "TEXT GENERATED ALWAYS AS (  column1 || column2 )   STORED",
        generated: 'ALWAYS',
    )]
    private $concatenated;
}
```

it will try to generate the diff 

```
`ALTER TABLE fulltext  ALTER concatenated DROP DEFAULT
```

#### Expected behaviour

it should not see a difference 

 I will open a PR as I have a fix which I think is not hackish

### PR DESCRIPTION
**Pull request by allan-simon**
|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| Fixed issues | #6198 

#### Summary

The `pg_get_expr(adbin, adrelid)` expression in Postgresql's internal table `pg_attrdef` is used to know a column definition

for most column, if this returns something, it means this column's default value. So DBAL has been considering has ALWAYS meaning it contains its default.

However for generated columns, it contains the value definition and not its default value, so we change the selectTableColumns' query to correctly set the 'default' column to `null` for generated columns 

It will help setting correctly the column's attributes which in turn will help generate correct schema diff.

### CODE REVIEW

**Comment by allan-simon** [comment]
I've tested manually on Postgresql 10 (with no support at all of GENERATED column, hence the feature detection code ) ,  Postgresql 13,  14,  15 


For automated test, I've written one, but to be honest I haven't found a documentation on how to run them

File: src/Schema/PostgreSQLSchemaManager.php [hunk 1]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+
+        
         $sql = 'SELECT';
 
         if ($tableName === null) {
             $sql .= ' c.relname AS table_name, n.nspname AS schema_name,';
         }
 
-        $sql .= <<<'SQL'
+        $sql .= <<<SQL
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]: I've remod the `''` to be able to inject the  subquery

I know it's not good, but I didn't find a cleaner way

File: src/Schema/PostgreSQLSchemaManager.php [hunk 2]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+        if ($supportsGeneratedColumn) {
+            // in case of GENERATED ALWAYS AS ( foobar) STORED column
+            // postgreSQL's pg_get_expr(adbin, adrelid) will return the 'foobar' part
+            // which is not the 'default' value of the column but its 'definition'
+            // so in that case we force it to NULL as DBAL will use that column only for the
+            // 'default' value
+            $fragmentDefaultValueSQL = <<<SQL
+                SELECT
+                    CASE
+                        WHEN a.attgenerated = 's' THEN NULL
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]: `s` means `stored` ,  and it will be an empty string for normal column

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: its defined in the link  https://pgpedia.info/g/generated-column.html#implementation that I put above, so i didn't feel it was necessary to put it again

File: src/Schema/PostgreSQLSchemaManager.php [hunk 3]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+        $results = $this->_conn->executeQuery(<<<'SQL'
+            SELECT true
+            FROM information_schema.columns
+            WHERE table_name = 'pg_attribute'
+                AND column_name = 'attgenerated';
+        SQL);
+        $supportsGeneratedColumn = $results->fetchOne();
+
+        $fragmentDefaultValueSQL = <<<SQL
+            SELECT pg_get_expr(adbin, adrelid)
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
             SELECT pg_get_expr(adbin, adrelid)
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 4]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
 
     protected function selectTableColumns(string $databaseName, ?string $tableName = null): Result
     {
+        
+        // feature detection: if attrgenerated exists it means we are 
+        // in a postgreSQL version supporting GENERATED columns
+        // see https://pgpedia.info/g/generated-column.html#implementation
+        $results = $this->_conn->executeQuery(<<<'SQL'
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]: this exists as otherwise on Postgresql < 12 the other request would have failed

File: src/Schema/PostgreSQLSchemaManager.php [hunk 5]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+            SELECT true
+            FROM information_schema.columns
+            WHERE table_name = 'pg_attribute'
+                AND column_name = 'attgenerated';
+        SQL);
+        $supportsGeneratedColumn = $results->fetchOne();
+
+        $fragmentDefaultValueSQL = <<<SQL
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]: I've decided to put the whole subquery rather than just the part that change (i.e the selected column )  because I felt it was easier for future maintainer to have a copy/pastable query rather than having to re-craft the query by hand when trying to understand what the code is doing

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 6]
```diff
@@ -320,6 +320,26 @@ public function testBooleanDefault(callable $comparatorFactory): void
         self::assertFalse($diff);
     }
 
+    /**
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php:329]: @derrabus  this test fail on version of postgresql not supporting GENERATED column (which is normal)  ,  I would like to know how to tell that this test should only be run on postgres 12+  ? 

(for postgres < 12 , my changes will be tested against  regression by the other test checking for default values , i.e the one just above )

File: src/Schema/PostgreSQLSchemaManager.php [hunk 7]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
 
     protected function selectTableColumns(string $databaseName, ?string $tableName = null): Result
     {
+
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 8]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
 
     protected function selectTableColumns(string $databaseName, ?string $tableName = null): Result
     {
+        
+        // feature detection: if attrgenerated exists it means we are
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
        // feature detection: if attrgenerated exists it means we are
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 9]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+             WHERE c.oid = pg_attrdef.adrelid
+                AND pg_attrdef.adnum=a.attnum
+        SQL;
+        if ($supportsGeneratedColumn) {
+            // in case of GENERATED ALWAYS AS ( foobar) STORED column
+            // postgreSQL's pg_get_expr(adbin, adrelid) will return the 'foobar' part
+            // which is not the 'default' value of the column but its 'definition'
+            // so in that case we force it to NULL as DBAL will use that column only for the
+            // 'default' value
+            $fragmentDefaultValueSQL = <<<SQL
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
            $fragmentDefaultValueSQL = <<<'SQL'
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 10]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+                    CASE
+                        WHEN a.attgenerated = 's' THEN NULL
+                        ELSE pg_get_expr(adbin, adrelid)
+                    END
+                 FROM pg_attrdef
+                 WHERE c.oid = pg_attrdef.adrelid
+                    AND pg_attrdef.adnum=a.attnum
+            SQL;
+        }
+
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 11]
```diff
@@ -610,13 +610,50 @@ protected function selectTableNames(string $databaseName): Result
...
+
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion

```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 12]
```diff
@@ -320,6 +320,26 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
+    {
+        $table = new Table('ddc2843_bools');
+        $table->addColumn('id', Types::INTEGER);
+        $table->addColumn('idIsOdd', Types::BOOLEAN, ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED']);
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]:
```suggestion
        $table->addColumn(
            'idIsOdd',
            Types::BOOLEAN,
            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED']
        );
```

File: src/Schema/PostgreSQLSchemaManager.php (hunk 5 above)
Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
        $fragmentDefaultValueSQL = <<<'SQL'
```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 13]
```diff
@@ -320,6 +320,30 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
     }
 
+    /**
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
+    {
+        $table = new Table('ddc2843_bools');
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]:
```suggestion
        $table = new Table('ddc6198_generated_always_as');
```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 14]
```diff
@@ -320,6 +320,30 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
     }
 
+    /**
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
+    {
+        $table = new Table('ddc6198_generated_always_as');
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php:336]:
```suggestion
        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
             self::markTestSkipped('Manually setting the Oid is not supported in Postgres 11 and earlier');
        }

        $table = new Table('ddc6198_generated_always_as');
```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php (hunk 6 above)
Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php:329]: found it !

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 15]
```diff
@@ -320,6 +320,34 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
+        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
+             self::markTestSkipped('Manually setting the Oid is not supported in Postgres 11 and earlier');
+        }
+
+        $table = new Table('ddc6198_generated_always_as');
+        $table->addColumn('id', Types::INTEGER);
+        $table->addColumn(
+            'idIsOdd',
+            Types::BOOLEAN,
+            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED']
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]:
```suggestion
            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED'],
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 16]
```diff
@@ -610,13 +610,47 @@ protected function selectTableNames(string $databaseName): Result
...
+        SQL);
+        $supportsGeneratedColumn = $results->fetchOne();
+
+        $fragmentDefaultValueSQL = <<<'SQL'
+             SELECT pg_get_expr(adbin, adrelid)
+             FROM pg_attrdef
+             WHERE c.oid = pg_attrdef.adrelid
+                AND pg_attrdef.adnum=a.attnum
+        SQL;
+        if ($supportsGeneratedColumn) {
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion

        if ($supportsGeneratedColumn) {
```

File: src/Schema/PostgreSQLSchemaManager.php (hunk 4 above)
Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
        $results                 = $this->_conn->executeQuery(<<<'SQL'
```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 17]
```diff
@@ -320,6 +320,34 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
     }
 
+    /**
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
+    {
+        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]:
```suggestion
        $wrappedConnection = $this->connection->getWrappedConnection();
        assert($wrappedConnection instanceof ServerInfoAwareConnection);
        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 18]
```diff
@@ -610,13 +610,48 @@ protected function selectTableNames(string $databaseName): Result
...
+        $supportsGeneratedColumn = $results->fetchOne();
+
+        $fragmentDefaultValueSQL = <<<'SQL'
+             SELECT pg_get_expr(adbin, adrelid)
+             FROM pg_attrdef
+             WHERE c.oid = pg_attrdef.adrelid
+                AND pg_attrdef.adnum=a.attnum
+        SQL;
+
+        if ($supportsGeneratedColumn) {
```
Comment (allan-simon) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
        if ($supportsGeneratedColumn) {

```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 19]
```diff
@@ -320,6 +320,36 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
+             self::markTestSkipped('Manually setting the Oid is not supported in Postgres 11 and earlier');
+        }
+
+        $table = new Table('ddc6198_generated_always_as');
+        $table->addColumn('id', Types::INTEGER);
+        $table->addColumn(
+            'idIsOdd',
+            Types::BOOLEAN,
+            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED'],
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]:
```suggestion
            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED', 'nullable' => false],
```

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 20]
```diff
@@ -320,6 +320,36 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
+        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
+             self::markTestSkipped('Manually setting the Oid is not supported in Postgres 11 and earlier');
+        }
+
+        $table = new Table('ddc6198_generated_always_as');
+        $table->addColumn('id', Types::INTEGER);
+        $table->addColumn(
+            'idIsOdd',
+            Types::BOOLEAN,
+            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED', 'nullable' => false],
```
Comment (allan-simon) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]:
```suggestion
            ['columnDefinition' => 'boolean GENERATED ALWAYS AS (id % 2 = 1) STORED', 'notNull' => true],
```

**Comment by allan-simon** [comment]
Ok I've finally been able to setup the CI locally for postgresql and correct the coding style 

so now I'm pretty sure all will be green :)

File: src/Schema/PostgreSQLSchemaManager.php [hunk 21]
```diff
@@ -610,13 +610,49 @@ protected function selectTableNames(string $databaseName): Result
...
+        // feature detection: if attrgenerated exists it means we are
+        // in a postgreSQL version supporting GENERATED columns
+        // see https://pgpedia.info/g/generated-column.html#implementation
+        $results                 = $this->_conn->executeQuery(<<<'SQL'
+            SELECT true
+            FROM information_schema.columns
+            WHERE table_name = 'pg_attribute'
+                AND column_name = 'attgenerated';
+        SQL);
+        $supportsGeneratedColumn = $results->fetchOne();
```
Comment (derrabus) [inline src/Schema/PostgreSQLSchemaManager.php]: We usually don't do this kind of feature detection. We use the platform class hierarchy to deal with functionality that is not available on all versions of a database.

**Review by derrabus — CHANGES_REQUESTED** [review]

File: src/Schema/PostgreSQLSchemaManager.php (hunk 21 above)
Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: Ok no problem

So you prefer I   introduce a postgresqlplatfrom120 class ?

Comment (derrabus) [reply src/Schema/PostgreSQLSchemaManager.php]: Absolutely, yes!

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: @derrabus  done !

File: src/Schema/PostgreSQLSchemaManager.php [hunk 22]
```diff
@@ -610,13 +611,38 @@ protected function selectTableNames(string $databaseName): Result
...
     protected function selectTableColumns(string $databaseName, ?string $tableName = null): Result
     {
+        $fragmentDefaultValueSQL = <<<'SQL'
+             SELECT pg_get_expr(adbin, adrelid)
+             FROM pg_attrdef
+             WHERE c.oid = pg_attrdef.adrelid
+                AND pg_attrdef.adnum=a.attnum
+        SQL;
+
+        if ($this->_platform instanceof PostgreSQL120Platform) {
```
Comment (derrabus) [inline src/Schema/PostgreSQLSchemaManager.php]: Everything inside this `if` should be moved inside `PostgreSQL120Platform`. We should not need to perform any `instanceof` checks here.

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: fair enough

**Comment by allan-simon** [comment]
@derrabus  I see there's still some changes requested in this PR, but normally I've adressed everything ? Is there's something you're waiting from me ? 

(I don't mean to push you, if it's just a "I didn't have time yet to check it" , no worry I'll way :blush:  , it's just I'm suddenly thinking "maybe he's the one waiting for me" ^^" )

**Comment by derrabus** [comment]
No, I'm aware that the ball's in my court here. 😓

File: src/Platforms/PostgreSQLPlatform.php [hunk 23]
```diff
@@ -1186,6 +1186,21 @@ public function getTruncateTableSQL($tableName, $cascade = false)
         return $sql;
     }
 
+    /**
+     * Get the snippet used to retrieve the default value for a given column
+     *
+     * @return string
+     */
+    public function getDefaultColumnValueSQLSnippet()
```
Comment (derrabus) [inline src/Platforms/PostgreSQLPlatform.php]:
```suggestion
     */
    public function getDefaultColumnValueSQLSnippet(): string
```

File: src/Platforms/PostgreSQL120Platform.php [hunk 24]
```diff
@@ -0,0 +1,33 @@
...
+
+/**
+ * Provides the behavior, features and SQL dialect of the PostgreSQL 10.0 database platform.
+ */
+class PostgreSQL120Platform extends PostgreSQL100Platform
+{
+    /**
+     * {@inheritDoc}
+     */
+    public function getDefaultColumnValueSQLSnippet()
```
Comment (derrabus) [inline src/Platforms/PostgreSQL120Platform.php]:
```suggestion
    public function getDefaultColumnValueSQLSnippet(): string
```

File: src/Platforms/PostgreSQL120Platform.php [hunk 25]
```diff
@@ -0,0 +1,33 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Doctrine\DBAL\Platforms;
+
+/**
+ * Provides the behavior, features and SQL dialect of the PostgreSQL 10.0 database platform.
```
Comment (derrabus) [inline src/Platforms/PostgreSQL120Platform.php]:
```suggestion
 * Provides the behavior, features and SQL dialect of the PostgreSQL 12.0 database platform.
```

🙃

File: src/Schema/PostgreSQLSchemaManager.php (hunk 1 above)
Comment (derrabus) [reply src/Schema/PostgreSQLSchemaManager.php]: This is fine.

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 26]
```diff
@@ -320,6 +320,36 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
+    {
+        $wrappedConnection = $this->connection->getWrappedConnection();
+        assert($wrappedConnection instanceof ServerInfoAwareConnection);
+        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
+             self::markTestSkipped('Manually setting the Oid is not supported in Postgres 11 and earlier');
```
Comment (derrabus) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: Isn't this test about generated columns?

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 27]
```diff
@@ -320,6 +320,36 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
+    /**
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
+    {
+        $wrappedConnection = $this->connection->getWrappedConnection();
+        assert($wrappedConnection instanceof ServerInfoAwareConnection);
+        if (version_compare($wrappedConnection->getServerVersion(), '12.0', '<')) {
```
Comment (derrabus) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: Now that you have a dedicated platform for version 12, you can check the type of `$this->connection->getDatabasePlatform()` instead.

**Review by derrabus — CHANGES_REQUESTED** [review]

File: src/Platforms/PostgreSQLPlatform.php (hunk 23 above)
Comment (allan-simon) [reply src/Platforms/PostgreSQLPlatform.php]: that's the only methods with type hinting ? but ok

File: src/Platforms/PostgreSQL120Platform.php (hunk 25 above)
Comment (allan-simon) [reply src/Platforms/PostgreSQL120Platform.php]: oopsie

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php (hunk 26 above)
Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: indeed, a copy paste error

File: src/Platforms/PostgreSQLPlatform.php (hunk 23 above)
Comment (derrabus) [reply src/Platforms/PostgreSQLPlatform.php]: Yes, because most of them come from a time when PHP didn't have return types. Adding native types to a class that is supposed to be extended in userland is a breaking change. But that should not stop us from using native return types on brand new methods.

Comment (allan-simon) [reply src/Platforms/PostgreSQLPlatform.php]: fair enough, I've applied your suggestion and corrected the remarks.

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php (hunk 27 above)
Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: changed

**Comment by allan-simon** [comment]
repushed (I forgot to run phpcs locally) and squashed, the previous CI was only failing on IBM DB2 test, but it seems to me it was a flaky test

**Comment by allan-simon** [comment]
@derrabus  the fail seems to be a flaky test , can you relaunch them ?

File: tests/Functional/Schema/PostgreSQLSchemaManagerTest.php [hunk 28]
```diff
@@ -320,6 +321,36 @@ public function testBooleanDefault(callable $comparatorFactory): void
...
 
+    /**
+     * @param callable(AbstractSchemaManager):Comparator $comparatorFactory
+     *
+     * @dataProvider \Doctrine\DBAL\Tests\Functional\Schema\ComparatorTestUtils::comparatorProvider
+     */
+    public function testGeneratedColumn(callable $comparatorFactory): void
+    {
+        $wrappedConnection = $this->connection->getWrappedConnection();
+        assert($wrappedConnection instanceof ServerInfoAwareConnection);
```
Comment (derrabus) [inline tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: We don't need this `assert()`, do we?

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: I ve taken this from somewehere else in the codebase so I will remove it if you dont want it

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: I know some people add this because it helps phpstan or their ide code completion to not complain if later you use a method not present in the interface  so I admitted if was the case here

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: As people then deactivate assert in prod

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: as I didn't get any answer I've removed it

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: @derrabus  any chance for it to get merged as a christmas present ? :santa:  

I think on my side to have adressed all your comments and the tests are as green as a christmas tree :)

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: @derrabus sorry to bother you, I know what it's like to be pinged, but is there something blocking or that I can do to ease the burden of review ?

I've found some other (more blocking) bug related to generated column and I would like to have this PR merged before pushing anything more :)

Comment (allan-simon) [reply tests/Functional/Schema/PostgreSQLSchemaManagerTest.php]: Friendly reminder that  this PR is still an issue today :)

File: src/Platforms/PostgreSQL120Platform.php [hunk 29]
```diff
@@ -0,0 +1,30 @@
...
+namespace Doctrine\DBAL\Platforms;
+
+/**
+ * Provides the behavior, features and SQL dialect of the PostgreSQL 12.0 database platform.
+ */
+class PostgreSQL120Platform extends PostgreSQL100Platform
+{
+    public function getDefaultColumnValueSQLSnippet(): string
+    {
+        // in case of GENERATED ALWAYS AS ( foobar) STORED column (added in PostgreSQL 12.0)
```
Comment (greg0ire) [inline src/Platforms/PostgreSQL120Platform.php]:
```suggestion
        // in case of GENERATED ALWAYS AS (foobar) STORED column (added in PostgreSQL 12.0)
```

File: src/Platforms/PostgreSQL120Platform.php [hunk 30]
```diff
@@ -0,0 +1,30 @@
...
+        // postgreSQL's pg_get_expr(adbin, adrelid) will return the 'foobar' part
```
Comment (greg0ire) [inline src/Platforms/PostgreSQL120Platform.php]:
```suggestion
        // PostgreSQL's pg_get_expr(adbin, adrelid) will return the 'foobar' part
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 31]
```diff
@@ -632,11 +634,7 @@ protected function selectTableColumns(string $databaseName, ?string $tableName =
                 AND pg_index.indkey[0] = a.attnum
                 AND pg_index.indisprimary = 't'
             ) AS pri,
-            (SELECT pg_get_expr(adbin, adrelid)
-             FROM pg_attrdef
-             WHERE c.oid = pg_attrdef.adrelid
-                AND pg_attrdef.adnum=a.attnum
-            ) AS default,
+            ($fragmentDefaultValueSQL) AS default,
```
Comment (greg0ire) [inline src/Schema/PostgreSQLSchemaManager.php]: Why does Codecov say hat line is not covered? Are you sure the new test is executed on the CI?

File: src/Schema/PostgreSQLSchemaManager.php [hunk 32]
```diff
@@ -616,7 +616,9 @@ protected function selectTableColumns(string $databaseName, ?string $tableName =
             $sql .= ' c.relname AS table_name, n.nspname AS schema_name,';
         }
 
-        $sql .= <<<'SQL'
+        $fragmentDefaultValueSQL = $this->_platform->getDefaultColumnValueSQLSnippet();
```
Comment (greg0ire) [inline src/Schema/PostgreSQLSchemaManager.php]: Up for debate, but I think I'd rather resort to `sprintf` here, partly because it means no extra variable is required.

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: I agree to disagree, if you can do a suggestion I will gladly accept it

File: src/Schema/PostgreSQLSchemaManager.php [hunk 33]
```diff
@@ -616,7 +616,9 @@ protected function selectTableColumns(string $databaseName, ?string $tableName =
...
+
+        $sql .= <<<SQL
```
Comment (greg0ire) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
        $fragmentDefaultValueSQL = $this->_platform->getDefaultColumnValueSQLSnippet();

        $sql .= sprintf(<<<'SQL'
```

File: src/Schema/PostgreSQLSchemaManager.php (hunk 31 above)
Comment (greg0ire) [inline src/Schema/PostgreSQLSchemaManager.php]:
```suggestion
            (%s) AS default,
```

File: src/Schema/PostgreSQLSchemaManager.php [hunk 34]
```diff
@@ -632,11 +634,7 @@ protected function selectTableColumns(string $databaseName, ?string $tableName =
...
             ) AS pri,
-            (SELECT pg_get_expr(adbin, adrelid)
-             FROM pg_attrdef
-             WHERE c.oid = pg_attrdef.adrelid
-                AND pg_attrdef.adnum=a.attnum
-            ) AS default,
+            ($fragmentDefaultValueSQL) AS default,
             (SELECT pg_description.description
                 FROM pg_description WHERE pg_description.objoid = c.oid AND a.attnum = pg_description.objsubid
             ) AS comment
```
Comment (greg0ire) [inline src/Schema/PostgreSQLSchemaManager.php:638]: To close the sprintf, I need to do a suggestion on line 652, which is not part of the diff, so that won't work.

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php:638]: erf I will do to rebuild a environment to check that (and verify I don't break coding style etc. ) :( 

if the burden is on me can I let you change that in a follow-up PR ? (as I think it's purely a subjective change)

File: src/Schema/PostgreSQLSchemaManager.php (hunk 31 above)
Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: let me check in the history of CI pipeline but I do remember to see one failed because a previous version had a bug

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: https://github.com/doctrine/dbal/runs/22902499257 say 100% of my patch is test covered (if i open the details I got a blank page on firefox and chrome)  ?

File: src/Schema/PostgreSQLSchemaManager.php (hunk 34 above)
Comment (greg0ire) [reply src/Schema/PostgreSQLSchemaManager.php:638]: As a maintainer, I should be able to push a commit to your branch, hang on.

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php:638]: ah yes if you can do so , please do, I don't mind :)

File: src/Schema/PostgreSQLSchemaManager.php (hunk 31 above)
Comment (greg0ire) [reply src/Schema/PostgreSQLSchemaManager.php]: After that last push, it no longer complains, so I think this must be fine.

Comment (allan-simon) [reply src/Schema/PostgreSQLSchemaManager.php]: does it mean we're good for merging  ? :)

**Comment by greg0ire** [comment]
> So DBAL has been considering has ALWAYS meaning it contains its default

Is this sentence broken? I don't understand it.

**Comment by allan-simon** [comment]
> > So DBAL has been considering has ALWAYS meaning it contains its default
> 
> Is this sentence broken? I don't understand it.

yes , sorry 

I meant 

DBAL was interpreting "pg_get_expr(adbin, adrelid) returns something"  as  meaning "the value returned is the default value of the column "  while it's a more generic "definition value" which can be the default value , but can also be other things (like the generated column expression ) 


I think the confusion was that postgresql uses the abbreviated form "pg_attrdef"  and one could have interpreted that as "postgresql attribute default"  whereas it actually means "postgresql attribute definition"

**Review by greg0ire — DISMISSED** [review]

**Comment by allan-simon** [comment]
@derrabus friendly reminder this PR exists , tell me if you need anything from me :)   I can make myself available for a pair review call if you want.

**Review by derrabus — APPROVED** [review]

**Comment by allan-simon** [comment]
thanks a lot !
