### PR TITLE
Switched from ibmcom/db2express-c to ibmcom/db2

### LINKED ISSUE #3618: Travic CI tests are failing because ibmcom/db2express-c docker is gone
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | master

#### Summary

Travis-CI tests are failing due to docker ibmcom/db2express-c being removed.

#### Current behaviour

```
sudo docker pull ibmcom/db2express-c:10.5.0.5-3.10.0
Error response from daemon: pull access denied for ibmcom/db2express-c, repository does not exist or may require 'docker login'
The command "bash ./tests/travis/install-db2.sh" failed and exited with 1 during .
```

#### How to reproduce

Just commit and that commit or PR will have a Travis CI failure.

#### Expected behaviour

Tests for db2 should probably use https://hub.docker.com/r/ibmcom/db2 instead.

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

Fixes #3618.

### CODE REVIEW

File: tests/travis/install-db2.sh [hunk 1]
```diff
@@ -4,19 +4,20 @@ set -ex
...
     -e DB2INST1_PASSWORD=Doctrine2018 \
     -e LICENSE=accept \
+    -e DBNAME=doctrine \
+    -v /tmp/doctrine-init.sh:/var/custom/doctrine-init.sh:ro \
     --name db2 \
-    ibmcom/db2express-c:10.5.0.5-3.10.0 \
-    db2start
-
-sleep 15
+    --privileged=true \
```
Comment (lcobucci) [inline tests/travis/install-db2.sh]: Is it really necessary to have this flag enabled? Not a big deal but it's usually recommended to give the minimum permissions to the container.

File: tests/travis/install-db2.sh [hunk 2]
```diff
@@ -4,19 +4,20 @@ set -ex
...
+    ibmcom/db2
```
Comment (lcobucci) [inline tests/travis/install-db2.sh]: Can we use a tag here, other than "latest" (sure)? Otherwise we might rely on different images if they change things.

File: tests/travis/install-db2.sh [hunk 3]
```diff
@@ -4,19 +4,20 @@ set -ex
...
 
-sudo docker exec db2 su - db2inst1 -c \
-    'db2 CREATE DB doctrine && db2 CONNECT TO doctrine && db2 CREATE USER TEMPORARY TABLESPACE doctrine_tbsp PAGESIZE 4 K'
+sudo docker logs -f db2 | sed '/(*) Setup has completed./ q'
```
Comment (lcobucci) [inline tests/travis/install-db2.sh]: Is it possible to use `dockerize` instead?

File: tests/travis/install-db2.sh (hunk 1 above)
Comment (morozov) [reply tests/travis/install-db2.sh]: Yes, it's necessary.

File: tests/travis/install-db2.sh (hunk 2 above)
Comment (morozov) [reply tests/travis/install-db2.sh]: Yeah, let's use a tag.

File: tests/travis/install-db2.sh (hunk 3 above)
Comment (morozov) [reply tests/travis/install-db2.sh]: I haven't used it before. What would be the benefit and what would the command look like?

Comment (morozov) [reply tests/travis/install-db2.sh]: The [documentation](https://hub.docker.com/r/ibmcom/db2#quick-start) says:

> To confirm Db2 container is ready, in the logs we will see the message **Setup has completed**.

While we can ping the container until it's ready, but our experience with MySQL shows that often it's not reliable.

**Review by lcobucci — APPROVED** [review]
