### PR TITLE
Retain SQLite column position when renaming or altering

### LINKED ISSUE #4775: SQLite platform changes the position of the renamed or altered column
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.x

#### Summary

If a column is renamed or altered, and it's not part of the PK or an FK, it's moved to the end of the table.

#### How to reproduce

1. Renaming the column
   ```php
   $table = new Table('test');
   $table->addColumn('c1', 'string');
   $table->addColumn('c2', 'integer');

   $sm = $connection->getSchemaManager();
   $sm->dropAndCreateTable($table);

   $table->dropColumn('c1')
       ->addColumn('c1_x', 'string');

   $comparator = new Comparator();
   $diff = $comparator->diffTable($sm->listTableDetails('test'), $table);
   var_dump(array_keys($diff->renamedColumns));

   // The dropColumn() and addColumn() above have been correctly determined as a rename
   //
   // array(1) {
   //  [0] =>
   //  string(2) "c1"
   // }

   $sm->alterTable($diff);
   $table = $sm->listTableDetails('test');
   var_dump(array_keys($table->getColumns()));

   // The column order is incorrect
   //
   // array(2) {
   //   [0] =>
   //   string(2) "c2"
   //   [1] =>
   //   string(4) "c1_x"
   // }
   ```

2. Altering the column
   ```php
   $table = new Table('test');
   $table->addColumn('c1', 'string');
   $table->addColumn('c2', 'integer');

   $sm = $connection->getSchemaManager();
   $sm->dropAndCreateTable($table);

   $table->getColumn('c1')
       ->setType(Type::getType(Types::INTEGER));

   $comparator = new Comparator();
   $diff = $comparator->diffTable($sm->listTableDetails('test'), $table);
   $sm->alterTable($diff);

   $table = $sm->listTableDetails('test');
   var_dump(array_keys($table->getColumns()));

   // The column order is incorrect
   //
   // array(2) {
   //   [0] =>
   //   string(2) "c2"
   //   [1] =>
   //   string(4) "c1"
   // }
   ```

#### Expected behaviour

The column retains its position within the table.

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #4775

### CODE REVIEW

File: tests/Platforms/AbstractPlatformTestCase.php [hunk 1]
```diff
@@ -777,9 +777,12 @@ public function testGetCreateSchemaSQL(): void
 
     public function testAlterTableChangeQuotedColumn(): void
     {
-        $tableDiff                        = new TableDiff('mytable');
-        $tableDiff->fromTable             = new Table('mytable');
-        $tableDiff->changedColumns['foo'] = new ColumnDiff(
+        $table = new Table('mytable');
+        $table->addColumn('select', 'integer');
```
Comment (morozov) [inline tests/Platforms/AbstractPlatformTestCase.php:781]: Although this change is necessary for the test to pass, it doesn't identify a breaking change. The original test is invalid since it attempts to alter a non-existing column producing an invalid SQL migration.

**Review by SenseException — APPROVED** [review]
