### PR TITLE
Consider CASE_LOWER being equal to 0 in portability middleware

### LINKED ISSUE #5231: Connection::PORTABILITY_FIX_CASE specified alone doesn't enable case conversion
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.3.x

```php
function test(int $mode): void {
    $config = new Configuration();
    $config->setMiddlewares([
        new Portability\Middleware($mode, ColumnCase::LOWER)
    ]);

    $connection = DriverManager::getConnection([
        'driver'   => 'oci8',
        'host'     => 'localhost',
        'user'     => 'system',
        'password' => 'oracle',
        'dbname'   => 'XE',
    ], $config);

    var_dump($connection->fetchAssociative("SELECT 'foo' AS BAR FROM DUAL"));
}

// doesn't work
test(Portability\Connection::PORTABILITY_FIX_CASE);
// array(1) {
//   'BAR' =>
//   string(3) "foo"
// }

// works
test(Portability\Connection::PORTABILITY_ALL);
// array(1) {
//   'bar' =>
//   string(3) "foo"
// }
```

It works as follows:
1. `ColumnCase::LOWER` is converted to `CASE_LOWER`:
   https://github.com/doctrine/dbal/blob/d9f969b366fcd4c7def89372b9c198edb2cc9fe5/src/Portability/Driver.php#L59
2. If only the case conversion is enabled and the case is not specified, the driver doesn't create a wrapper connection:
   https://github.com/doctrine/dbal/blob/d9f969b366fcd4c7def89372b9c198edb2cc9fe5/src/Portability/Driver.php#L66-L67
3. The problem is that `CASE_LOWER` is `0`.

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #5231.

While refactoring the test, I removed `testConnFetchMode()` since it looked identical to `testFullFetchMode()`.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

File: tests/Functional/PortabilityTest.php [hunk 1]
```diff
@@ -79,22 +45,29 @@ public function testFullFetchMode(): void
         }
     }
 
-    public function testConnFetchMode(): void
+    /**
+     * @param array{int, list<string>} $expected
```
Comment (greg0ire) [inline tests/Functional/PortabilityTest.php:49]: Noticed during https://github.com/doctrine/dbal/pull/5252: this should be `list<string>`. it seems that PHPStan detects more things on 4.x
