### PR TITLE
Fix MariaDB fetching of default table character-set

### LINKED ISSUE #6361: COLLATION_CHARACTER_SET_APPLICABILITY.COLLATION_NAME vs MariaDB FULL_COLLATION_NAME
In recent MariaDB version the following will not succeed (resp. always yields an empty result set):

https://github.com/doctrine/dbal/blob/7fb00fdf7091a3ab0a4b6d0eed12170b4c7c2aa8/src/Schema/MySQLSchemaManager.php#L463-L474

The reason is, that `CCSA.collation_name` in recent MariaDB versions (tested version: 10.11.7) only contains the short collation name without prepended character set, while `TABLES.table_collation` contains the *long* table name. For example, in the case of the newly introduced `utf8mb4_uca1400_ai_ci` the corresponding row from `COLLATION_CHARACTER_SET_APPLICABILITY` is (CSV export):

```
"COLLATION_NAME","CHARACTER_SET_NAME","FULL_COLLATION_NAME","ID","IS_DEFAULT"
"uca1400_ai_ci","utf8mb4","utf8mb4_uca1400_ai_ci","2304",
```

while the `TABLES.TABLE_COLLATION` holds the full collation name `utf8mb4_uca1400_ai_ci`.

It also seems that this is a recent change in MariaDB; one Ubuntu "Jammy" system I am using runs MariaDB 10.6.16 which only has the `COLLATION_NAME` and `CHARACTER_SET_NAME` in that table, and the collation name is the full name with the character set prepended.

### PR DESCRIPTION
**Pull request by grooverdan**
|      Q       |   A
|------------- | -----------
| Type         | bug
| Fixed issues | #6361

#### Summary

From MariaDB-10.10.1, where uca1400 was added, the information_schema.COLLATION_CHARACTER_SET_APPLICABILITY was extended to have FULL_COLLATION_NAME which corresponds to the information_schema.TABLES.TABLE_COLLATION value.

Executable comment syntax is used to limited to the applicable versions.

To preserve compatibility with older MariaDB versions, and MySQL versions where the previous COLLATION_NAME was the match is left as a JOIN criteria. In new MariaDB versions this won't result in an extra row match.

Closes: #6361

The lack of this fix did case the CI test to fail with a MariaDB-11.0+ container:

```
1) Doctrine\DBAL\Tests\Functional\Schema\MySQLSchemaManagerTest::testEnsureTableWithoutOptionsAreReflectedInMetadata
Undefined array key "engine"

/home/runner/work/dbal/dbal/src/Schema/Table.php:927
/home/runner/work/dbal/dbal/tests/Functional/Schema/MySQLSchemaManagerTest.php:550
```

With this fix all version of MySQL and MariaDB (even those new ones soon to be in a different PR) will pass like: https://github.com/grooverdan/dbal/actions/runs/9412110648/job/25926481038

### CODE REVIEW

**Comment by grooverdan** [comment]
SQL example:
```
MariaDB [test]> select version();
+----------------+
| version()      |
+----------------+
| 11.5.2-MariaDB |
+----------------+
1 row in set (0.001 sec)


MariaDB [test]> create table t (c varchar(30)) charset 'utf32' collate 'uca1400_ai_ci';
Query OK, 0 rows affected (0.002 sec)

MariaDB [test]> SELECT t.TABLE_NAME,            t.ENGINE,            t.AUTO_INCREMENT,            t.TABLE_COMMENT,            t.CREATE_OPTIONS,            t.TABLE_COLLATION,            ccsa.CHARACTER_SET_NAME       FROM information_schema.TABLES t         INNER JOIN information_schema.COLLATION_CHARACTER_SET_APPLICABILITY ccsa             ON /*M!101001 ccsa.FULL_COLLATION_NAME = t.TABLE_COLLATION OR */ COLLATION_NAME = t.TABLE_COLLATION WHERE t.TABLE_NAME='t';
+------------+--------+----------------+---------------+----------------+---------------------+--------------------+
| TABLE_NAME | ENGINE | AUTO_INCREMENT | TABLE_COMMENT | CREATE_OPTIONS | TABLE_COLLATION     | CHARACTER_SET_NAME |
+------------+--------+----------------+---------------+----------------+---------------------+--------------------+
| t          | InnoDB |           NULL |               |                | utf32_uca1400_ai_ci | utf32              |
+------------+--------+----------------+---------------+----------------+---------------------+--------------------+
````

File: src/Schema/MySQLSchemaManager.php [hunk 1]
```diff
@@ -567,7 +572,8 @@ protected function fetchTableOptionsByTable(string $databaseName, ?string $table
            ccsa.CHARACTER_SET_NAME
       FROM information_schema.TABLES t
         INNER JOIN information_schema.COLLATION_CHARACTER_SET_APPLICABILITY ccsa
-            ON ccsa.COLLATION_NAME = t.TABLE_COLLATION
+	     ON /*M!101001 ccsa.FULL_COLLATION_NAME = t.TABLE_COLLATION OR */
+               ccsa.COLLATION_NAME = t.TABLE_COLLATION
```
Comment (derrabus) [inline src/Schema/MySQLSchemaManager.php:576]: I'd like to avoid version conditionals in SQL. We have our platform class hierarchy for this purpose.

I'll accept this change as a hotfix for MariaDB 11.4 on the 3.8.x branch. Can you work on a PR for 3.9.x that moves the SQL statement to `AbstractMySQLPlatform` and that introduces a new platform class for MariaDB 10.10 which overrides the generated SQL?

**Review by derrabus — APPROVED** [review]
