### PR TITLE
Don't Set a Default Value on PostgreSQL SERIAL Fields

### LINKED ISSUE #2906: Cannot Generate [BIG]SERIAL Columns Without a Default or NOT NULL
The [postgres docs](https://www.postgresql.org/docs/current/static/ddl-default.html) have an example of a serial column without a `NOT NULL` declaration or default value.

```sql
CREATE TABLE example (
    colname SERIAL,
    -- ...
);
```
This `CREATE TABLE` can't be done in DBAL schema APIs.

Specifying `notnull` to `false` in the column options adds a `DEFAULT NULL` to the column which errors with...

> Syntax error: 7 ERROR:  multiple default values specified for column

Anyway, I'd expect to be able to do something like this:

```php
$table = new \Doctrine\DBAL\Schema\Table('example');
$table->addColumn('colname', 'integer', [
  'autoincrement' => true,
  'notnull' => false,
]);
```

To generate the example SQL above, without a `DEFAULT NULL` in there.

There's a work around for this (setting `default => "nextval('example_colname_seq')"`), but the point of having the serial type is the shorthand and avoiding the sequence stuff. Also ties the schema to postgres rather than being more generic.

### PR DESCRIPTION
**Pull request by chrisguitarguy**
Specifically when `'notnull' => false` is in the column options.

Right now DBAL adds a `DEFAULT NULL` when that happens. `[BIG]SERIAL` fields already have a default value and adding the `DEFAULT NULL` produces an error.

Fixes #2906

Not sure if the functional tests here are necessary, but it seemed like a good idea.

### CODE REVIEW

**Comment by chrisguitarguy** [comment]
The scrutenizer failure here seems unrelated, just picked up because I changed a file with a pre-existing issue: https://scrutinizer-ci.com/g/doctrine/dbal/inspections/6801d978-162b-436c-a2e2-c1315ea461c5/issues/files/tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php [hunk 1]
```diff
@@ -1186,4 +1188,23 @@ public function quoteStringLiteral($str)
 
         return parent::quoteStringLiteral($str);
     }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function getDefaultValueDeclarationSQL($field)
+    {
+        if (self::isSerialField($field) && empty($field['notnull'])) {
```
Comment (lcobucci) [inline lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: This condition will result to `true` when `$field['notnull']` doesn't exist, is this the expected behaviour? I'd suggest to be more explicit about that, like `$field['notnull'] ?? false === false`.

Comment (lcobucci) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: I know that we use `empty()` on the parent method, but we didn't have these features back then.

Comment (lcobucci) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Is there any reason to leave the `empty($field['notnull'])` out of the method?

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php [hunk 2]
```diff
@@ -1186,4 +1188,23 @@ public function quoteStringLiteral($str)
...
+            return '';
+        }
+
+        return parent::getDefaultValueDeclarationSQL($field);
+    }
+
+    private static function isSerialField($field)
```
Comment (lcobucci) [inline lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Missing type declarations (parameters and return)

Comment (lcobucci) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Also, any reason to make this static?

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php [hunk 3]
```diff
@@ -1186,4 +1188,23 @@ public function quoteStringLiteral($str)
...
+    {
+        return !empty($field['autoincrement']) && isset($field['type']) && (
```
Comment (lcobucci) [inline lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Same comments about being explicit here (with `empty()`)

File: tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php [hunk 4]
```diff
@@ -419,6 +419,34 @@ public function testListNegativeColumnDefaultValue()
...
+    {
+        return [
+            ['integer'],
+            ['bigint'],
+        ];
+    }
+
+    /**
+     * @dataProvider serialTypes
+     * @group https://github.com/doctrine/dbal/issues/2906
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php]: Please use only `2906` as group

File: tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php [hunk 5]
```diff
@@ -144,6 +144,30 @@ public function testGenerateTableWithAutoincrement()
...
+    {
+        return [
+            ['integer', 'SERIAL'],
+            ['bigint', 'BIGSERIAL'],
+        ];
+    }
+
+    /**
+     * @dataProvider serialTypes
+     * @group https://github.com/doctrine/dbal/issues/2906
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php]: Please use only `2906` as group

File: tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php [hunk 6]
```diff
@@ -419,6 +419,34 @@ public function testListNegativeColumnDefaultValue()
         self::assertEquals(-1.1, $columns['col_decimal']->getDefault());
         self::assertEquals('(-1)', $columns['col_string']->getDefault());
     }
+
+    public static function serialTypes()
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php]: Add ` : array` as return type

File: tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php [hunk 7]
```diff
@@ -419,6 +419,34 @@ public function testListNegativeColumnDefaultValue()
...
+            ['integer'],
+            ['bigint'],
+        ];
+    }
+
+    /**
+     * @dataProvider serialTypes
+     * @group https://github.com/doctrine/dbal/issues/2906
+     */
+    public function testAutoIncrementCreatesSerialDataTypesWithoutADefaultValueWheNotNullIsFalse($type)
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php]: `public function testAutoIncrementCreatesSerialDataTypesWithoutADefaultValueWheNotNullIsFalse(string $type) : void`

File: tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php [hunk 8]
```diff
@@ -419,6 +419,34 @@ public function testListNegativeColumnDefaultValue()
...
+        $table->addColumn('id', $type, [
+            'autoincrement' => true,
+            'notnull' => false,
+        ]);
+
+        $this->_sm->dropAndCreateTable($table);
+
+        $columns = $this->_sm->listTableColumns($tableName);
+
+        $this->assertNull($columns['id']->getDefault());
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php]: Please use `self::assert*` instead

File: tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php [hunk 9]
```diff
@@ -144,6 +144,30 @@ public function testGenerateTableWithAutoincrement()
         self::assertEquals(array('CREATE TABLE autoinc_table (id SERIAL NOT NULL)'), $this->_platform->getCreateTableSQL($table));
     }
 
+    public static function serialTypes()
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php]: Add ` : array` as return type

File: tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php [hunk 10]
```diff
@@ -144,6 +144,30 @@ public function testGenerateTableWithAutoincrement()
...
+            ['integer', 'SERIAL'],
+            ['bigint', 'BIGSERIAL'],
+        ];
+    }
+
+    /**
+     * @dataProvider serialTypes
+     * @group https://github.com/doctrine/dbal/issues/2906
+     */
+    public function testGenerateTableWithAutoincrementAndNotNullFalseDoesNotSetADefaultValueOnSerialFields($type, $definition)
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php]: Please add type declarations here

File: tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php [hunk 11]
```diff
@@ -144,6 +144,30 @@ public function testGenerateTableWithAutoincrement()
...
+    {
+        $table = new \Doctrine\DBAL\Schema\Table('autoinc_table_notnull');
+        $column = $table->addColumn('id', $type);
+        $column->setAutoIncrement(true);
+        $column->setNotNull(false);
+
+        $sql = $this->_platform->getCreateTableSQL($table);
+
+        self::assertEquals(array("CREATE TABLE autoinc_table_notnull (id $definition)"), $sql);
```
Comment (lcobucci) [inline tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php]: Please use short-array notation

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php (hunk 1 above)
Comment (lcobucci) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Also do we have unit tests covering all the paths?

**Review by lcobucci — CHANGES_REQUESTED** [review]
Nice job, great commit organisation too.

I got some suggestions, questions, and nitpicking - obviously.

Can you please make sure that the code you're adding follows our standards? `phpcs` is already configured - with `phpcbf` - and can be helpful (I've tried to make it mandatory and simplify the lives of new contributors on #2849 but @Ocramius said NOPE 😂).

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php (hunk 2 above)
Comment (chrisguitarguy) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: > Missing type declarations (parameters and return)

Left out the parameter type declaration because the method from which this is called doesn't have one either (`getDefaultValueDeclarationSQL`). `$field` theoretically should be `array`? Happy to add the type declaration for `$field`, but that was the reason I didn't.

Definitely should have the return type!

> Also, any reason to make this static?

Habit of my, sorry. I tend to make "pure" utility functions static -- since nothing from the platform's instance state is required, I made it static. Want me to make it non-static?

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php (hunk 1 above)
Comment (chrisguitarguy) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: > Is there any reason to leave the empty($field['notnull']) out of the method?

Yep. `nonnull` doesn't have anything to do with being a `SERIAL` field. Also: this is perfectly okay: `whatever SERIAL NOT NULL`. So if someone wants to make sure the field is `notnull` they are free to do so.

> This condition will result to true when $field['notnull'] doesn't exist, is this the expected behaviour?

`$field['notnull']` missing is the same as `$field['notnull'] = false` yeah? I think you're right though, should be more explicit.

> Also do we have unit tests covering all the paths?

I need to add some for `whatever SERIAL NOT NULL` now that I think about it.

Comment (chrisguitarguy) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Okay, coming back to this `notnull` thing. I'm not actually it sure it should get checked at all. Any default value for a serial field is invalid -- they already have defaults built in. Maybe `getDefaultValueDeclarationSQL` should just return its empty string for any `SERIAL` field?

**Comment by chrisguitarguy** [comment]
> phpcs is already configured - with phpcbf - and can be helpful

I did the best I could with this. Find some errors in the tests with aligned equals signs. Running either tool on the whole codebase produces a lot of violations, even running it on the files I edited were 40 or 50 fixes per file.

**Comment by morozov** [comment]
Time for a shameless self-promotion:
```
pull-request doctrine dbal 2907 --standard=vendor/doctrine/coding-standard/lib/Doctrine

FILE: tests/Doctrine/Tests/DBAL/Platforms/AbstractPostgreSqlPlatformTestCase.php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------
 159 | WARNING | Line exceeds 120 characters; contains 147 characters
 175 | WARNING | Line exceeds 120 characters; contains 149 characters
--------------------------------------------------------------------------------
```

@chrisguitarguy, see [morozov/diff-sniffer-pull-request](https://github.com/morozov/diff-sniffer-pull-request) and [morozov/diff-sniffer-pre-commit](https://github.com/morozov/diff-sniffer-pre-commit).

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php (hunk 2 above)
Comment (lcobucci) [reply lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: I got your point. I don't see much difference in this case, since the caller is already in the scope of the instance. I'd keep it non-static here but was just curious 😄

File: lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php [hunk 12]
```diff
@@ -1186,4 +1188,23 @@ public function quoteStringLiteral($str)
...
+    public function getDefaultValueDeclarationSQL($field)
+    {
+        if (self::isSerialField($field)) {
+            return '';
+        }
+
+        return parent::getDefaultValueDeclarationSQL($field);
+    }
+
+    private static function isSerialField($field) : bool
```
Comment (lcobucci) [inline lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php]: Regarding the type, we just don't have the type declaration on `getDefaultValueDeclarationSQL` for historical reasons. Let's add it here too

**Review by lcobucci — CHANGES_REQUESTED** [review]
Great job @chrisguitarguy, just one more thing (apart from what @morozov said).

**Comment by chrisguitarguy** [comment]
Thanks, @morozov, those tools are great!

Updated with the latest requested changes and fixed the PHP CS warnings, @lcobucci.

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@chrisguitarguy merged and backported to 2.6, thanks for your contribution!

**Comment by chrisguitarguy** [comment]
My pleasure, thanks for the support @lcobucci!
