### PR TITLE
[DBAL-2644] Fix fetchAll(PDO::FETCH_COLUMN) on DB2 with Portability wrapper

### LINKED ISSUE #2644: Portability\Statement incorrectly handles fetchAll(PDO::FETCH_COLUMN)
The `Portability\Statement::fixRow()` implementation doesn't take into account that `mixed $row` is not always iterable (particularly in the case if `$fetchMode = PDO::FETCH_COLUMN`).

```php
use Doctrine\DBAL\Portability\Connection;
use Doctrine\DBAL\DriverManager;

$conn = DriverManager::getConnection(array(
    'driver' => 'ibm_db2',
    'wrapperClass' => Connection::class,
    'portability' => Connection::PORTABILITY_FIX_CASE,
    'fetch_case' => PDO::CASE_LOWER,
));

$conn->executeQuery('SELECT id FROM users')
    ->fetchAll(\PDO::FETCH_COLUMN);
```
Produces:
> Warning: Invalid argument supplied for foreach() in vendor/doctrine/dbal/lib/Doctrine/DBAL/Portability/Statement.php on line 203

Besides that, the `Portability\Statement::connect()` implementation forcedly [replaces](https://github.com/doctrine/dbal/commit/daf4f16f597d4b358315ad0099ab200457e0e550#diff-a59fd02c89788e9db9c34b9b2b12b5e6R81) the `portability` value from whatever provided in the connection parameters with `PORTABILITY_DB2` which is inconsistent with the rest of the supported platforms.

### PR DESCRIPTION
**Pull request by morozov**
Fixes #2644:

1. Do not enforce platform-dependent portability settings
2. Properly handle the result of fetchAll(PDO::FETCH_COLUMN)

### CODE REVIEW

File: lib/Doctrine/DBAL/Portability/Statement.php [hunk 1]
```diff
@@ -175,8 +175,20 @@ public function fetchAll($fetchMode = null, $columnIndex = 0)
             return $rows;
         }
 
-        foreach ($rows as $num => $row) {
-            $rows[$num] = $this->fixRow($row, $iterateRow, $fixCase);
+        if ($fetchMode === PDO::FETCH_COLUMN) {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Statement.php]: @morozov can you isolate the contents of the `if` and `else` statements into private methods? Early return preferred

File: lib/Doctrine/DBAL/Portability/Statement.php [hunk 2]
```diff
@@ -175,8 +175,20 @@ public function fetchAll($fetchMode = null, $columnIndex = 0)
...
+            if ($iterateRow) {
+                foreach ($rows as $num => $value) {
+                    if (($this->portability & Connection::PORTABILITY_EMPTY_TO_NULL) && $value === '') {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Statement.php]: The first bitwise expression does not need re-computing within the loop, and should be moved to a variable

File: lib/Doctrine/DBAL/Portability/Statement.php [hunk 3]
```diff
@@ -175,8 +175,20 @@ public function fetchAll($fetchMode = null, $columnIndex = 0)
...
+                        $rows[$num] = null;
+                    } elseif (($this->portability & Connection::PORTABILITY_RTRIM) && is_string($value)) {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Statement.php]: The first bitwise expression does not need re-computing within the loop, and should be moved to a variable

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: lib/Doctrine/DBAL/Portability/Statement.php [hunk 4]
```diff
@@ -169,14 +169,14 @@ public function fetchAll($fetchMode = null, $columnIndex = 0)
...
+        $rTrim = (bool) ($this->portability & Connection::PORTABILITY_RTRIM);
         $fixCase = !is_null($this->case) && ($fetchMode == PDO::FETCH_ASSOC || $fetchMode == PDO::FETCH_BOTH) && ($this->portability & Connection::PORTABILITY_FIX_CASE);
-        if ( ! $iterateRow && !$fixCase) {
-            return $rows;
-        }
 
-        foreach ($rows as $num => $row) {
-            $rows[$num] = $this->fixRow($row, $iterateRow, $fixCase);
+        if ($fetchMode === PDO::FETCH_COLUMN) {
+            $rows = $this->fixColumn($rows, $emptyToNull, $rTrim);
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Statement.php]: return early please

File: lib/Doctrine/DBAL/Portability/Statement.php [hunk 5]
```diff
@@ -169,14 +169,14 @@ public function fetchAll($fetchMode = null, $columnIndex = 0)
...
+        } else {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Statement.php]: No need for `else`

File: lib/Doctrine/DBAL/Portability/Statement.php [hunk 6]
```diff
@@ -213,6 +213,55 @@ protected function fixRow($row, $iterateRow, $fixCase)
...
+     * Fixes column values according to portability settings
+     *
+     * @param mixed[] $values Column values indexed by row number
+     * @param bool $emptyToNull Should empty strings be converted to NULL
+     * @param bool $rTrim Should strings be right-trimmed
+     * @return mixed[]
+     */
+    private function fixColumn(array $values, $emptyToNull, $rTrim)
+    {
+        if (!$emptyToNull && !$rTrim) {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Statement.php]: Isn't it simpler to loop twice, and call two separate methods that do one the `emptyToNull` fixing, and the other the `rTrim` fixing?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: lib/Doctrine/DBAL/Portability/Statement.php (hunk 6 above)
Comment (morozov) [inline lib/Doctrine/DBAL/Portability/Statement.php]: I think ideally (if [performance allows](http://stackoverflow.com/questions/18144782/performance-of-foreach-array-map-with-lambda-and-array-map-with-static-function/26527704#26527704)), we could have just 2-3 lower level functions which convert keys and values, and combine them together in reusable combinations based on `fetch*(PDO::FETCH_*)`. But let's try your suggestion first.

Comment (deeky666) [inline lib/Doctrine/DBAL/Portability/Statement.php]: Another idea that comes to mind is to normalize the rows at the beginning if `PDO::FETCH_COLUMN` is given and denormalize again at the end? Like expand the rows to a multi-dimensional array at the beginning and flatten again after portability adjustments? Not sure if that might be a better solution.

Comment (morozov) [inline lib/Doctrine/DBAL/Portability/Statement.php]: I think it'd look hacky but definitely save some lines of code.

Comment (deeky666) [inline lib/Doctrine/DBAL/Portability/Statement.php]: The most important thing is it saves a lot of complexity and function calls which only serve for 1 use-case. But as I said, not sure about that, it is just an idea that came to my mind.

**Comment by morozov** [comment]
@Ocramius are you okay with the current approach?

Off-topic: I tried putting together an [alternative implementation](https://github.com/doctrine/dbal/compare/master...morozov:portability-fun) which uses a functional approach to converting data and avoids code duplication, but… for some reason, there's even more code there than in the original one 😕

**Comment by Ocramius** [comment]
@morozov I'm fine with it, and merging :-)

File: lib/Doctrine/DBAL/Portability/Connection.php [hunk 7]
```diff
@@ -71,11 +71,11 @@ public function connect()
                 } elseif ($this->getDatabasePlatform()->getName() === "sqlite") {
                     $params['portability'] = $params['portability'] & self::PORTABILITY_SQLITE;
                 } elseif ($this->getDatabasePlatform()->getName() === "drizzle") {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Portability/Connection.php]: Note for the next person that has to maintain this: we're sorry about this massive chain of doom and `elseif` :-(

**Comment by Ocramius** [comment]
Backported to `2.5` via doctrine/dbal@5a4ff4673c98f18fc034c7222ce2d4b1481d4565
