### PR TITLE
Single PostgreSQLPlatform::getListSequencesSQL

### LINKED ISSUE #5244: Diff command with PostgreSQLPlatform fails when there is a sequence
### Bug Report

|    Q        |   A
|------------ | ------
| Version dbal | 3.3.1
| Version postgres | 13.5

#### Summary

Diff command with **PostgreSQLPlatform** fails when there is a sequence. Note: There is no problem with deprecated **PostgreSQL100Platform** .

#### Current behaviour

When using diff command with actual **PostgreSQLPlatform**, fatal error: An exception occurred while executing a query: `SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "test_id_seq"`

#### How to reproduce

1. Use PostgreSQLPlatform.
2. Have the `test_id_seq` sequence.
3. Run the diff command.

#### Expected behaviour

The diff command with **PostgreSQLPlatform** has the same behavior as with **PostgreSQL100Platform**. This is correct behavior.

#### Possible solution
The fix is here https://github.com/doctrine/dbal/pull/5233

### PR DESCRIPTION
**Pull request by maxm86545**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | https://github.com/doctrine/dbal/issues/5244

#### Summary

PostgreSQL100Platform::getListSequencesSQL is compatible with Postgres 9.4+

### CODE REVIEW

File: tests/Platforms/PostgreSQLPlatformTest.php [hunk 1]
```diff
@@ -1071,4 +1071,19 @@ public function testInitializesJsonTypeMapping(): void
         self::assertTrue($this->platform->hasDoctrineTypeMappingFor('jsonb'));
         self::assertEquals(Types::JSON, $this->platform->getDoctrineTypeMapping('jsonb'));
     }
+
+    public function testGetListSequencesSQL(): void
```
Comment (morozov) [inline tests/Platforms/PostgreSQLPlatformTest.php]: Please do not reinstate this test. It's pointless. This code is covered by `SchemaManagerFunctionalTestCase::testListSequences()`.

**Review by derrabus — DISMISSED** [review]

**Comment by morozov** [comment]
@maxm86545 could you squash the commits, please? Or I can do it myself later.

I actually cannot:
```
$ git push git@github.com:maxm86545/dbal.git pull/5256:3.4.x -f
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 12 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 1.60 KiB | 817.00 KiB/s, done.
Total 11 (delta 10), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (10/10), completed with 10 local objects.
To github.com:maxm86545/dbal.git
 ! [remote rejected]     pull/5256 -> 3.4.x (permission denied)
error: failed to push some refs to 'github.com:maxm86545/dbal.git'
```

Please squash them yourself.

**Review by derrabus — APPROVED** [review]
