### PR TITLE
Drop deprecation in `TableDiff` and throw exception instead

### LINKED ISSUE #7124: SQLite platform ignores changes in unnamed foreign key constraints
If an unnamed foreign key constraint is affected by a diff, the SQLite platform, doesn't drop it. It either ignores the fact that it needs to be dropped, or just creates the new version.
```php
$a = new Table('a');
$a->addColumn('id', Types::INTEGER);

$b = new Table('b');
$b->addColumn('id', Types::INTEGER);

// this is the first version of table "c". we need to pass unnamed foreign key constraints
// to the constructor instead of adding them to an existing object to prevent auto-generation
// of a name
$c1 = new Table('c', [
    new Column('id', Type::getType(Types::INTEGER)),
    new Column('a_id', Type::getType(Types::INTEGER)),
    new Column('b_id', Type::getType(Types::INTEGER)),
], [], [], [
    new ForeignKeyConstraint(['a_id'], 'a', ['id']),
]);

$schema = new Schema([$a, $b, $c1]);

$sm = $this->connection->createSchemaManager();
$sm->createSchemaObjects($schema);

// this is the version of table "c" introspected from the database
$c = $sm->introspectTable('c');

// this is the second version of table "c". instead of the FK constraint referencing table "a",
// now it contains another one referencing table "b",
$c2 = new Table('c', [
    new Column('id', Type::getType('integer')),
    new Column('a_id', Type::getType('integer')),
    new Column('b_id', Type::getType('integer')),
], [], [], [
    new ForeignKeyConstraint(['b_id'], 'b', ['id']),
]);

// the diff should capture the difference between the actual and the new versions
$diff = $this->schemaManager->createComparator()
    ->compareTables($c, $c2);

try {
    $sm->alterTable($diff);
} catch (\Throwable $e) {
    // for some reason, the INSERT query executed during the migration triggers:
    // General error: 1 foreign key mismatch - "c" referencing "b"
    // I cannot reproduce it with by using SQLite directly
    echo $e->getMessage(), PHP_EOL;
}

// introspect table "c" again
$c = $sm->introspectTable('c');

// observe the FK constraints
foreach ($c->getForeignKeys() as $fk) {
    echo $fk->getForeignTableName() . "\n";
}
```

**Expected behavior**:
1. The FK constraint referencing table "a" has been dropped
2. The one referencing table "b" has been added

**Actual behavior**:
Both keys are there.

### 3.10.x implementation details

The comparator detects that the FK constraint has been "modified". But since it doesn't have a name, it doesn't replace the previous one but just gets added to the list of the FK constraints of the new table (the `else` block).
https://github.com/doctrine/dbal/blob/7d710c9a468e2ded810cb920e52e409a93e3ffc8/src/Platforms/SqlitePlatform.php#L1513-L1520

### 4.4.x implementation details

The comparator detects that one FK constraint has been dropped and another one was added (which makes more sense than the 3.10.x logic. However, if the dropped constraint doesn't have a name, the platform ignores it (the `if` block):
https://github.com/doctrine/dbal/blob/234c37cd2632c7449f3dc864c18b8b6842ebcf61/src/Platforms/SQLitePlatform.php#L933-L941

### PR DESCRIPTION
**Pull request by santysisi**
|      Q       |   A
|------------- | -----------
| Type         | deprecation
| Fixed issues |no

Fixes #7124

#### Summary

The `TableDiff` constructor no longer allows dropped foreign keys without names. A deprecation warning was triggered since `4.4`. This patch removes the trigger and replaces it with an immediate Exception if an unnamed dropped foreign key is passed.

Reference:
https://github.com/doctrine/dbal/pull/7143

### CODE REVIEW

**Comment by santysisi** [comment]
status: needs work

**Comment by santysisi** [comment]
Status: needs review

Hi 👋
I have a couple of comments regarding this PR:

1) I updated some tests to include a foreign key name. If the FK name doesn't exist, `TableDiff` will now throw this new exception. I'm wondering if this change is necessary for the previous versions as well. Once that's clear, I can rebase this PR. Please let me know if you'd prefer me to update the previous branch first and then rebase, or if it's okay to keep this change within this branch.

2) I'm currently throwing an `InvalidArgumentException`, but I’m not sure if you'd prefer a custom exception or a new one specific to this case. Let me know what you think 😊

Thanks!

File: src/Schema/TableDiff.php [hunk 1]
```diff
@@ -44,12 +45,9 @@ public function __construct(
     ) {
         foreach ($droppedForeignKeys as $droppedForeignKey) {
             if ($droppedForeignKey->getObjectName() === null) {
-                Deprecation::trigger(
-                    'doctrine/dbal',
-                    'https://github.com/doctrine/dbal/pull/7143',
-                    'Dropping a foreign key constraints without specifying its name is deprecated.',
+                throw new InvalidArgumentException(
```
Comment (morozov) [inline src/Schema/TableDiff.php:48]: > I'm currently throwing an `InvalidArgumentException`, but I’m not sure if you'd prefer a custom exception or a new one specific to this case. Let me know what you think 😊

~~Please introduce `ForeignKeyAlreadyExists` similar to `ForeignKeyDoesNotExist` with the following error message:~~
> ~~A foreign key constraint named %s already exists on table %s.~~

Sorry, that would be for the other PR. Here, throwing an `InvalidArgumentException` is fine. I'm going to rework the constructor later, so this situation won't be possible. See https://github.com/doctrine/dbal/pull/7157.

**Review by morozov — COMMENTED** [review]
> I updated some tests to include a foreign key name. If the FK name doesn't exist, `TableDiff` will now throw this new exception.

👍 

> I'm wondering if this change is necessary for the previous versions as well.

No. It would be a breaking change which is only acceptable in the next major release.

File: src/Schema/TableDiff.php (hunk 1 above)
Comment (santysisi) [reply src/Schema/TableDiff.php:48]: Got it, thanks a lot for the explanation and the context! 😊
I'll fix the failing test, and I think it'll be ready after that

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @santysisi!
