### PR TITLE
Use correct column order for composite foreign keys

### LINKED ISSUE #4971: MySQL: Determining existing composite foreign keys does not take column positions (ORDINAL_POSITION) into account (missing ORDER BY)
### Bug Report

When using a foreign key with multiple join columns, the method `\Doctrine\DBAL\Platforms\MySqlPlatform::getListTableForeignKeysSQL` does not order by `ORDINAL_POSITION` in its SQL. See: https://github.com/doctrine/dbal/blob/96b0053775a544b4a6ab47654dac0621be8b4cf8/src/Platforms/MySQLPlatform.php#L179

This can result in the order of the columns not being the same as expected.

E.g. on a MySQL 8.0 installation it seems to be ordered alphabetically by column name and 5.7 it seems to be by ordinal position which results in potential schema differences with 8.0

It might also be something else and not version related.

I think it should be enough to add

```sql
ORDER BY k.`ORDINAL_POSITION` ASC
```

Not 100% sure if this is the correct field but I think it is. It probably also has to be added to the select for the ORDER BY to be usable in this scenario.

With it, 8.0 and 5.7 both return the same order for the referenced columns.

For other similar statements the columns are already ordered, e.g. https://github.com/doctrine/dbal/blob/96b0053775a544b4a6ab47654dac0621be8b4cf8/src/Platforms/MySQLPlatform.php#L147
or
https://github.com/doctrine/dbal/blob/96b0053775a544b4a6ab47654dac0621be8b4cf8/src/Platforms/MySQLPlatform.php#L350

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.4 (but probably also 3.1.3)

### PR DESCRIPTION
**Pull request by AndreasA**
Fixes wrong foreign key order. For now just an integration test.

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4971

### CODE REVIEW

File: src/Platforms/MySQLPlatform.php [hunk 1]
```diff
@@ -185,7 +185,7 @@ public function getListTableForeignKeysSQL($table, $database = null)
         }
 
         $sql = 'SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, ' .
-               'k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ ' .
+               'k.`REFERENCED_COLUMN_NAME`, k.`ORDINAL_POSITION` /*!50116 , c.update_rule, c.delete_rule */ ' .
```
Comment (morozov) [inline src/Platforms/MySQLPlatform.php:188]: Do we need to select this column? Its value seems to be used only for ordering.

File: src/Platforms/MySQLPlatform.php [hunk 2]
```diff
@@ -195,7 +195,8 @@ public function getListTableForeignKeysSQL($table, $database = null)
 
         return $sql . ' AND k.table_schema = ' . $databaseNameSql
             . ' /*!50116 AND c.constraint_schema = ' . $databaseNameSql . ' */'
-            . ' AND k.`REFERENCED_COLUMN_NAME` is not NULL';
+            . ' AND k.`REFERENCED_COLUMN_NAME` is not NULL'
+            . ' ORDER BY k.`ORDINAL_POSITION` ASC';
```
Comment (morozov) [inline src/Platforms/MySQLPlatform.php]: `ASC` is redundant.

File: tests/Functional/Schema/MySQLSchemaManagerTest.php [hunk 3]
```diff
@@ -544,6 +544,44 @@ public function testEnsureTableOptionsAreReflectedInMetadata(): void
         ], $onlineTable->getOption('create_options'));
     }
 
+    public function testCreatedCompositeForeignKeySchemaDoesNotDifferAfterCreation(): void
+    {
+        $this->connection->executeStatement('DROP TABLE IF EXISTS test_table_metadata');
+
+        $sql = <<<'SQL'
+CREATE TABLE test_table_foreign_key_referenced (
```
Comment (morozov) [inline tests/Functional/Schema/MySQLSchemaManagerTest.php]: Please create the table using the `Schema` API and move the test to the base class. This scenario is valid for all supported platforms.

UPD: probably, except for SQLite. Use `if ($platform->supportsForeignKeyConstraints())` to skip, if necessary.

File: tests/Functional/Schema/MySQLSchemaManagerTest.php [hunk 4]
```diff
@@ -544,6 +544,44 @@ public function testEnsureTableOptionsAreReflectedInMetadata(): void
...
+        $table->addColumn('child_col1', Types::INTEGER, ['notNull' => true]);
+        $table->addColumn('child_col2', Types::INTEGER, ['notNull' => true]);
+        $table->setPrimaryKey(['id']);
+
+        $table->addForeignKeyConstraint('test_table_foreign_key_referenced', ['child_col2', 'child_col1'], ['col2', 'col1']);
+        $this->schemaManager->createTable($table);
+
+        $tableFetched = $this->schemaManager->listTableDetails('test_table_with_foreign_key');
+
+        $diff = (new Comparator())->diffTable($tableFetched, $table);
```
Comment (morozov) [inline tests/Functional/Schema/MySQLSchemaManagerTest.php]: Since the issue is not about the comparator, it's redundant in the test as well. It's sufficient to get the foreign key definition of the introspected table and assert that the columns are in the right order.

**Review by morozov — COMMENTED** [review]
Thanks for the patch, @AndreasA. Please see a few comments inline.

File: src/Platforms/MySQLPlatform.php (hunk 1 above)
Comment (AndreasA) [reply src/Platforms/MySQLPlatform.php:188]: @morozov Thanks for giving feedback. I will try to remove it again. But I think I was not able to order by that column without selecting it. But I will re-check tomorrow.

File: tests/Functional/Schema/MySQLSchemaManagerTest.php (hunk 4 above)
Comment (AndreasA) [reply tests/Functional/Schema/MySQLSchemaManagerTest.php]: @morozov Makes sense.

File: tests/Functional/Schema/MySQLSchemaManagerTest.php (hunk 3 above)
Comment (AndreasA) [reply tests/Functional/Schema/MySQLSchemaManagerTest.php]: @morozov So I should create it like I do with the `test_table_with_foreign_key`  table?

Comment (morozov) [reply tests/Functional/Schema/MySQLSchemaManagerTest.php]: Yes.

File: src/Platforms/MySQLPlatform.php (hunk 1 above)
Comment (AndreasA) [reply src/Platforms/MySQLPlatform.php:188]: @morozov I just re-checked it is required due to the DISTINCT in the select clause, otherwise I get the following error.
`3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'information_schema.k.ORDINAL_POSITION' which is not in SELECT list; this is incompatible with DISTINCT` which is because MySQL 8.0 uses `ONLY_FULL_GROUP_BY` by default.

File: src/Platforms/MySQLPlatform.php (hunk 2 above)
Comment (AndreasA) [reply src/Platforms/MySQLPlatform.php]: @morozov I just checked other similar statements in MySQLPlatform and all of them add `ASC` at the end, see: https://github.com/doctrine/dbal/blob/3.1.3/src/Platforms/MySQLPlatform.php#L364
https://github.com/doctrine/dbal/blob/3.1.3/src/Platforms/MySQLPlatform.php#L157

personally, I also prefer to add the direction and not count on the default direction staying ASC, though it is extremely unlikely that MySQL will change that 😄 

However, as mentioned for other similar statements it is with ASC, so I would prefer to keep it, so it is in sync with the others.

**Comment by AndreasA** [comment]
@morozov The threads should now be fixed or if not I added a comment why not.

I have now also manually executed the two create table statements on another machine with MySQL 8.0 and the retrieve foreign key SQL for it and the result was the same regarding the foreign key columns order. without ORDINAL_POSITION it was different there as well, so I think it is not just an issue - due to some configuration - for my MySQL installation. In any case using ORDINAL_POSITION should always work.

I have also checked and `ORDINAL_POSITION` was in that table since 5.6 - e.g. in case of MariaDB https://dev.mysql.com/doc/refman/5.6/en/information-schema-key-column-usage-table.html

By now moving the test to be used for all platforms, I cannot be sure 100% if the issue is fixed for all of them. I have fixed it for the SQLSrv tests now because that workflow was automatically started. 

I just hope that all others are already retrieving the data in the correct order 😄  From a short glance they should do so but the tests should make sure.

One other thing: I have created the PR for 3.x but should I actually create a PR for 2.x which can then be merged into 3.x? though I doubt it is an issue that occurs that often, otherwise I think it would have been addressed earlier.

File: src/Platforms/SQLServer2012Platform.php [hunk 5]
```diff
@@ -1010,7 +1010,8 @@ public function getListTableForeignKeysSQL($table, $database = null)
                 INNER JOIN sys.objects AS o ON o.OBJECT_ID = fc.referenced_object_id
                 ON f.OBJECT_ID = fc.constraint_object_id
                 WHERE ' .
-                $this->getTableWhereClause($table, 'SCHEMA_NAME (f.schema_id)', 'OBJECT_NAME (f.parent_object_id)');
+                $this->getTableWhereClause($table, 'SCHEMA_NAME (f.schema_id)', 'OBJECT_NAME (f.parent_object_id)') .
+                ' ORDER BY fc.constraint_column_id';
```
Comment (AndreasA) [inline src/Platforms/SQLServer2012Platform.php:1014]: in SQLSrv some order bys add `ASC` and some don't, so I have not added it here to be in sync with your initial suggestion regarding MySQL. However, in the MySQL platform ASC is always there so I think we should add it there.

File: src/Platforms/MySQLPlatform.php (hunk 1 above)
Comment (morozov) [reply src/Platforms/MySQLPlatform.php:188]: Oh, this is because of the `DISTINCT`. It's often a smell of something missing from the query but we can leave it as is for now. Thanks for the details.

File: src/Platforms/MySQLPlatform.php (hunk 2 above)
Comment (morozov) [reply src/Platforms/MySQLPlatform.php]: It is still redundant. The fact that this practice is used in other places doesn't justify using it here. Please remove it.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php [hunk 6]
```diff
@@ -1418,6 +1419,58 @@ public function testCommentInTable(): void
...
+        $foreignColumns = ['col2', 'col1'];
+
+        $table = new Table('test_table_foreign_key_referenced');
+
+        $table->addOption('collate', 'utf8_general_ci');
+        $table->addOption('charset', 'utf8');
+        $table->addOption('comment', 'Test foreign key referenced table');
+
+        $table->addColumn('col1', Types::INTEGER, ['notNull' => true]);
+        $table->addColumn('col2', Types::INTEGER, ['notNull' => true]);
```
Comment (morozov) [inline tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: Are the `notNull` options required for the test? If not, please remove them.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php [hunk 7]
```diff
@@ -1418,6 +1419,58 @@ public function testCommentInTable(): void
...
+    public function testCreatedCompositeForeignKeyOrderIsCorrectAfterCreation(): void
+    {
+        $localColumns = ['child_col2', 'child_col1'];
+        $foreignColumns = ['col2', 'col1'];
+
+        $table = new Table('test_table_foreign_key_referenced');
+
+        $table->addOption('collate', 'utf8_general_ci');
+        $table->addOption('charset', 'utf8');
+        $table->addOption('comment', 'Test foreign key referenced table');
```
Comment (morozov) [inline tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: All the options above are irrelevant to the test. Please remove them.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php [hunk 8]
```diff
@@ -1418,6 +1419,58 @@ public function testCommentInTable(): void
...
+
+        $table->addColumn('col1', Types::INTEGER, ['notNull' => true]);
+        $table->addColumn('col2', Types::INTEGER, ['notNull' => true]);
+        $table->setPrimaryKey($foreignColumns);
+
+        $this->schemaManager->dropAndCreateTable($table);
```
Comment (morozov) [inline tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: I think `dropAndCreate()` won't work well for the tables connected by a foreign key. Please try running this test as follows  and make sure that both runs pass:
```shell
phpunit \
  --repeat 2 \
  --filter testCreatedCompositeForeignKeyOrderIsCorrectAfterCreation \
  tests/Functional/Schema/MySQLSchemaManagerTest.php
```

You may need to use something like this instead: https://github.com/doctrine/dbal/blob/81c54e8caf8b959609fa6dab244904c54f0181fc/tests/Functional/Schema/OracleSchemaManagerTest.php#L128-L132

For that, you'll need to temporarily comment out this line which is another PITA:
https://github.com/doctrine/dbal/blob/81c54e8caf8b959609fa6dab244904c54f0181fc/tests/Functional/Schema/MySQLSchemaManagerTest.php#L21-L21

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php [hunk 9]
```diff
@@ -1418,6 +1419,58 @@ public function testCommentInTable(): void
...
+        );
+
+        $this->schemaManager->dropAndCreateTable($table);
+
+        $table = $this->schemaManager->listTableDetails('test_table_with_foreign_key');
+
+        self::assertSame(
+            $localColumns,
+            $table->getForeignKey('fk_test_foreign_key')->getLocalColumns(),
+            'Order for the foreign key local columns should match the specified order for the foreign key constraint.'
```
Comment (morozov) [inline tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: Personally, I find custom assertion messages doing more harm than good. An assertion may fail not only because the order doesn't match, so this message will be misleading. I'd remove it completely.

**Comment by morozov** [comment]
> I just hope that all others are already retrieving the data in the correct order 😄 From a short glance they should do so but the tests should make sure.

I approved the test run.

> One other thing: I have created the PR for 3.x but should I actually create a PR for 2.x which can then be merged into 3.x? though I doubt it is an issue that occurs that often, otherwise I think it would have been addressed earlier.

There's no need to backport the fix to `2.x` unless you really need to.

File: src/Platforms/MySQLPlatform.php (hunk 2 above)
Comment (AndreasA) [reply src/Platforms/MySQLPlatform.php]: I have now removed it.

Though, personally I think staying in line with existing code syntax used (in this case SQL for MySQL platform) should be more important here, than removing redundancy but I am fine with removing it. Also I wouldn't say it is redundant, it is specific. Redundant would be if the same ORDER BY would be added twice, after all there is the extermely unlikely scenario, that MySQL adds an option to change the default order by direction and somebody decides to use it but as mentioned extremely unlikely :smile:

File: src/Platforms/MySQLPlatform.php (hunk 1 above)
Comment (AndreasA) [reply src/Platforms/MySQLPlatform.php:188]: Not 100% sure the DISTINCT is actually necessary but I didn't want to touch that part as I would first need to understand why it has been put there in the first place.

**Comment by AndreasA** [comment]
@morozov I have now done the necessary adjustments. Can you re-check? Not sure if the test run is running against the lastest verison.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php (hunk 8 above)
Comment (AndreasA) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: @morozov Thanks for the hint. However, dropping did not help. I had to first remove the foreign key, otherwise it did not work. Probably could have kept the dropAndCreate now but I have kept them separate now.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php (hunk 9 above)
Comment (AndreasA) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: Done. Though phpunit would output the differences too but I am happy with either solution. Personally, I very seldom use custom error messages too, but I saw some other tests using  them, so I thought it might be expected.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php (hunk 7 above)
Comment (AndreasA) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: Are removed now.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php (hunk 6 above)
Comment (AndreasA) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: Are removed now.

**Comment by morozov** [comment]
You'll need to disable the test on SQLite (see https://github.com/doctrine/dbal/pull/4978#discussion_r746828703). Its failure prevents other jobs from running.

**Comment by AndreasA** [comment]
> You'll need to disable the test on SQLite (see [#4978 (comment)](https://github.com/doctrine/dbal/pull/4978#discussion_r746828703)). Its failure prevents other jobs from running.

Ah yes. Missed that part and have added it now.

**Comment by AndreasA** [comment]
@morozov 

> You'll need to disable the test on SQLite (see [#4978 (comment)](https://github.com/doctrine/dbal/pull/4978#discussion_r746828703)). Its failure prevents other jobs from running.

Ah yes. Missed that part and have added it now. Thanks for letting me know.

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php [hunk 10]
```diff
@@ -1418,6 +1419,53 @@ public function testCommentInTable(): void
...
+            self::markTestSkipped('Platform does not support foreign keys.');
+        }
+
+        $foreignKey                = 'fk_test_foreign_key';
+        $tableForeignKeyReferenced = 'test_table_foreign_key_referenced';
+        $tableWithForeignKey       = 'test_table_with_foreign_key';
+        $localColumns              = ['child_col2', 'child_col1'];
+        $foreignColumns            = ['col2', 'col1'];
+
+        $this->schemaManager->tryMethod('dropForeignKey', $foreignKey, $tableWithForeignKey);
```
Comment (morozov) [inline tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: Dropping the FK shouldn't be necessary. Instead, the order of `DROP TABLE`'s should be changed: first the referencing, then the referenced.

Comment (AndreasA) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: @morozov Ah, damn, of course it shouldn't matter as long as the order in which they are dropped is correct. 

I guess it is indeed late 😄 

Fixed this now and also shortened the names so the OCI tests are hopefully successful as well.

Comment (AndreasA) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: btw. any reason why this line ` Type::addType('point', PointType::class); ` isn't something like:
`Type::hasType('point') ? Type::overrideType('point', PointType::class) : Type::addType('point', PointType::class);`

Comment (morozov) [reply tests/Functional/Schema/SchemaManagerFunctionalTestCase.php]: It probably should be like that. Nobody bothered to fix it yet.

**Comment by derrabus** [comment]
Can you have a look at the test failures on Oracle and DB2?

**Comment by AndreasA** [comment]
@derrabus I just did, apparantly the column names are always uppercase there but I specify them originally lowercase. I guess the easies solution would be to create them uppercase for now as I don't really care about the case just the order.

Or I ignore the case during the assertion. Not sure which way to go

**Comment by morozov** [comment]
Most tests create the columns in the lower case and use `strtolower()` on the introspection results before comparison.

**Comment by AndreasA** [comment]
@morozov @derrabus Added a corresponding strtolower conversion for the result comparison now. Hopefully, the tests will work now.

**Comment by morozov** [comment]
@AndreasA, the patch looks good to me. Please squash all commits, and we can merge it.

**Comment by AndreasA** [comment]
@morozov Done.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @AndreasA!
