### PR TITLE
Index table-scoped objects by schema and table name separately

### LINKED ISSUE #6764: Oracle: Fails to retrieve table comments when table name is a reserved keyword
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.10.x

#### Summary

On oracle, schema introspection fails to retrieve comments if the table name is a reserved keyword

#### Current behavior

Getting the comment on a table with a reserverd keyword returns `NULL`.

#### Expected behavior

Getting the comment on a table with a reserverd keyword should return the comment.

#### How to reproduce

I did setup oracle / oci driver using docker. If you have a working oracle setup it should be more straghtforward.

In the dbal sources I created those files directly.

<details><summary><code>./compose.yaml</code></summary>
<pre>
services:
  oracle:
    image: wnameless/oracle-xe-11g-r2
  php:
    build: .
    volumes:
      - .:/var/www/html
</pre>
</details>

<details><summary><code>./Dockerfile</code></summary>
<pre>
# From https://github.com/silencesys/docker-php-oci8
FROM php:8.3-fpm

# Update OS packages and install required ones.
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
      curl \
      libmemcached-dev \
      libz-dev \
      libpq-dev \
      libjpeg-dev \
      libpng-dev \
      libfreetype6-dev \
      libssl-dev \
      libmcrypt-dev \
      zip \
      unzip \
      build-essential \
      libaio1 \
      libzip-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && rm /var/log/lastlog /var/log/faillog

# Download oracle packages and install OCI8
RUN curl -o instantclient-basic-linux.x64-19.6.0.0.0dbru.zip https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip \
    && unzip instantclient-basic-linux.x64-19.6.0.0.0dbru.zip -d /usr/lib/oracle/ \
    && rm instantclient-basic-linux.x64-19.6.0.0.0dbru.zip \
    && curl -o instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip \
    && unzip instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip -d /usr/lib/oracle/ \
    && rm instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip \
    && echo /usr/lib/oracle/instantclient_19_6 > /etc/ld.so.conf.d/oracle-instantclient.conf \
    && ldconfig

ENV LD_LIBRARY_PATH /usr/lib/oracle/instantclient_19_6

RUN docker-php-ext-configure oci8 --with-oci8=instantclient,/usr/lib/oracle/instantclient_19_6 \
    && docker-php-ext-install -j$(nproc) oci8

# Expose port 9000 and start php-fpm server
CMD ["php-fpm"]
EXPOSE 9000
</pre>
</details>

```php
<?php
// ./index.php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Doctrine\DBAL\DriverManager;

$connection = DriverManager::getConnection([
    'driver'   => 'oci8',
    'host'     => 'oracle',
    'user'     => 'system',
    'password' => 'oracle',
    'dbname'   => 'XE',
    'port'     => 1521,
]);

// $connection->executeStatement('DROP TABLE "users" PURGE'); // Uncomment on subsequent runs
$connection->executeStatement('CREATE TABLE "users" ("users" NUMBER)');
$connection->executeStatement('COMMENT ON TABLE "users" IS \'table comment\'');
$connection->executeStatement('COMMENT ON COLUMN "users"."users" IS \'column comment\'');

$schemaManager = $connection->createSchemaManager();
$schema = $schemaManager->introspectSchema();
$table = $schema->getTable('users');
var_dump('table comment', $table->getComment()); // Output: table comment, NULL (ISSUE: should be table comment, table comment)
$id = $table->getColumn('users');
var_dump('column comment', $table->getColumn('users')->getComment()); // Ouput: column comment, column comment (correct)
```

Then the issue is visible after running:
1. `docker compose up` (optional, if you do not have a working oracle setup)
2. `docker compose exec php php index.php`

##### Non-reserved keyword works

```php
$connection->executeStatement('CREATE TABLE test ("id" NUMBER)');
$connection->executeStatement('COMMENT ON TABLE test IS \'table comment\'');
$connection->executeStatement('COMMENT ON COLUMN test."id" IS \'column comment\'');

$schemaManager = $connection->createSchemaManager();
$schema = $schemaManager->introspectSchema();
$table = $schema->getTable('test');
var_dump('table comment', $table->getComment()); // ==> table comment, table comment
$id = $table->getColumn('id');
var_dump('column comment', $table->getColumn('id')->getComment()); // ==> column comment, column comment
```

##### AbstractSchemaManager

The error seems to come from those calls:

https://github.com/doctrine/dbal/blob/818eae935f877a0feef51f25323be681b3f059cf/src/Schema/AbstractSchemaManager.php#L408-L411

In fact here `$tableColumnsByTable` contains `"users"` while `$indexColumnsByTable` contains `users` (notice the missing quotes) which leads to the following lines returning an empty array:

https://github.com/doctrine/dbal/blob/818eae935f877a0feef51f25323be681b3f059cf/src/Schema/AbstractSchemaManager.php#L427

#### References

- Original implementation: https://github.com/doctrine/dbal/pull/3512
- Possible related issue: https://github.com/doctrine/dbal/issues/5776
- Possible related issue: https://github.com/doctrine/dbal/issues/4357
- Originally implemented in https://github.com/doctrine/dbal/pull/3512

### PR DESCRIPTION
**Pull request by morozov**
This change eliminates the collision caused by the usage of value returned by as the key for grouping table-scoped objects (see https://github.com/doctrine/dbal/pull/6755).

Also, it enables changing the type of the parameter accepted by `TableEditor::setName()` from `string` (currently) to `OptionallyQualifiedName` which now can be built directly from introspected schema: https://github.com/doctrine/dbal/blob/76ab7a377073777a0792771f3a8223a776f9d470/src/Schema/AbstractSchemaManager.php#L268-L272

I will do it in a subsequent PR before `TableEditor::setName()` is released in 4.3.0

## Breaking changes

Besides the breaking changes in the public API, there are more in the protected Schema Manager API for which no upgrade path is being provided:
1. The `select*()` methods that accept a table name (e.g. `selectTableColumns()`) and the corresponding `fetch*()` methods (e.g. `fetchTableColumns()`) now accept the table name as `OptionallyQualifiedName`, not `string`.
2. The above `fetch*()` methods, instead of returning lists of rows grouped by qualified table name, return list of rows grouped by schema name and table name (another level of nesting).

## Improvements

Now, table names containing a dot (e.g. `"example.com"`) can be introspected on the platforms that support schemas without specifying the schema name (see the updated test).

## Future scope

Having the schema managers implement the same API for the database platforms that do and don't support schemas make the code a bit too complex and requiring extra documentation and runtime checks. A better and simpler code could be achieved by using separate APIs for fetching the schema of the databases that do and don't support schemas and an adapter between them, but this would be too much of additional rework at this point.

Fixes: https://github.com/doctrine/dbal/issues/6764.

### CODE REVIEW

File: src/Schema/SQLiteSchemaManager.php [hunk 1]
```diff
@@ -222,7 +221,9 @@ protected function _getPortableTableForeignKeysList(array $rows): array
 
             // Inferring a shorthand form for the foreign key constraint, where the "to" field is empty.
             // @see https://www.sqlite.org/foreignkeys.html#fk_indexes.
-            $foreignTablePrimaryKeyColumnRows = $this->fetchPrimaryKeyColumns($value['foreignTable']);
+            $foreignTablePrimaryKeyColumnRows = $this->fetchPrimaryKeyColumns(
+                OptionallyQualifiedName::quoted($value['foreignTable']),
+            );
```
Comment (morozov) [inline src/Schema/SQLiteSchemaManager.php:226]: This is an issue similar to the ones fixed in the last two commits of https://github.com/doctrine/dbal/pull/6744 – while parsing introspected results, the schema manager needs to fetch more, which makes it convert the data from the lower-level representation (`string`) back to the higher-level format (`OptionallyQualifiedName`) mimicking the user input for the `fetch*()` method.

This isn't nice but isn't the end of the world and could be fixed separately.

File: src/Schema/AbstractSchemaManager.php [hunk 2]
```diff
@@ -36,6 +37,22 @@
  */
 abstract class AbstractSchemaManager
 {
+    /**
+     * The key that represents null in an array where key is schema name.
+     */
+    protected const NULL_SCHEMA_KEY = "\x00";
```
Comment (morozov) [inline src/Schema/AbstractSchemaManager.php:44]: This could be any value, which isn't a valid SQL identifier. An empty string would look even closer to `null` but I think it would be more error-prone.

**Comment by greg0ire** [comment]
> and and adapter between them

ERR_CANNOT_PARSE

**Review by greg0ire — APPROVED** [review]

**Comment by morozov** [comment]
> > and and adapter between them
> 
> ERR_CANNOT_PARSE

It was supposed to be "and an adapter". Here's what I meant in pseudo-code:
```php
/**
 * To be implemented by PostgreSQL and SQL Server.
 */
interface IntrospectorThatSupportsSchemas
{
    /**
     * Accepts a qualified name (<schema>.<table>) and groups columns by schema name and table name.
     */
    function fetchColumns(QualifiedName $tableName): array<string,array<string,list<Column>>>;
}

/**
 * To be implemented by all others.
 */
interface IntrospectorThatDoesNotSupportSchemas
{
    /**
     * Accepts an unqualified name (<table>) and groups columns by table name.
     */
    function fetchColumns(UnqualifiedName $table): array<string,list<Column>>;
}

/**
 * To be used by AbstractSchemaManager.
 */
interface AbstractIntrospector // as in "for abstract database platform"
{
    /**
     * Accepts an optionally qualified name (<schema>?.<table>) and groups columns by schema name and table name.
     */
    function introspectColumns(OptionallyQualifiedName $tableName): array<string,array<string,list<Column>>>;
}

class AdapterForSupportsSchemas implements AbstractIntrospector
{
    public function __construct(private IntrospectorThatSupportsSchemas $introspector)
    {
    }
    
    public function introspectColumns(OptionallyQualifiedName $tableName): array
    {
        // resolve the optionally qualified name to a qualified name:
        // - If the name is already qualified, use it as is
        // - If not, use the default schema name (this is what PostgreSQL and SQL Server schema managers
        //   do in their buildQueryConditions() and getWhereClause() respectively)
        
        return $this->introspector->fetchColumns($resolvedTableName);
    }
}

class AdapterForDoesNotSupportSchemas implements AbstractIntrospector
{
    public function __construct(private IntrospectorThatDoesNotSupportSchemas $introspector)
    {
    }

    public function introspectColumns(OptionallyQualifiedName $tableName): array
    {
        // make sure that the optionally qualified name doesn't have a qualifier.
        // otherwise, throw an exception
        // this is what ensureUnqualifiedName() currently does in a dozen of places

        return [
            NULL_SCHEMA_KEY => $this->introspector->fetchColumns($unqualifiedTableName),
        ];
    }
}
```
