### PR TITLE
fixed using lower case column names

### LINKED ISSUE #4832: Columns are not found with 3.1.2
### Bug Report

Columns are not found. They are named in camelCase. 

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 3.1.2

#### Summary

I am using doctrine/dbal in a lumen project. I recently upgraded dbal to 3.1.2 and now my tests with sqlite and mysql fail with the message that columns cannot be found when renamed or their type is changed. 

With version 2.13.3 and 3.1.1 it works. 

#### Current behaviour

-

#### How to reproduce

-

#### Expected behaviour

The columns should be found and renamed or their type should get altered.

### PR DESCRIPTION
**Pull request by eschricker**
Columns are not found when camelCase named columns are changed or renamed when using sqlite as database.

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4832

#### Summary

Recovered the behavior of version 3.1.1 to use lower case column names.

### CODE REVIEW

**Comment by derrabus** [comment]
Can you provide a test that fails without your changes?

**Comment by eschricker** [comment]
@derrabus I have added a test, that fails without my changes

**Comment by derrabus** [comment]
Thank you. Can you have a look at the failing CS check? You probably just need to run `./vendor/bin/phpcbf` to fix this.

**Review by derrabus — DISMISSED** [review]

File: tests/Platforms/SqlitePlatformTest.php [hunk 1]
```diff
@@ -360,6 +360,30 @@ public function testRenameNonExistingColumn(): void
         $this->platform->getAlterTableSQL($tableDiff);
     }
 
+    public function testRenameCamelCaseColumn(): void
```
Comment (morozov) [inline tests/Platforms/SqlitePlatformTest.php]: @eschricker thank you for the patch. Instead of testing SQL, please test the behavior at the integration level. See `RenameColumnTest`.

File: src/Platforms/SqlitePlatform.php [hunk 2]
```diff
@@ -920,7 +920,8 @@ public function getAlterTableSQL(TableDiff $diff)
                 continue;
             }
 
-            $columns = $this->replaceColumn($diff->name, $columns, $oldColumnName, $column);
+            $oldColumnName = strtolower($oldColumnName);
```
Comment (morozov) [inline src/Platforms/SqlitePlatform.php:923]: Note, the `replaceColumn()` method also converts the names to the lower case because this is how `$columns` are indexed. With this patch, it seems no longer necessary.

Comment (eschricker) [reply src/Platforms/SqlitePlatform.php:923]: I have removed the conversion to lower case in the `replaceColumn()` method

File: tests/Platforms/SqlitePlatformTest.php (hunk 1 above)
Comment (eschricker) [reply tests/Platforms/SqlitePlatformTest.php]: I have updated the RenameColumnTest to include in the dataprovider the desired name for renaming in addition to the column name. But due to the comment that it's not working on case-sensitive platforms, the extended tests should fail on them.

Comment (morozov) [reply tests/Platforms/SqlitePlatformTest.php]: Please remove this test. Unlike the integration one, it doesn't prove that the implementation is correct, it only proves that it won't change accidentally.

**Review by morozov — COMMENTED** [review]
Looks good. Please remove the new test and squash.

**Comment by eschricker** [comment]
@morozov can you describe to me, how I can squash my commits?

**Comment by derrabus** [comment]
The test failure on SQL server looks related.

**Comment by greg0ire** [comment]
> can you describe to me, how I can squash my commits?

1. `git rebase -i origin/3.1.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already push. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by eschricker** [comment]
>     2\. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one

Thanks @greg0ire it worked :)

**Comment by morozov** [comment]
The failing test should be skipped on SQL Server due to https://github.com/doctrine/dbal/issues/4816. There's already the if-statement in the test.

**Comment by eschricker** [comment]
@morozov is there anything else I should do or is it ok so far?

**Comment by morozov** [comment]
@eschricker please fix the coding standard violation and disable the test on SQL Server.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @eschricker!
