### PR TITLE
Fix length type in `MySQLSchemaManager` with `ATTR_STRINGIFY_FETCHES` enabled

### LINKED ISSUE #7027: `SchemaManager::listTableColumns()` fails on DBAL 4.3.0 with `binary` column on MySql
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 4.3.0
| Previous Version if the bug is a regression | x.y.z

#### Summary

There is a typing issue in `\Doctrine\DBAL\Schema\MySQLSchemaManager::_getPortableTableColumnDefinition()`, 
when type is binary (probably char, varchar, and varbinary as well), `$length` contains the length as string, that fails the types in the columns constructor.

#### Current behavior

When you call `$connection->createSchemaManager()->$manager->listTableColumns($table)` on a table that has a binary column on MySql you get following error:

```
Doctrine\DBAL\Schema\Column::setLength(): Argument #1 ($length) must be of type ?int, string given
```

#### Expected behavior

`listTableColumns()` should work as expected

#### How to reproduce

* create a table with binary column on MySQL
* call `SchemaManager::listTableColumns()` on that table

### PR DESCRIPTION
**Pull request by keulinho**
Fixes https://github.com/doctrine/dbal/issues/7027

|      Q       |   A
|------------- | -----------
| Type         | bug
| Fixed issues | #7027

#### Summary

The length var was type string, which broke on the constructor of `Column`

### CODE REVIEW

**Comment by keulinho** [comment]
removed test for varchar type as there  seems to be no type mapping for that

**Comment by keulinho** [comment]
i'm having trouble to add a pure reproducer in the testing setup here, see https://github.com/doctrine/dbal/pull/7029

However I verified the fix locally inside shopware, see e.g. this workflow run for the issue: https://github.com/shopware/shopware/actions/runs/16268473345/job/45929737083?pr=11222

**Comment by derrabus** [comment]
> However I verified the fix locally inside shopware

I don't know much about Shopware's internals, but I'd like to understand why you're having this problem. Is Shopware maybe operating DBAL with the [PDO::ATTR_STRINGIFY_FETCHES](https://www.php.net/manual/en/pdo.constants.php#pdo.constants.attr-stringify-fetches) option enabled?

**Comment by keulinho** [comment]
@derrabus yes exactly we are still relying on that option and it seems that the issue only shows with that option, so far I was unable to get that option into the testsuite here and for now stopped work on the reproducer, will happily continue with that when you provide the general direction e.g. if we even want to have a complete unit test run with that option?

**Comment by derrabus** [comment]
Maybe we should add a CI job that runs the whole test suite with that option enabled. This option could be a potential footgun for every operation DBAL itself performs on the database. 🤔

**Comment by VincentLanglet** [comment]
I can confirm the (important) bug.

The error can be found on the phpstan-doctrine CI https://github.com/phpstan/phpstan-doctrine/actions/runs/16344462764/job/46174534513

**Comment by derrabus** [comment]
@VincentLanglet The failure in PHPStan's CI that you're linking to shows a test failure that happens with Postgres. This issue discusses a bug inside the MySQL schema manager. Are you sure you provided the correct link?

**Comment by VincentLanglet** [comment]
There is one failure, but also 950 errors like
```
1) PHPStan\Platform\QueryResultTypeWalkerFetchTypeMatrixTest::testPdoMysqlStringify with data set " -1" (array(array('1', true, null, 0.125, null, '0.1', null, 9, null, '2147483648', null, 'foobar', null, 1, DateTime Object (...))), 'SELECT -1 FROM %s t', PHPStan\Type\Constant\ConstantIntegerType Object (...), PHPStan\Type\Constant\ConstantIntegerType Object (...), PHPStan\Type\Constant\ConstantIntegerType Object (...), PHPStan\Type\Constant\ConstantIntegerType Object (...), PHPStan\Type\MixedType Object (...), -1, -1, -1, -1, -1, 'default')
TypeError: Doctrine\DBAL\Schema\Column::setLength(): Argument #1 ($length) must be of type ?int, string given, called in /home/runner/work/phpstan-doctrine/phpstan-doctrine/vendor/doctrine/dbal/src/Schema/Column.php on line 102
```

I thought this was related to the fact `length` was not caster to int.

**Comment by derrabus** [comment]
> There is one failure, but also 950 errors like

You're right, I missed those. My bad. Yes, this seems to be the same error.

Same question for you then: https://github.com/doctrine/dbal/pull/7028#issuecomment-3074932303

**Comment by VincentLanglet** [comment]
> > There is one failure, but also 950 errors like
> 
> You're right, I missed those. My bad. Yes, this seems to be the same error.
> 
> Same question for you then: [#7028 (comment)](https://github.com/doctrine/dbal/pull/7028#issuecomment-3074932303)

I dunno a lot about the logic behind the phpstan-doctrine tests, but the failure happen on some
```
$this->performDriverTest(
			'pdo_sqlite',
			self::CONFIG_STRINGIFY,
			$data,
			$dqlTemplate,
			(string) $this->dataName(),
			PHP_VERSION_ID,
			$sqliteExpectedType,
			$sqliteExpectedResult,
			$stringify,
		);
```
code with the map
```
private const CONNECTION_CONFIGS = [
		self::CONFIG_DEFAULT => [],
		self::CONFIG_STRINGIFY => [
			PDO::ATTR_STRINGIFY_FETCHES => true,
		],
		self::CONFIG_NO_EMULATE => [
			PDO::ATTR_EMULATE_PREPARES => false,
		],
		self::CONFIG_STRINGIFY_NO_EMULATE => [
			PDO::ATTR_STRINGIFY_FETCHES => true,
			PDO::ATTR_EMULATE_PREPARES => false,
		],
	];
```

So yes @derrabus indeed the failure occurs because there is a testcase with the option `[PDO::ATTR_STRINGIFY_FETCHES](https://www.php.net/manual/en/pdo.constants.php#pdo.constants.attr-stringify-fetches)`.

**Comment by keulinho** [comment]
i got the issue reproduced in the doctrine test suite by adding a job with stringify fetches, you can see it failing with the same error here: https://github.com/doctrine/dbal/pull/7029

I'll cherry-pick the new testsuite to this PR and will make it green

Anything else you need before this is ready to merge?

File: tests/Functional/Query/QueryBuilderTest.php [hunk 1]
```diff
@@ -555,24 +556,21 @@ public function testPlatformDoesNotSupportCTE(): void
      */
     private function prepareExpectedRows(array $rows): array
     {
-        if (! TestUtil::isDriverOneOf('ibm_db2', 'pdo_oci', 'pdo_sqlsrv', 'oci8')) {
```
Comment (keulinho) [inline tests/Functional/Query/QueryBuilderTest.php:558]: This took quite some time for me to understand all the negated ifs, IMHO keeping the flow as straight forward as possible makes it easier to understand what is going on

File: tests/Functional/Query/QueryBuilderTest.php [hunk 2]
```diff
@@ -555,24 +556,21 @@ public function testPlatformDoesNotSupportCTE(): void
...
-            return $rows;
-        }
-
-        if (! TestUtil::isDriverOneOf('ibm_db2')) {
+        if (
+            TestUtil::isDriverOneOf('pdo_oci', 'pdo_sqlsrv', 'oci8')
+            || (TestUtil::getConnectionParams()['driverOptions'][PDO::ATTR_STRINGIFY_FETCHES] ?? false) === true
```
Comment (keulinho) [inline tests/Functional/Query/QueryBuilderTest.php:561]: I intentionally did not check for `pdo_mysql`driver as this would allow us to easily add the same job for other DB engines, if the `ATTR_STRINGIFY_FETCHES` option is relevant as well

**Comment by keulinho** [comment]
@derrabus tests and CI is green now, I consider this finished so far, happy to get your review ;)

**Review by derrabus — APPROVED** [review]
Awesome work, thank you! Would you be interested in adding a CI job for the other PDO drivers as well?

**Comment by keulinho** [comment]
Thanks for quickly merging this! 🎉 

PR for more jobs with that option is here: https://github.com/doctrine/dbal/pull/7052
