### PR TITLE
[DBAL-2555] Fix date and datetimetz type mapping on Oracle

### LINKED ISSUE #2555: schema generation maps oracle DATE fields to datetime
I am using the schema generation tool to generate create/update scripts for my database from yaml entities.
Using http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#datetime as a guide, I have a date column of type 'date', which correctly generates an oracle column with type DATE.
However, when I try to generate update scripts, OraclePlatform::doctrineTypeMappings maps the oracle DATE to a doctrine DateTimeType. The columns are seen as different because DateType != DateTimeType.
If I change the mapping date->datetime to date->date, it correctly sees that the database column matches the entity definition.

I think this is a bug, although minor since the update sql is generated from the entity definition and ends up being a no-op.

### PR DESCRIPTION
**Pull request by deeky666**
Fixes #2555 

Oracle's `DATE` type was erroneously mapped to Doctrine's `DateTime` type. Although I wonder why nobody ever complained about that until now, the fix looks straight forward and also complies to what we have documented.

Additionally the instrospection of `DateTimeTzType` was wrong and has been fixed (wrong case in type comparison).

Tests pass locally.

### CODE REVIEW

File: lib/Doctrine/DBAL/Schema/OracleSchemaManager.php [hunk 1]
```diff
@@ -102,7 +102,7 @@ protected function _getPortableTableColumnDefinition($tableColumn)
 
         $dbType = strtolower($tableColumn['data_type']);
         if (strpos($dbType, "timestamp(") === 0) {
-            if (strpos($dbType, "WITH TIME ZONE")) {
+            if (strpos($dbType, "with time zone")) {
```
Comment (Ocramius) [inline lib/Doctrine/DBAL/Schema/OracleSchemaManager.php]: Since this seems to be something that the DB engine doesn't guarantee, `strtolower()` should be used (or at least case insensitive matching).

Comment (Ocramius) [inline lib/Doctrine/DBAL/Schema/OracleSchemaManager.php]: Test probably also needed with it, but unsure if practical

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: lib/Doctrine/DBAL/Schema/OracleSchemaManager.php (hunk 1 above)
Comment (deeky666) [inline lib/Doctrine/DBAL/Schema/OracleSchemaManager.php]: Have a look at line 193 ;)
But besides that you reminded me that I forgot a unit test case for the mapping issue in the platform which I added now.

Comment (deeky666) [inline lib/Doctrine/DBAL/Schema/OracleSchemaManager.php]: This is is covered by the functional test case btw. Not sure how else to test this :>

Comment (Ocramius) [inline lib/Doctrine/DBAL/Schema/OracleSchemaManager.php]: Dammit, didn't read that, thanks :-)

**Review by Ocramius — APPROVED** [review]

File: tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php [hunk 2]
```diff
@@ -412,13 +412,19 @@ public function testAlterTableNotNULL()
         $this->assertEquals($expectedSql, $this->_platform->getAlterTableSQL($tableDiff));
     }
 
+    /**
+     * @group DBAK-2555
```
Comment (DeepDiver1975) [inline tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php]: DBAL :wink:

Comment (deeky666) [inline tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php]: thx, fixed

**Comment by Ocramius** [comment]
:shipit:

**Comment by Ocramius** [comment]
Backported via doctrine/dbal@8a13144aa046f4c218dc12ed48167de7b184416c
