### PR TITLE
Source column defaults from its own table

### LINKED ISSUE #5322: Charset or Collation are ignored during migration
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.*

#### Summary

After upgrade dbal from 2.x to 3.3.x doctrine migration generates `down` a lot of changes about `COLLATE` because in Comparatar charset & collation is null 
https://github.com/doctrine/dbal/blob/dfdb5fb2b2230237bf46761140ce9b2dd4edea39/src/Platforms/MySQL/Comparator.php#L34-L37

#### Current behaviour

We have a table:
```sql
CREATE TABLE IF NOT EXISTS `test` (`name` VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\';');
```

If I run `migrations:diff`:
- `up` is empty
- `down` contains changes for `name` column 

```sql
ALTER TABLE test CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`
```

#### How to reproduce

```php
$connection = DriverManager::getConnection(['url' => 'mysql://root:root@127.0.0.1:3306/test?serverVersion=8.0']);
$connection->executeQuery('CREATE TABLE IF NOT EXISTS `test` (`name` VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\';');
$schemaManager = $connection->createSchemaManager();
$fromSchema = $schemaManager->createSchema();

$toSchema = new Schema([], [], $schemaManager->createSchemaConfig());
$toSchema->createTable('test')->addColumn(
    'name',
    Types::STRING,
    ['length' => 255, 'notnull' => true, 'platformOptions' => ['version' => false]]
);

$up = $schemaManager->createComparator()->compareSchemas($fromSchema, $toSchema);
$diffSql = $up->toSql($connection->getDatabasePlatform());
assert(count($diffSql) === 0);


$down = $schemaManager->createComparator()->compareSchemas($toSchema, $fromSchema);
$diffSql = $down->toSql($connection->getDatabasePlatform());
assert(count($diffSql) === 0);
```

#### Expected behaviour

Diff of UP & DOWN should be empty -> nothing to migrate

I created this issue from https://github.com/doctrine/dbal/issues/5321#issuecomment-1069705080

### PR DESCRIPTION
**Pull request by morozov**
**Change summary**:
1. Instead of sourcing column defaults from the from/online table, source them from its own table.
2. Add some more assertions that test the inverse diff. Those assertions would fail without the fix so I believe they cover the originally reported scenario.

Fixes #5322.

### CODE REVIEW

File: tests/Functional/Schema/MySQLSchemaManagerTest.php [hunk 1]
```diff
@@ -202,18 +202,7 @@ public function testDoesNotPropagateDefaultValuesForUnsupportedColumnTypes(): vo
 
         $diff = $this->schemaManager->createComparator()
             ->diffTable($table, $onlineTable);
-        self::assertNotFalse($diff);
```
Comment (morozov) [inline tests/Functional/Schema/MySQLSchemaManagerTest.php:205]: The expectation that there should be a diff is invalid. It's a bug that is mitigated down the line: https://github.com/doctrine/dbal/blob/a18ffc1a1fde506b17c34e9523fce95f16838359/src/Platforms/AbstractMySQLPlatform.php#L544-L551

We may try removing this condition as well.

Comment (morozov) [reply tests/Functional/Schema/MySQLSchemaManagerTest.php:205]: Funny thing is that this is one of the conditions that cause https://github.com/doctrine/dbal/issues/4747.

**Review by greg0ire — APPROVED** [review]
