### PR TITLE
Fix #3082: Add BC for PDO-only fetch modes

### LINKED ISSUE #3082: Custom PDO fetch modes and 2.7.0
[Announced](https://github.com/doctrine/dbal/releases/tag/v2.7.0) as a deprecation only, an [exception is thrown](https://github.com/doctrine/dbal/blob/f76bf5ef631cec551a86c2291fc749534febebf1/lib/Doctrine/DBAL/Driver/PDOStatement.php#L234) when passing unrecognized fetch modes, such as `PDO::FETCH_KEY_PAIR`. That is a BC break. In another instance, a [silenced deprecation warning](https://github.com/doctrine/dbal/blob/f76bf5ef631cec551a86c2291fc749534febebf1/lib/Doctrine/DBAL/Schema/Column.php#L129) is issued instead.

While I completely agree on deprecating implicit usage of PDO features, I'd like a migration path that does not involve breaking working code. I suppose that some code depends on recognized fetch modes; I will investigate this and want to provide a pull request.

### PR DESCRIPTION
**Pull request by corphi**
The test case covers most of the sane PDO fetch modes that are not availably as DBAL fetch mode. Unfortunately, the fetch mode cannot be read by userland code. We have to trust that they are actually swapped for every method that uses them (well, they are); or use reflection to test the private method `convertFetchMode()`.
closes #3082

Edit by @beberlei:

This deprecation was introduced as part of the removal of Doctrine DBAL API relying on implicit PDO behavior. This was started here https://github.com/doctrine/dbal/pull/2958 and disallows the use of `PDO::PARAM_*` constants in Doctrine DBAL APIs.

Before:
```php
$statement->bindParam(1, $value, PDO::PARAM_INT);
```
After:
```php
$statement->bindParam(1, $value, \Doctrine\DBAL\Types\Types::INTEGER);
```

in addition PDO Fetch modes that are unsupported by Doctrine explictly are disallowed, for example `PDO::FETCH_KEY_PAIR`. Use the new `fetch*()` APIs instead. See https://github.com/doctrine/dbal/pull/4019 for details.

### CODE REVIEW

**Comment by morozov** [comment]
@corphi thank you for the patch. Please replicate the same logic for `convertParamType()`. I don't know which of the PDO-specific parameter type users can use, but the same issue is still there.

As for the testing, could you turn your test into a functional one so that apart from verifying the deprecation message, it also makes sure that a PDO-specific mode still works. I will help us ensure that we don't break this functionality again.

File: lib/Doctrine/DBAL/Driver/PDOStatement.php [hunk 1]
```diff
@@ -231,7 +234,13 @@ private function convertFetchMode(?int $fetchMode) : ?int
         }
 
         if (! isset(self::FETCH_MODE_MAP[$fetchMode])) {
-            throw new \InvalidArgumentException('Invalid fetch mode: ' . $fetchMode);
+            // next major: throw an exception
```
Comment (Majkl578) [inline lib/Doctrine/DBAL/Driver/PDOStatement.php]: Can you prefix this with `TODO: ...`?

File: lib/Doctrine/DBAL/Driver/PDOStatement.php [hunk 2]
```diff
@@ -231,7 +234,13 @@ private function convertFetchMode(?int $fetchMode) : ?int
...
+            @trigger_error(sprintf(
+                'Using a PDO fetch mode (%d given) is deprecated and will cause an error in Doctrine 3.0',
```
Comment (Majkl578) [inline lib/Doctrine/DBAL/Driver/PDOStatement.php]: The message should also mention conbination of modes:
```
Using a PDO fetch mode or their combination (%d given) is deprecated and will not be supported in Doctrine 3.0'
```

**Review by Majkl578 — COMMENTED** [review]
Nicely handled. 👍

**Comment by morozov** [comment]
@corphi are you planning on finishing this up or I could take over?

**Comment by corphi** [comment]
@morozov I addressed the minor points raised by @Majkl578, but can’t refactor the test until Thursday.

Concerning param types: I think these are a minor issue in comparison and beyond the scope of what I intended. I never used param types beyond those supported by Doctrine: The native string ones are new, and the `NULL` one is [rather useless](https://wiki.php.net/rfc/deprecate_pdo_null). That basically leaves `PDO::PARAM_INPUT_OUTPUT` for use with stored procedures.

**Comment by morozov** [comment]
> @morozov I addressed the minor points raised by @Majkl578, but can’t refactor the test until Thursday.

No worries. I can take care of it myself. If you don't mind, I'll update this pull request. Otherwise, I'll file a new one.

> Concerning param types: I think these are a minor issue in comparison and beyond the scope of what I intended. I never used param types other than those supported by Doctrine: The native string ones are new, that basically leaves `PDO::PARAM_INPUT_OUTPUT` for use with stored procedures.

I see your point and I think the same regarding custom parameters. The problem is that if somebody even in theory uses them, it will be a breaking change for them same as this one was for you. I want to get it fixed even if it's not reported.

File: lib/Doctrine/DBAL/Driver/PDOStatement.php [hunk 3]
```diff
@@ -213,7 +216,13 @@ public function fetchColumn($columnIndex = 0)
     private function convertParamType(int $type) : int
     {
         if (! isset(self::PARAM_TYPE_MAP[$type])) {
-            throw new \InvalidArgumentException('Invalid parameter type: ' . $type);
+            // TODO: next major: throw an exception
+            @trigger_error(sprintf(
+                'Using a PDO parameter type (%d given) is deprecated and will cause an error in Doctrine 3.0',
```
Comment (Majkl578) [inline lib/Doctrine/DBAL/Driver/PDOStatement.php]: Can we have a test for this one too? 🙏

Comment (morozov) [reply lib/Doctrine/DBAL/Driver/PDOStatement.php]: PostgeSQL doesn't like `PDO::PARAM_INPUT_OUTPUT` (see https://travis-ci.org/doctrine/dbal/jobs/363396885).

**Review by morozov — APPROVED** [review]

**Review by Majkl578 — APPROVED** [review]

**Comment by Majkl578** [comment]
Thanks @corphi!

**Comment by Majkl578** [comment]
Backported into 2.7 @ d4a96deb43ffcadbd60f6542551c92c83f4ce48a
