### PR TITLE
Fix BC break: QueryBuilder::andWhere() etc. should ignore empty strings

### LINKED ISSUE #4282: Skip empty expression parts
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.11.0

#### Summary

The commit 1d503253ff57987161f10d4f2c81b5a9889d48a4 introduced a breaking change.

[CompsiteExpression->with()](https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Query/Expression/CompositeExpression.php#L119) directly adds `parts`, whereas the old [CompositeExpression->addMultiple()](https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Query/Expression/CompositeExpression.php#L80) utilized [CompositeExpression->add()](https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Query/Expression/CompositeExpression.php#L98) which had an `empty`-check.

- has a guard
see https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Query/Expression/CompositeExpression.php#L100

- has no guard
see https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Query/Expression/CompositeExpression.php#L126

#### Current behaviour

`parts` with empty-string result in `AND ()` which is an invalid where-expression.

#### How to reproduce

- Instantiate QueryBuilder instance.
- provide an empty string to `andWhere`

```php
$queryBuilder->andWhere('', "foo = 'bar'")->getSQL();
```

#### Expected behaviour

Do not add empty where conditions in `CompositeExpression->with()` as `CompositeExpression->add()` did.

### PR DESCRIPTION
**Pull request by BenMorel**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4282

#### Summary

The previous behaviour of these methods has been restored: they now ignore empty strings passed as parameters.

### CODE REVIEW

File: lib/Doctrine/DBAL/Query/QueryBuilder.php [hunk 1]
```diff
@@ -1393,4 +1399,21 @@ public function __clone()
...
+     * @param array<mixed> $args
+     *
+     * @return array<mixed>
+     *
+     * @todo remove for 3.0
+     */
+    private static function filterEmptyArgs(array $args): array
+    {
+        return array_values(array_filter($args, static function ($value) {
+            return ! empty($value);
```
Comment (morozov) [inline lib/Doctrine/DBAL/Query/QueryBuilder.php:1416]: Isn't it the default behavior of `array_filter` without a callback?

File: lib/Doctrine/DBAL/Query/QueryBuilder.php [hunk 2]
```diff
@@ -1393,4 +1399,21 @@ public function __clone()
...
+     * Filters out empty values from the given argument list.
+     * Fixes a BC break introduces in 2.11: https://github.com/doctrine/dbal/issues/4282
+     *
+     * @param array<mixed> $args
+     *
+     * @return array<mixed>
+     *
+     * @todo remove for 3.0
+     */
+    private static function filterEmptyArgs(array $args): array
```
Comment (morozov) [inline lib/Doctrine/DBAL/Query/QueryBuilder.php:1413]: Why does the method need to be static?

File: lib/Doctrine/DBAL/Query/QueryBuilder.php [hunk 3]
```diff
@@ -829,6 +831,7 @@ public function where($predicates)
     public function andWhere($where)
     {
         $args  = func_get_args();
+        $args  = self::filterEmptyArgs($args);
```
Comment (morozov) [inline lib/Doctrine/DBAL/Query/QueryBuilder.php:834]: As far as I understand, we need to cover both branches with the `with()` and `::and()` because the latter used to be implemented by `->addMultiple()` → `->add()` as well. Would it be possible to cover it with a test as well?

Once implemented, please replicate the test for the rest of the changed methods.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 2 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php:1413]: Because phpcs wants it so!

Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php:1413]: Please double-check. I can't reproduce this by making the method non-static.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 1 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Indeed! Updated. Should we keep the `filterEmptyArgs()` anyway, even if it's very simple, just as documentation?

File: lib/Doctrine/DBAL/Query/QueryBuilder.php [hunk 4]
```diff
@@ -1393,4 +1399,19 @@ public function __clone()
...
+     *
+     * @param array<mixed> $args
+     *
+     * @return array<mixed>
+     *
+     * @todo remove for 3.0
+     */
+    private static function filterEmptyArgs(array $args): array
+    {
+        return array_values(array_filter($args));
```
Comment (morozov) [inline lib/Doctrine/DBAL/Query/QueryBuilder.php:1415]: Is `array_values()` necessary here? The array keys are not used anywhere explicitly, and PHP seems to ignore the keys of the array passed via `...`.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 3 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php:834]: Tests added!

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 1 above)
Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: If it ends up being just `array_filter()`, it could be used directly w/o being wrapped in a documenting method. But I don't have a strong opinion.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 4 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Indeed! Because PHP errors when non-numeric keys are used, I was pretty sure that it would error if non-sequentials keys were used... I was wrong. Fixed.

The above question stands even more then: should we keep `filterEmptyArgs()` as documentation? Or should we use `array_filter()` inline? But we lose the link to the issue and the TODO.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 1 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Okay, I've inlined it with a link to the issue and a TODO. See if you're happy with that!

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 2 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: It's [here](https://github.com/BenMorel/dbal/runs/1151940985):
> [error]Closure not using "$this" should be declared static.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php [hunk 5]
```diff
@@ -829,6 +830,7 @@ public function where($predicates)
     public function andWhere($where)
     {
         $args  = func_get_args();
+        $args  = array_filter($args); // TODO remove for 3.0 https://github.com/doctrine/dbal/issues/4282
```
Comment (morozov) [inline lib/Doctrine/DBAL/Query/QueryBuilder.php:833]: Instead of a TODO, it's better to file a release blocker for 3.0. It's fine to leave a comment explaining why this is needed though.

Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php:833]: I don't know what a release blocker is. Is it an issue that mentions that this code should be removed?

Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Yes, please file an issue. I'll mark it as a blocker and assign it to the 3.0.0 milestone. This way, we'll have it tracked in the issue tracker, not in the source code.

Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Anyway I've removed the TODO now. Should I squash?

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 3 above)
Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Are you sure the four added tests cover the four updated methods with two execution branches in each?

Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: There are 8 tests added!

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 5 above)
Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Yep, looks good. I also ran the test on the previous release to make the patch doesn't fix something that's not broken:
```
$ git checkout 2.10.2
HEAD is now at aab745e7b Release v2.10.2

$ git diff 2.11.x 19f33f7072cbbd6edf103551298ff12a068209c2 -- tests | patch
patching file tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php

$ phpunit tests/Doctrine/Tests/DBAL/Query/QueryBuilderTest.php
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

.............................................................................     77 / 77 (100%)

Time: 1 second, Memory: 12.00 MB

OK (77 tests, 111 assertions)
```

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 3 above)
Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: I'm sorry. I think I saw what I expected to see.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 1 above)
Comment (morozov) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Looks good.

File: lib/Doctrine/DBAL/Query/QueryBuilder.php (hunk 5 above)
Comment (BenMorel) [reply lib/Doctrine/DBAL/Query/QueryBuilder.php]: Squashed!

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @BenMorel!
