### PR TITLE
Fix introspection of BLOB columns on SQL Server

### LINKED ISSUE #4760: SQL Server schema manager introspects BLOB columns as BINARY
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.x

```php
$table = new Table('test');
$table->addColumn('b', Types::BLOB);

$sm = $connection->createSchemaManager();
$sm->dropAndCreateTable($table);

$table = $sm->listTableDetails('test');
var_dump($table->getColumn('b')->getType()->getName());
// binary
```
Found during the work on #4759 ([build](https://github.com/doctrine/dbal/pull/4759/checks?check_run_id=3438387653)).

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #4760.

### CODE REVIEW

File: tests/Functional/Schema/SchemaManagerFunctionalTestCase.php [hunk 1]
```diff
@@ -885,17 +886,14 @@ public function testChangeColumnsTypeWithDefaultValue(): void
     public function testListTableWithBlob(): void
     {
         $table = new Table('test_blob_table');
-        $table->addColumn('id', 'integer', ['comment' => 'This is a comment']);
```
Comment (morozov) [inline tests/Functional/Schema/SchemaManagerFunctionalTestCase.php:888]: This column and assertions are irrelevant to the test.

**Review by greg0ire — APPROVED** [review]
