### PR TITLE
#4437 MSSQL adds a redundant ORDER BY clause when with subquery with …

### LINKED ISSUE #4437: MSSQL adds a redundant ORDER BY clause when with subquery with ORDER BY
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12

#### Summary

I have a query where in the ORDER BY clause I have a subquery with an ORDER BY clause, when I limit the query I get an incorrect query with redundant ORDER BY clause

#### Current behaviour

Input sql
``` sql
SELECT col1 FROM test ORDER BY ( SELECT col2 from test ORDER BY col2 )
```
Output sql
``` sql
SELECT col1 FROM test ORDER BY ( SELECT col2 from test ORDER BY col2 ) ORDER BY (SELECT 0) OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

#### How to reproduce

``` php
/** @var SQLServerPlatform */
$platform;
$querySql = 'SELECT col1 FROM test ORDER BY ( SELECT col2 from test ORDER BY col2 )';
$sql = $platform->modifyLimitQuery($querySql, 10);
```

#### Expected behaviour

``` sql
SELECT col1 FROM test ORDER BY ( SELECT col2 from test ORDER BY col2 ) OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

### PR DESCRIPTION
**Pull request by trusek**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4437

#### Summary

Currently, it is checking the last ORDER BY clause if after this clause the number of open brackets is different from the number of closed brackets, then it adds an ORDER BY clause. 
I changed the logic so that ORDER BY was added when, among all ORDER BY instances found in the query, the condition that number of open brackets is different than number of closed brackets for a particular clause is met.
Overall, I check every occurrence of ORDER BY, not just the last.

### CODE REVIEW

File: lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php [hunk 1]
```diff
@@ -103,17 +103,29 @@ protected function doModifyLimitQuery($query, $limit, $offset = null)
...
+            $orderByAlreadyExists = false;
+            $tempMatchesCount     = $matchesCount;
+            while ($tempMatchesCount && ! $orderByAlreadyExists) {
+                $orderByPos           = $matches[0][--$tempMatchesCount][1];
+                $openBracketsCount    = substr_count($query, '(', $orderByPos);
+                $closedBracketsCount  = substr_count($query, ')', $orderByPos);
+                $orderByAlreadyExists = ($openBracketsCount - $closedBracketsCount === 0);
+            }
+
+            $shouldAddOrderBy = ! $orderByAlreadyExists;
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:125]: Would it make sense to move all this logic into a separate `private function shouldAddOrderBy(): bool`? It could help avoid awkward variable names like `$tmpMatchesCount` and reduce the complexity of this method.

File: lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php [hunk 2]
```diff
@@ -103,17 +103,29 @@ protected function doModifyLimitQuery($query, $limit, $offset = null)
...
+            //  number of open parentheses after the occurrence of the clause is equal to
+            //  number of closed brackets after the occurrence of the clause,
+            // it means that ORDER BY is included in the query being checked
+            $orderByAlreadyExists = false;
+            $tempMatchesCount     = $matchesCount;
+            while ($tempMatchesCount && ! $orderByAlreadyExists) {
+                $orderByPos           = $matches[0][--$tempMatchesCount][1];
+                $openBracketsCount    = substr_count($query, '(', $orderByPos);
+                $closedBracketsCount  = substr_count($query, ')', $orderByPos);
+                $orderByAlreadyExists = ($openBracketsCount - $closedBracketsCount === 0);
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:122]: The parentheses look redundant here. Not sure why the coding standard didn't flag them.

**Review by morozov — COMMENTED** [review]
Thank you for the patch, @trusek. In addition to the unit test, it would be good to have an integration test that confirms that the simplified SQL also works and yields the expected results. See the [testing guidelines](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.12/reference/testing.html#integration-tests) and `Doctrine\Tests\DBAL\Functional\ModifyLimitQueryTest`.

File: lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php (hunk 2 above)
Comment (trusek) [reply lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php]: I simplified this into 
```php
$orderByAlreadyExists = $openBracketsCount === $closedBracketsCount;
````

Comment (morozov) [reply lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php]: This is even better.

**Comment by trusek** [comment]
I have a problem with an integration test. In SQL Server, the ORDER BY clause in a subquery must come together with TOP, OFFEST or FOR XML [(ms_docs),](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15#limitations-and-restrictions) so I figured I'd use a double `modifyLimitQuery` call to fit my case, but that creates bugs in other database engines e.g. IBM DB2 or SQL Server 2008. What am I supposed to do now?

File: lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php [hunk 3]
```diff
@@ -143,4 +131,35 @@ protected function doModifyLimitQuery($query, $limit, $offset = null)
...
+            return true;
+        }
+
+        // ORDER BY instance may be in a subquery after ORDER BY
+        // e.g. SELECT col1 FROM test ORDER BY (SELECT col2 from test ORDER BY col2)
+        // if in the searched query ORDER BY clause was found where
+        //  number of open parentheses after the occurrence of the clause is equal to
+        //  number of closed brackets after the occurrence of the clause,
+        // it means that ORDER BY is included in the query being checked
+        while ($matchesCount) {
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:154]: Please avoid implicit conversion to boolean. It should be `$matchesCount > 0`.

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 4]
```diff
@@ -195,4 +195,17 @@ private function assertLimitResult(
...
+
+    public function testLimitWhenOrderByWithLimitedSubquery(): void
+    {
+        $this->connection->insert('modify_limit_table2', ['test_int' => 1]);
+        $this->connection->insert('modify_limit_table2', ['test_int' => 2]);
+
+        $subquery        = 'SELECT test_int FROM modify_limit_table2';
+        $p               = $this->connection->getDatabasePlatform();
+        $limitedSubquery = $p->modifyLimitQuery($subquery, 1, 0);
+        $sql             = 'SELECT test_int FROM modify_limit_table2 ORDER BY (' . $limitedSubquery . ') ASC';
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:207]: It doesn't look like the case you originally tried to implement. The one in the unit test looks quote generic and should work with most of the platforms while this one is quite exotic.

File: lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php [hunk 5]
```diff
@@ -143,4 +131,35 @@ protected function doModifyLimitQuery($query, $limit, $offset = null)
...
+        $matchesCount = preg_match_all('/[\\s]+order\\s+by\\s/im', $query, $matches, PREG_OFFSET_CAPTURE);
+        if ($matchesCount === 0) {
+            return true;
+        }
+
+        // ORDER BY instance may be in a subquery after ORDER BY
+        // e.g. SELECT col1 FROM test ORDER BY (SELECT col2 from test ORDER BY col2)
+        // if in the searched query ORDER BY clause was found where
+        //  number of open parentheses after the occurrence of the clause is equal to
+        //  number of closed brackets after the occurrence of the clause,
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:152]: Is extra indentation here intended or it's a typo?

Comment (trusek) [reply lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:152]: I did this on purpose to highlight the condition. Is it wrong?

Comment (morozov) [reply lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:152]: It doesn't look highlighting to me. If you want it highlighted, you could probably use some punctuation or markup. Otherwise, just leave it as plain tex.

**Comment by trusek** [comment]
I have no idea how to create a functional test for this case.
When I try to test SQL Server 2016, TOP, OFFEST or FOR XML is required for a subquery with ORDER BY [[ms_docs],](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15#limitations-and-restrictions) but it is incorrect for sqlite because the syntax is wrong.

**Comment by morozov** [comment]
> I have no idea how to create a functional test for this case.

It should be the query that made you make this change in the codebase.

> it is incorrect for sqlite because the syntax is wrong

Please make it as generic as possible and skip on those platforms that don't support this syntax.

**Comment by trusek** [comment]
I used QueryBuilder to create a subquery with ORDER BY. Which eliminated syntax errors for other database engines.
For some reason the MariaDB and MySql pipeline crashes with an error:
```
OK, but incomplete, skipped, or risky tests!
Tests: 5772, Assertions: 10176, Skipped: 672, Incomplete: 11.

Generating code coverage report in Clover XML format ... done [00:00.479]
/home/runner/work/_temp/1dcb457b-658c-4781-ba88-0ada93656118.sh: line 1:  5764 Segmentation fault      (core dumped) vendor/bin/phpunit -c ci/github/phpunit/mysqli.xml --coverage-clover=coverage.xml
Error: Process completed with exit code 139.
```

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 6]
```diff
@@ -195,4 +199,33 @@ private function assertLimitResult(
...
+        $this->connection->insert('modify_limit_table2', ['test_int' => 1]);
+        $this->connection->insert('modify_limit_table2', ['test_int' => 2]);
+
+        $subquery = $this->connection->createQueryBuilder()
+            ->select('test_int')
+            ->from('modify_limit_table2')
+            ->orderBy('test_int')
+            ->setMaxResults(1);
+
+        $sql = 'SELECT test_int FROM modify_limit_table2 ORDER BY (' . $subquery->getSQL() . ') ASC';
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:227]: What does this query try to achieve? It returns both rows in their original order. Why is this `ORDER BY` clause is needed? Additionally, it's different from the one in the unit test: the `LIMIT` clause is applied to the inner query which in turn doesn't have a sub-query which the original issue is above.

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 7]
```diff
@@ -195,4 +199,33 @@ private function assertLimitResult(
...
+    {
+        $platform = $this->connection->getDatabasePlatform();
+        if ($platform instanceof DB2Platform) {
+            self::markTestSkipped('Generated SQL is invalid');
+        }
+
+        $platformName = get_class($platform);
+        if (
+            $platformName === SQLServer2008Platform::class
+            || $platformName === SQLServer2005Platform::class
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:213]: The `get_class()` could be avoided if coded as `if ($platform instanceof SQLServerPlatform && ! $platform instanceof SQLServer2012Platform)`.

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 8]
```diff
@@ -195,4 +199,33 @@ private function assertLimitResult(
             self::assertCount(count($expectedResults), $data);
         }
     }
+
+    public function testLimitWhenOrderByWithSubqueryWithOrderBy(): void
+    {
+        $platform = $this->connection->getDatabasePlatform();
+        if ($platform instanceof DB2Platform) {
+            self::markTestSkipped('Generated SQL is invalid');
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:207]: Is it a bug or DB2 just doesn't support LIMIT in subqueries? If it's a bug, the test should be marked as incomplete, not skipped.

Comment (trusek) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:207]: I don't know this engine.
If I set a limit on the query, I get a DBALException:
<details>
  <summary>Error</summary>

  ```
1) Doctrine\Tests\DBAL\Functional\ModifyLimitQueryTest::testLimitWhenOrderByWithSubqueryWithOrderBy
Exception: [Doctrine\DBAL\Exception] An exception occurred while executing 'SELECT db22.* FROM (SELECT db21.*, ROW_NUMBER() OVER() AS DC_ROWNUM FROM (SELECT test_int FROM modify_limit_table2 ORDER BY (SELECT db22.* FROM (SELECT db21.*, ROW_NUMBER() OVER() AS DC_ROWNUM FROM (SELECT test_int FROM modify_limit_table2 ORDER BY test_int ASC) db21) db22 WHERE db22.DC_ROWNUM <= 1) ASC) db21) db22 WHERE db22.DC_ROWNUM <= 10':

db2_execute(): Statement Execute Failed

With queries:
5. SQL: 'SELECT db22.* FROM (SELECT db21.*, ROW_NUMBER() OVER() AS DC_ROWNUM FROM (SELECT test_int FROM modify_limit_table2 ORDER BY (SELECT db22.* FROM (SELECT db21.*, ROW_NUMBER() OVER() AS DC_ROWNUM FROM (SELECT test_int FROM modify_limit_table2 ORDER BY test_int ASC) db21) db22 WHERE db22.DC_ROWNUM <= 1) ASC) db21) db22 WHERE db22.DC_ROWNUM <= 10' Params: 
4. SQL: 'INSERT INTO modify_limit_table2 (test_int) VALUES (?)' Params: '2'
3. SQL: 'INSERT INTO modify_limit_table2 (test_int) VALUES (?)' Params: '1'
2. SQL: 'TRUNCATE modify_limit_table2 IMMEDIATE' Params: 
1. SQL: 'TRUNCATE modify_limit_table IMMEDIATE' Params: 

Trace:
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/DBALException.php:159
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Connection.php:2121
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Connection.php:1264
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Connection.php:935
/home/runner/work/dbal/dbal/tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:185
/home/runner/work/dbal/dbal/tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:213
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:1536
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:1142
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestResult.php:730
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:883
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/TextUI/Command.php:148
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/TextUI/Command.php:101
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/phpunit:61


/home/runner/work/dbal/dbal/tests/Doctrine/Tests/DbalFunctionalTestCase.php:110
  ```
</details>
However, when I do not limit the result, I have a warning in `db2_fetch_assoc()`:
<details>
  <summary>Error</summary>

  ```
  1) Doctrine\Tests\DBAL\Functional\ModifyLimitQueryTest::testLimitWhenOrderByWithSubqueryWithOrderBy
Exception: [PHPUnit\Framework\Error\Warning] db2_fetch_assoc(): Fetch Failure

With queries:
5. SQL: 'SELECT db22.* FROM (SELECT db21.*, ROW_NUMBER() OVER() AS DC_ROWNUM FROM (SELECT test_int FROM modify_limit_table2 ORDER BY (SELECT test_int FROM modify_limit_table2 ORDER BY test_int ASC) ASC) db21) db22 WHERE db22.DC_ROWNUM <= 10' Params: 
4. SQL: 'INSERT INTO modify_limit_table2 (test_int) VALUES (?)' Params: '2'
3. SQL: 'INSERT INTO modify_limit_table2 (test_int) VALUES (?)' Params: '1'
2. SQL: 'TRUNCATE modify_limit_table2 IMMEDIATE' Params: 
1. SQL: 'TRUNCATE modify_limit_table IMMEDIATE' Params: 

Trace:
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php:300
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Driver/IBMDB2/DB2Statement.php:356
/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Connection.php:935
/home/runner/work/dbal/dbal/tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:185
/home/runner/work/dbal/dbal/tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:215
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:1536
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:1142
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestResult.php:730
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:883
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/TextUI/Command.php:148
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/src/TextUI/Command.php:101
/home/runner/work/dbal/dbal/vendor/phpunit/phpunit/phpunit:61
  ```
</details>

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php (hunk 6 above)
Comment (trusek) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php]: I changed query and input so that ORDER BY means something.
I limit the query because I am getting the error that the subquery returned more than 1 row.

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 9]
```diff
@@ -195,4 +200,51 @@ private function assertLimitResult(
...
+        $this->connection->insert('modify_limit_table2', ['test_int' => 3]);
+        $this->connection->insert('modify_limit_table2', ['test_int' => 1]);
+        $this->connection->insert('modify_limit_table2', ['test_int' => 2]);
+
+        $subquery = $this->connection->createQueryBuilder()
+            ->select('test_int')
+            ->from('modify_limit_table2', 'T2')
+            ->where('T1.id=T2.id')
+            ->orderBy('test_int')
+            ->setMaxResults(1);
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:244]: This still doesn't reproduce the reported issue. The LIMIT clause is applied to the sub-query which doesn't have a subquery in it. While the issue is about applying a LIMIT clause to a query with a sub-query.

Comment (trusek) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:244]: In `assertLimitResult()` LIMIT is applied to query and as parameter query with the subquery is passed.

Comment (morozov) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:244]: Why then do you need to have a LIMIT clause in the sub-query? The query in the unit test doesn't have it.

This is why it doesn't on Oracle: by wrapping it in a sub-query we're making it a grand-child of the top-level query which is unavailable in its context ([ref](https://community.oracle.com/tech/developers/discussion/1040136/simple-subquery-with-error-ora-00904-invalid-identifier)).

Comment (trusek) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:244]: I limit the subquery otherwise I am getting the error that the subquery returned more than 1 row. I'll change the unit test.

I tested this query for Oracle on [livesql.oracle](https://livesql.oracle.com/) and its working, but Oracle Database 19c is there.

Comment (morozov) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:232]: By doing so, you're making the test not work on half of the supported platforms. You can limit the number of the rows selected by the inner query by something like `SELECT T1.id`. Again, the test and the fix are about applying a limit to the outer query, not to the limit one.

Maybe we could start with a practical case. Why do you need this?

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 10]
```diff
@@ -195,4 +201,45 @@ private function assertLimitResult(
...
+        $this->connection->insert('modify_limit_table2', ['test_int' => 3]);
+        $this->connection->insert('modify_limit_table2', ['test_int' => 1]);
+        $this->connection->insert('modify_limit_table2', ['test_int' => 2]);
+
+        $subquery = $this->connection->createQueryBuilder()
+            ->select('test_int')
+            ->from('modify_limit_table2', 'T2')
+            ->where('T1.id=T2.id')
+            ->orderBy('test_int')
+            ->getSQL();
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:226]: Why do you need a query builder to build this query?

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php [hunk 11]
```diff
@@ -195,4 +201,45 @@ private function assertLimitResult(
...
+
+    public function testLimitWhenOrderByWithSubqueryWithOrderBy(): void
+    {
+        $platform = $this->connection->getDatabasePlatform();
+        if ($platform instanceof DB2Platform) {
+            self::markTestSkipped('DB2 cannot handle ORDER BY in subquery');
+        }
+
+        $driver = $this->connection->getDriver();
+        if ($driver instanceof PDO\OCI\Driver || $driver instanceof OCI8Driver) {
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php:213]: This condition should be based on `$platform`, not on `$driver`.

File: tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php (hunk 9 above)
Comment (trusek) [reply tests/Doctrine/Tests/DBAL/Functional/ModifyLimitQueryTest.php]: I made a mistake with error that subquery returns more than 1 line. The error occurred before my query change.
In my work I ran into this bug and rewrote the subquery to join, but thought doctrine should handle it.

File: lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php [hunk 12]
```diff
@@ -143,4 +131,35 @@ protected function doModifyLimitQuery($query, $limit, $offset = null)
 
         return $query;
     }
+
+    /**
+     * @param string $query
+     */
+    protected function shouldAddOrderBy($query): bool
```
Comment (morozov) [inline lib/Doctrine/DBAL/Platforms/SQLServer2012Platform.php:138]: Does this have to be `protected`? Let's make it private unless it's expected to be visible to the subclasses.

**Review by morozov — COMMENTED** [review]
Apart from the new `protected` method, looks good. Please squash.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @trusek.
