### PR TITLE
Fix parsing SQLite FK reference not containing whitepace

### LINKED ISSUE #5584: Changing/renaming/dropping columns on sqlite doesn't work in v 3.4.x
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.x

#### Summary

I ran into the issue while running migrations in laravel 9.0, which uses docrine/dbal behind the curtains.

Any kind of change (dropColumn, renameColumn, change) to columns on sqlite db, throws an error

#### Current behaviour

Migrations throw an exception:
 ErrorException 

  Undefined array key -1
```
  at vendor/doctrine/dbal/src/Schema/SqliteSchemaManager.php:605
    601▕         $foreignKeyCount   = count($foreignKeyDetails);
    602▕ 
    603▕         foreach ($columns as $i => $column) {
    604▕             // SQLite identifies foreign keys in reverse order of appearance in SQL
  ➜ 605▕             $columns[$i] = array_merge($column, $foreignKeyDetails[$foreignKeyCount - $column['id'] - 1]);
    606▕         }
    607▕ 
    608▕         return $columns;
    609▕     }

```

I traced the issue to this function, where the regex fails to match what createSql returns
```php
 private function getForeignKeyDetails($table)
    {
        $createSql = $this->getCreateTableSQL($table);
        \Log::info($createSql);
//CREATE TABLE "files" ("id" integer not null primary key autoincrement, "user_id" integer not null, "uuid" varchar not null, "type" varchar not null, "state" varchar not null, "name" varchar not null, ... "is_flagged" tinyint(1), foreign key("user_id") references "users"("id"))  
        dd( preg_match_all(
            '#
                (?:CONSTRAINT\s+(\S+)\s+)?
                (?:FOREIGN\s+KEY[^)]+\)\s*)?
                REFERENCES\s+\S+\s+(?:\([^)]+\))?
                (?:
                    [^,]*?
                    (NOT\s+DEFERRABLE|DEFERRABLE)
                    (?:\s+INITIALLY\s+(DEFERRED|IMMEDIATE))?
                )?#isx',
            $createSql,
            $match
        ));
// 0
        if (
            preg_match_all(
                '#
                    (?:CONSTRAINT\s+(\S+)\s+)?
                    (?:FOREIGN\s+KEY[^)]+\)\s*)?
                    REFERENCES\s+\S+\s+(?:\([^)]+\))?
                    (?:
                        [^,]*?
                        (NOT\s+DEFERRABLE|DEFERRABLE)
                        (?:\s+INITIALLY\s+(DEFERRED|IMMEDIATE))?
                    )?#isx',
                $createSql,
                $match
            ) === 0
        ) {
            return [];
        }

```
Somehow the regex fails to match the following 
#### How to reproduce

1. Setup a basic project with laravel, use sqlite as connection (when running tests you might run into this use case)
```
DB_CONNECTION=sqlite
DB_HOST=database/database.sqlite
```
2. Create a table with a foreign key using a migration 
3. Create another migration where you try to modify a column from the previous

#### Expected behaviour

The migration should run w/o a problem.

#### Workaround:
Installed "doctrine/dbal": "^2.13.3" and it works w/o a problem.

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug

Fixes #5584.

### CODE REVIEW

File: src/Schema/SqliteSchemaManager.php [hunk 1]
```diff
@@ -626,7 +626,7 @@ private function getForeignKeyDetails($table)
                 '#
                     (?:CONSTRAINT\s+(\S+)\s+)?
                     (?:FOREIGN\s+KEY[^)]+\)\s*)?
-                    REFERENCES\s+\S+\s+(?:\([^)]+\))?
+                    REFERENCES\s+\S+\s*(?:\([^)]+\))?
```
Comment (morozov) [inline src/Schema/SqliteSchemaManager.php:629]: Note that this pattern is still invalid since the `\S+` expression matches the entire `"users"("id"));` substring of the SQL in the newly added test rendering the rest of the expressions on this line irrelevant.

The proper parsing logic would be more complex and might require a real parser since the double quote that terminates the table name acts as a token separator from the SQL syntax perspective but isn't a whitespace character from the regular expression perspective.

Likely, we can get away with this for now since these expressions don't capture anything. The actual referenced table and the column names are sourced from `PRAGMA foreign_key_list()`.

Comment (greg0ire) [reply src/Schema/SqliteSchemaManager.php:629]: Wouldn't that be solved by using `[^\s"]` instead of `\S`?

Comment (morozov) [reply src/Schema/SqliteSchemaManager.php:629]: > the double quote that terminates the table name acts as a token separator from the SQL syntax perspective

I guess this isn't entirely accurate since `users(id)` would be also a valid expression but it doesn't contain whitespace or a quote.

At the same time, an identifier can contain quotes, e.g. `"foo""bar"` but the proposed pattern will need an optional leading quote and will match only the first half of the identifier.

**Review by greg0ire — APPROVED** [review]

File: src/Schema/SqliteSchemaManager.php (hunk 1 above)
Comment (morozov) [reply src/Schema/SqliteSchemaManager.php:629]: A note for posterity: there is a quite mature parser generator [ANTLR](https://www.antlr.org/) which allows defining grammar in an abstract syntax and generating parsers for a variety of languages including PHP. For example, [Debezium](https://debezium.io/) uses ANTLR-based parsers for parsing arbitrary DDL statements of more database platforms than the DBAL supports.

If we ever get to the point where we'd want to properly support arbitrary identifiers (e.g. `CREATE TABLE "FOREIGN KEY u REFERENCES users(id)"` ← good luck parsing that with regular expressions), we might try using ANTLR.

UPD: using ANTLR as a parser was later prototyped in https://github.com/doctrine/dbal/pull/5694.
