### PR TITLE
Mark SQLite platform as supporting foreign keys

### LINKED ISSUE #5365: SQLite should properly check if foreign keys are supported and/or omit foreign key statements when a table diff is analyzed
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.5

#### Summary

while investigating some differences reported by the `doctrine:migration:diff` command I figured out that there is every time a diff is reported for tables containing foreign keys because of `ManyToOne` relations. when inspecting the generated migration file I've seen that the up method contains foreign keys while the down method does not. as far as I could see the code sometimes checks if foreign keys are supported before generating the relevant statements and sometimes not.

as foreign keys are a feature that can be turned on/off for an SQLite database it probably makes sense to replace the hardcoded `false` in `SqlitePlatform` in method `supportsForeignKeyConstraints` with a call to `PRAGMA foreign_keys;` where the result of `0` means it is disabled so the method should return `false` while the result `1` should return `true`.

additionally, the `getAlterTableSQL` in `SqlitePlatform` should probably check if foreign keys are supported to generate the correct statements not containing the foreign keys. currently, they are generated regardless if SQLite supports it or not.

#### Current behaviour

table diff migration generates a migration containing foreign keys for SQLite even if the method `supportsForeignKeyConstraints` returns every time `false`.

#### How to reproduce

1. create two entities with a `ManyToOne` relation
2. run `symfony console doc:mig:diff --from-empty-schema`
3. run `symfony console doc:mig:mig`
4. run `symfony console doc:mig:diff`

step 4 now generates a diff containing foreign key statements where I actually would expect that nothing is created

#### Expected behaviour

omit the foreign key statements in the create table statement for a diff
OR
determine if SQLite supports foreign keys so that the check is database feature dependent
OR 
add checks if foreign keys are supported in more places which are currently assume they are supported (mainly in the area for the `TableDiff` handling

### PR DESCRIPTION
**Pull request by morozov**
This patch re-introduces the changes reverted in https://github.com/doctrine/dbal/pull/5411. These changes will no longer break the ORM tests thanks to the following prep work done:

1. https://github.com/doctrine/dbal/pull/5416
2. https://github.com/doctrine/dbal/pull/5425
3. https://github.com/doctrine/orm/pull/9799

The compatibility of the changes with the ORM test suite has been tested with ORM 2.13.x and 3.0.x on SQLite, MySQL, and PostgreSQL.

### CODE REVIEW

File: src/Platforms/AbstractPlatform.php [hunk 1]
```diff
@@ -3804,10 +3804,18 @@ public function supportsPrimaryConstraints()
...
      *
+     * @deprecated All platforms should support foreign key constraints.
+     *
      * @return bool
      */
     public function supportsForeignKeyConstraints()
     {
+        Deprecation::triggerIfCalledFromOutside(
+            'doctrine/dbal',
+            'https://github.com/doctrine/dbal/pulls/5409',
```
Comment (greg0ire) [inline src/Platforms/AbstractPlatform.php]:
```suggestion
            'https://github.com/doctrine/dbal/pull/5409',
```

**Review by greg0ire — APPROVED** [review]

**Comment by arnegroskurth** [comment]
Great! Is there an ETA for the 3.4.0 release?

**Comment by greg0ire** [comment]
This week-end, maybe.
