### PR TITLE
Remove the APIs deprecated in DBAL 3.x

### LINKED ISSUE #5525: Inconsistent parameter indexes passed to the logging middleware
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.7

#### Summary

Correct me if this is intended and documented somewhere, otherwise it seems like a bug to me.

#### Current behaviour

The issue is bind params are strictly 1-based [1] [2], ie. always starting with index 1, not 0.

But in some places like https://github.com/doctrine/dbal/blob/2aec3f8da5f601462162d9b90d013554b240292b/src/Schema/SqliteSchemaManager.php#L207 the positional params are passed to DBAL in 0-based fashion.

Quick demo https://3v4l.org/s8hef shows the conversion must happen somewhere in the DBAL, as 0-based params are not accepted by SQLite natively.

I noticed this issue when using `Doctrine\DBAL\Logging\SQLLogger::startQuery()` which receives the passed params to DBAL, ie. params starting with index 0.

#### How to reproduce

Can some DBAL connection query method like:

```
$conn->fetchAllAssociative('SELECT * FROM PRAGMA_TABLE_INFO (?)', [$tableName]);
```

and notice what params are passed to `Doctrine\DBAL\Logging\SQLLogger::startQuery()`. Currently, the params start with `0` which is wrong as such params are not valid.

#### Expected behaviour

I expect `Doctrine\DBAL\Logging\SQLLogger::startQuery()` to always return params that are valid and can be used to reproduce the logged query /w and /wo DBAL.

I propose DBAL to never accept 0-based params so no transformation is needed. This seems to be already the case with `mysqli` driver.

[1] https://www.php.net/manual/en/pdostatement.bindparam.php
> For a prepared statement using question mark placeholders, this will be the 1-indexed position of the parameter. 

[2] https://www.php.net/manual/en/sqlite3stmt.bindparam.php
> Positional parameters start with 1.

### PR DESCRIPTION
**Pull request by morozov**
See the following pull requests for reference:

1. https://github.com/doctrine/dbal/pull/5550
2. https://github.com/doctrine/dbal/pull/5556
3. https://github.com/doctrine/dbal/pull/5558

### CODE REVIEW

**Comment by morozov** [comment]
Moved to draft. Let's get the deprecation merged up first (https://github.com/doctrine/dbal/pull/5561).

File: tests/Functional/Driver/OCI8/StatementTest.php [hunk 1]
```diff
@@ -35,24 +35,6 @@ public function testQueryConversion(string $query, array $params, array $expecte
...
 
-    /**
-     * Low-level approach to working with parameter binding
-     *
-     * @param mixed[] $params
-     * @param mixed[] $expected
-     *
-     * @dataProvider queryConversionProvider
-     */
-    public function testStatementBindParameters(string $query, array $params, array $expected): void
```
Comment (morozov) [inline tests/Functional/Driver/OCI8/StatementTest.php:46]: This test was implemented in https://github.com/doctrine/dbal/pull/3738 and used to reuse the existing data provider of the `testQueryConversion()` method.

The data provider provides positional statement parameters as a list which is still supported by the "shortcut" methods like `Connection::executeQuery()` but is no longer supported by the `Statement` class being tested. At the same time, this test doesn't and didn't need to reuse the data provider which focuses on testing the SQL parser while the test itself is meant to cover binding positional parameters directly to the statement.

The test has been renamed, reworked, and moved to the end of the suite in order to not be located between the other test and its data provider.

File: UPGRADE.md [hunk 2]
```diff
@@ -8,6 +8,15 @@ awareness about deprecated code.
 
 # Upgrade to 4.0
 
+## BC BREAK: made parameter type in driver-level `Statement::bind*()` methods required.
+
+The `$type` parameter of the driver-level `Statement::bindParam()` and `::bindValue()` has been made required.
+
+## BC BREAK: removed support using NULL as prepared statement parameter type.
```
Comment (greg0ire) [inline UPGRADE.md]:
```suggestion
## BC BREAK: removed support for using NULL as prepared statement parameter type.
```

File: src/Connection.php [hunk 3]
```diff
@@ -1318,15 +1317,6 @@ private function bindParameters(DriverStatement $stmt, array $params, array $typ
...
                     [$value, $bindingType] = $this->getBindingInfo($value, $type);
                 } else {
-                    if (array_key_exists($key, $types)) {
-                        Deprecation::trigger(
-                            'doctrine/dbal',
-                            'https://github.com/doctrine/dbal/pull/5550',
-                            'Using NULL as prepared statement parameter type is deprecated.'
-                                . 'Omit or use Parameter::STRING instead'
-                        );
-                    }
```
Comment (derrabus) [inline src/Connection.php:1328]: This basically means that the deprecation had no effect: It is still possible to pass `null` as type.

Comment (morozov) [reply src/Connection.php:1328]: This is not enforced at runtime because connection methods accept types as an array. If I misunderstand your point, could you illustrate it with a code snippet?

Passing NULL to the wrapper will likely result in `getBindingInfo()` returning NULL for `$bindingType` which in turn will cause an exception in the driver because the driver-level `bind*()` methods don't accept NULL.

Comment (derrabus) [reply src/Connection.php:1328]: > This is not enforced at runtime because connection methods accept types as an array.

This is okay, but then it did not make sense that we triggered that deprecation. The caller is warned about a call that continues to work.

> If I misunderstand your point, could you illustrate it with a code snippet?

If I understood the deprecation correctly, it is triggered on calls like this:

```php
$connection->executeQuery(
    sql: $sql,
    params: ['myParam' => 'foo'],
    types: ['myParam' => null]
);
```

The change you are suggesting is to remove the deprecation trigger without introducing a breaking change. The call above remains intact.

> Passing NULL to the wrapper will likely result in `getBindingInfo()` returning NULL for `$bindingType` which in turn will cause an exception in the driver because the driver-level `bind*()` methods don't accept NULL.

No, passing `null` has the same effect as omitting that particular parameter in the `$types` array: We fall back to string. This is literally what the line after this block does.

My suggesting would be to either:

* Revert the deprecation on 3.4.x or
* Throw if we encounter `null` in this array.

Comment (morozov) [reply src/Connection.php:1328]: I see. You're right. Should we just replace the`isset()` in the below condition with `array_key_exists()`? https://github.com/doctrine/dbal/blob/0cc7adc22ea3d81a425a48463044931e95693704/src/Connection.php#L1317-L1320

Comment (derrabus) [reply src/Connection.php:1328]: We could do that. That would trigger a `TypeError` on the call to `getBindingInfo()` because you've removed `null` from the union there.

**Review by derrabus — APPROVED** [review]
