### PR TITLE
Inject EventManager when using a custom platform

### LINKED ISSUE #3649: Platform-related events don't work if you specify a custom platform
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9/master

The event manager is only injected into the platform [in the `detectDatabasePlatform` method of Doctrine\DBAL\Connection](https://github.com/doctrine/dbal/blob/d6a1237/lib/Doctrine/DBAL/Connection.php#L388). If you specify a platform, then the detection method is never called and the event manager is not injected.

You can, after creating the Connection, get its event manager and set it on the platform yourself... I don't know if there are any events that might fire in the meantime that could be missed if done this way, but it seems not since `detectDatabasePlatform` is already only called "just-in-time."

If that's in fact sufficient it would still probably be an issue with the [documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/platforms.html) which indicates merely creating and passing the platform should be sufficient.

### PR DESCRIPTION
**Pull request by spideyfusion**
|      Q       |   A
|------------- | -----------
| Type         | bug
| Fixed issues | #3649

#### Summary

This fix ensures that schema-related events (e.g. `onSchemaAlterTable`) get fired when a `Connection` receives a `Platform` instead of relying on [auto-detection](https://github.com/doctrine/dbal/blob/82331b861727c15b1f457ef05a8729e508e7ead5/src/Connection.php#L284).

### CODE REVIEW

File: tests/ConnectionTest.php [hunk 1]
```diff
@@ -138,6 +138,20 @@ public function testConnectDispatchEvent(): void
...
     }
 
+    public function testEventDispatcherIsSetForCustomPlatform(): void
+    {
+        $eventManager = new EventManager();
+
+        $driverMock = $this->createMock(Driver::class);
+
+        $platformMock = $this->createMock(AbstractPlatform::class);
+        $platformMock->expects(self::once())
```
Comment (morozov) [inline tests/ConnectionTest.php]: Please make it a functional test, if possible. Just the fact that one DBAL component calls a method of another DBAL component doesn't mean anything from the API consumer standpoint.

Comment (spideyfusion) [reply tests/ConnectionTest.php]: @morozov Done. I have created a functional test.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Looks good to me. Thanks, @spideyfusion.

**Review by SenseException — APPROVED** [review]
