### PR TITLE
Fix deprecation on `ExpressionBuilder::literal()` with default type

### LINKED ISSUE #4906: PHP 8.1 - default value for type is wrong in ExpressionBuilder::literal
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.2

#### Summary

This PHP error happens with PHP 8.1:
`PHP Deprecated:  PDO::quote(): Passing null to parameter #2 ($type) of type int is deprecated in /home/mcmic/dev/doctrine/dbal/src/Driver/PDO/Connection.php on line 96`

You changed the default value in Connection::quote, but not in ExpressionBuilder::literal, which is:
```
    /**
     * Quotes a given input parameter.
     *
     * @param mixed    $input The parameter to be quoted.
     * @param int|null $type  The type of the parameter.
     *
     * @return string
     */
    public function literal($input, $type = null)
    {
        return $this->connection->quote($input, $type);
    }
```

But null is not a valid value anymore in PHP 8.1 as passing it to PDO::quote triggers the warning.

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #4906

### CODE REVIEW

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+        $platform = $this->connection->getDatabasePlatform();
+        if ($platform instanceof OraclePlatform) {
+            $qb->from('DUAL');
+        }
+
+        $result = $qb->execute();
+
+        self::assertInstanceOf(Result::class, $result);
+        self::assertEquals(42, $result->fetchOne());
+    }
```
Comment (greg0ire) [inline tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: Why not use a data provider here?

File: lib/Doctrine/DBAL/Connection.php [hunk 2]
```diff
@@ -2085,7 +2085,7 @@ private function _bindTypedValues($stmt, array $params, array $types)
      *
      * @return mixed[] [0] => the (escaped) value, [1] => the binding type.
```
Comment (greg0ire) [inline lib/Doctrine/DBAL/Connection.php]: Let's improve the phpdoc as well?
```suggestion
     * @return array{mixed, mixed} [0] => the (escaped) value, [1] => the binding type.
```

Comment (derrabus) [reply lib/Doctrine/DBAL/Connection.php]: Yeah, why not. The second component of the tuple has to be an `int` actually.

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php (hunk 1 above)
Comment (derrabus) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: I played with a data provider, but I couldn't find a solution that did not hurt the readability of the test. Maybe you have an idea? Then again, it's just two test cases.

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+use Doctrine\DBAL\Result;
+use Doctrine\Tests\DbalFunctionalTestCase;
+
+final class ExpressionBuilderTest extends DbalFunctionalTestCase
+{
+    public function testSelectStringLiteral(): void
+    {
+        $platform = $this->connection->getDatabasePlatform();
+        if ($platform instanceof DB2Platform) {
+            self::markTestSkipped('DB2 does not support SELECTing literals.');
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: It does. `AbstractPlatform::getDummySelectSQL()` works on all platforms and is used in many tests.

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+namespace Doctrine\Tests\DBAL\Functional\Query\Expression;
+
+use Doctrine\DBAL\ParameterType;
+use Doctrine\DBAL\Platforms\DB2Platform;
+use Doctrine\DBAL\Platforms\OraclePlatform;
+use Doctrine\DBAL\Result;
+use Doctrine\Tests\DbalFunctionalTestCase;
+
+final class ExpressionBuilderTest extends DbalFunctionalTestCase
```
Comment (morozov) [inline tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: This test is unnecessarily complex for such a simple issue and doesn't reflect any real case: the query builder will be never used and wasn't designed for building "dummy" queries.

Shouldn't have this problem been detected by static analysis?

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+        $platform = $this->connection->getDatabasePlatform();
+        if ($platform instanceof DB2Platform) {
+            self::markTestSkipped('DB2 does not support SELECTing literals.');
+        }
+
+        $qb   = $this->connection->createQueryBuilder();
+        $expr = $qb->expr();
+        $qb->select($expr->literal(42, ParameterType::INTEGER));
+
+        $platform = $this->connection->getDatabasePlatform();
```
Comment (greg0ire) [inline tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: This line can be removed, right?

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php (hunk 1 above)
Comment (greg0ire) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: Here is how I would do it: https://github.com/derrabus/dbal/pull/2, I know it's just 2 cases, but then when you read the data provider version, you know that it does the same actions.

Comment (derrabus) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: Thanks!

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php (hunk 3 above)
Comment (derrabus) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: Thanks for the pointer. I took inspiration from that method.

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php (hunk 4 above)
Comment (derrabus) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: > This test is unnecessarily complex for such a simple issue

That is correct. The issue I've had was that the `literal()` method was not covered by any test yet. And since `literal()` involves calling the driver connection, I felt that this kind of test was justified.

> and doesn't reflect any real case: the query builder will be never used and wasn't designed for building "dummy" queries.

Sure, an expression built with the `literal()` method would be used as a building block, as part of a comparison operation for instance. I could modify the test to cover a more realistic scenario, but that would make the test even more complex and you've already complained about its complexity.

I think the test is good as it is: It makes sure, the `literal()` method produces a literal that I can use inside a query on all supported platforms.

> Shouldn't have this problem been detected by static analysis?

Apparently, it wasn't. Then again, the PDO API started to behave picky about `null` values only recently, so maybe PHPStan/Psalm haven't caught up yet.

Comment (morozov) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: Just changing the return value of `getBindingInfo()` to `array{mixed, int}` is sufficient for Psalm to pick up the error:
```diff
-     * @return mixed[] [0] => the (escaped) value, [1] => the binding type.
+     * @return array{mixed, int} [0] => the (escaped) value, [1] => the binding type.
```
```
$ psalm
...
ERROR: MoreSpecificReturnType - lib/Doctrine/DBAL/Connection.php:2086:16 - The declared return type 'array{mixed, int}' for Doctrine\DBAL\Connection::getBindingInfo is more specific than the inferred return type 'array{mixed, int|null}' (see https://psalm.dev/070)
     * @return array{mixed, int} [0] => the (escaped) value, [1] => the binding type.


ERROR: LessSpecificReturnStatement - lib/Doctrine/DBAL/Connection.php:2101:16 - The type 'array{mixed, int|null}' is more general than the declared return type 'array{mixed, int}' for Doctrine\DBAL\Connection::getBindingInfo (see https://psalm.dev/129)
        return [$value, $bindingType];
```
I believe we do not need a unit test for this issue since it can be analyzed statically once the code is properly annotated.

Comment (derrabus) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: All right, I'm moving the test to a separate PR to unblock the merge here. The fact that `literal()` is not covered by tests at all still bugs me and we should solve in some way.

**Review by morozov — APPROVED** [review]

File: tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php (hunk 4 above)
Comment (morozov) [reply tests/Doctrine/Tests/DBAL/Functional/Query/Expression/ExpressionBuilderTest.php]: FWIW, the `$type` argument of `literal()` will be removed in `4.0.x`, so it's okay that it's not extensively tested.

I'd even challenge the validity of the `ExpressionBuilder::literal()` and `Connection::quote()` methods as such:
1. If you need to put a value into the statement when the connection is available, you should use a parameter.
2. If you do not have a connection, you won't be able to use those methods.
3. If you have a connection but you want to generate an SQL literal for future use with a different connection, you're likely asking for trouble because the other connection may interpret your literal differently.
